### ISSUE TITLE
UINT32 IS BORKED

### ISSUE THREAD

**Issue by invisig0th** [msgpack/msgpack-python#101]
In 0.4.2 ( and some prior versions ) the C implementation for uint32 decoding is broken:

In unpack_callback_uint32 ( from unpack.h ) the line:
    p = PyInt_FromLong((long)d);

causes _unsigned_ 32 bit integers to unpack as negative values in python:
ie. the hex "ce f0 00 00 00" unpacks to -268435456 rather than 4026531840

this can lead to catastrophic data corruption at the application layer when dealing with integers between 2 and 4 billion.

I would recommend changing to:
  p = PyLong_FromUnsignedLong((unsigned long)d);

with a possible check against INT32_MAX ( _not_ UINT32_MAX ) to create the slightly smaller/faster PyInt_FromLong() case, but only when the value will not trigger negative interpretation as a PyInt.

**Comment by ThomasWaldmann** [comment]
Also affects 0.3.0 (this is the version in ubuntu 14.04 lts):

https://github.com/msgpack/msgpack-python/blob/0.3.0/msgpack/unpack.h#L75
