### ISSUE TITLE
cannot serialize a slice with msgpack-python 0.4.4.

### ISSUE THREAD

**Issue by lebedov** [msgpack/msgpack-python#122]
It doesn't appear to be possible to serialize slice objects with msgpack-python 0.4.4 (used with Python 2.7.6 on Ubuntu 14.04.1). Is there any reason why they shouldn't be? I recall that Python pickle used to be [unable to serialize slices](http://bugs.python.org/issue1191699), but that appears to have been fixed some time ago.

**Comment by jnothman** [comment]
If you want to be able to deserialize it on the other end, you'll need
custom code anyway...

**Comment by lebedov** [comment]
Currently, yes, but I'm curious whether there is any technical reason why serialization/deserialization of slices could not be performed by msgpack-python natively.

**Comment by methane** [comment]
Because msgpack is cross language serialization format like JSON.

**Comment by lebedov** [comment]
Although the format is cross-platform, msgpack-python does contain code to handle Python-specific data structures such as lists, tuples, etc. Not sure why the same can't be done for slices.

**Comment by methane** [comment]
@lebedov I follow design of `json` standard library.

```
In [1]: import json
In [2]: json.dumps((1,2))
Out[2]: '[1, 2]'
In [3]: json.dumps([1,2])
Out[3]: '[1, 2]'
In [4]: json.dumps(slice(1,2))
TypeError: slice(1, 2, None) is not JSON serializable
```

I feel this is natural.  But I'll drop tuple support in the future since msgpack now has Ext type.
