### ISSUE TITLE
last pypi release has critical issues, do a new release

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#127]
See my comments at the end of the (IMHO prematurely closed) issue #124.

I am opening this ticket as I do not know whether anybody cares about comments on closed tickets.

The problem is that just fixing a bug in the repo is not enough to fix it out there in the world, you need to make a new pypi release. And, just as a suggestion, you could keep critical bug tickets OPEN as a reminder until a pypi release has been done.

It's in this case also impossible to write safe code AND use a unbroken version of msgpack, see my second comment in #124.

**Comment by thedrow** [comment]
So which msgpack version is safe to use?
Only master?

**Comment by bwesterb** [comment]
Versions **before** 7eb371f8278941fb2323e0c2333ed89c88ab822b

**Comment by methane** [comment]
I'm sorry about late, I uploaded 0.4.6 on PyPI for now.
I will build Windows wheels later.

**Comment by ThomasWaldmann** [comment]
Hey @methane!, thanks for new release, does it fix both mentioned problems?

**Comment by methane** [comment]
Sure.

**Comment by methane** [comment]
Windows wheels are uploaded.
