### ISSUE TITLE
Streaming unpacker memory usage

### ISSUE THREAD

**Issue by HelloZeroNet** [msgpack/msgpack-python#129]
I'm using the msgpack to parse incoming messages from socket, and looks like the unpacker object is keeping the messages even after parse is done. Am I doing something wrong?

Here is a simple mockup:
```python
import msgpack, gc

class Connection:
	def __init__(self):
		self.unpacker = msgpack.Unpacker()
		# Incoming message from socket
		self.unpacker.feed(msgpack.packb({"hello": "hello"*1024*1024}))
		# Parse messages
		for message in self.unpacker:
			print len(message["hello"])
			del(message) # Make sure message is gone

connections = []
for i in range(20):
	connections.append(Connection())

gc.collect()
raw_input(">")
```
Memory usage in windows task manager: 103MB

```
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
>>> msgpack.version
(0, 4, 6)
```
installed binary from msgpack_python‑0.4.6‑cp27‑none‑win32.whl

Thanks!

**Comment by methane** [comment]
It is intended. Unpacker can be reused and it holds buffer to reduce allocation.
You can re-create Unpacker to free memory.
