### ISSUE TITLE
update docs with security features

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#130]
The API docs linked from pypi do not yet reflect all kwarg parameters of unpackb / Unpacker.

As you didn't document the security critical ones, this is dangerous.

Missing:

```
    # avoid memory allocation issues caused by tampered input data.
    max_buffer_size=X,
    max_bin_len=X,
    max_str_len=X,
    max_array_len=X,
    max_map_len=X,
    max_ext_len=X,
```

Also, there is a typo in the max_buffer_size docstring:

```
        You shoud set this parameter when unpacking data from untrasted source.
```

If these parameters are not used and tampered data is unpacked, msgpack might (try to) allocate large amounts of memory, which might end up in DoS or at least unwanted memory allocation.

**Comment by ThomasWaldmann** [comment]
The missing parameters are documented now:

- http://pythonhosted.org/msgpack-python/api.html#msgpack.unpackb
- http://pythonhosted.org/msgpack-python/api.html#msgpack.Unpacker

The typo is still in the docs.

**Comment by ThomasWaldmann** [comment]
Hmm, looks like the typo is gone from release-0.4 branch source, maybe just the docs on rtfd need rebuilding?

**Comment by methane** [comment]
https://msgpack-python.readthedocs.io/en/latest/api.html#msgpack.unpackb
