### ISSUE TITLE
please check types

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#137]
some places in the code look a bit weird to me, could you please double-check them and either fix them or put a comment there if they are correct "as is"?

https://github.com/msgpack/msgpack-python/blob/master/msgpack/unpack.h#L72
cosmetic: as you already checked in the lines before that it is not more than LONG_MAX, I guess you could just use PyInt_FromLong((long) d). See also the code for int64.

https://github.com/msgpack/msgpack-python/blob/master/msgpack/unpack.h#L103
you are casting to (unsigned PY_LONG_LONG) but the value is a (signed) int64_t, so (PY_LONG_LONG) seems more appropriate and this is also what the called function expects there.

I am wondering about compiler warnings due to that? Are there any?

https://github.com/msgpack/msgpack-python/blob/master/msgpack/pack.h#L48
why is that commented/disabled?

**Comment by ThomasWaldmann** [comment]
ping

**Comment by methane** [comment]
Thank you for your precise review.
