### ISSUE TITLE
Tuple dict keys should not be allowed since they serialize to unhashable lists

### ISSUE THREAD

**Issue by rwarren** [msgpack/msgpack-python#138]
Simple demonstration:

    >>> import msgpack
    >>> # Tuples are hashable so are legit dict keys.  Let's encode one...
    >>> encoded = msgpack.dumps({(1, 2): "foo"})
    >>>> # It worked!  What did we get?
    >>> print repr(encoded)
    '\x81\x92\x01\x02\xa3foo'
    >>> # Now decode it...
    >>> msgpack.loads(encoded)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "msgpack/_unpacker.pyx", line 138, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:138)
    TypeError: unhashable type: 'list'
    >>> # This happens because tuples encode as lists...
    >>> msgpack.loads(msgpack.dumps((1, 2)))
    [1, 2]

Could other languages unpack this somehow?  For comparison, json only allows string keys.

I'll loosely cite #98 as related since if tuples unpacked as tuples this would work fine.

**Comment by methane** [comment]
Since msgpack spec only defines wire format, tuple keys and dict keys are allowed.
You can use `use_list=False` option to unpack it. It unpacks msgpack array to Python tuple.

**Comment by theonlygusti** [comment]
@methane 

```
>>> with open(path, 'rb') as infile:
...     print(msgpack.unpackb(infile.read(), use_list=False))
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key```

**Comment by plison** [comment]
I'm getting the same error as above....

**Comment by jfolz** [comment]
The readme actually mentions this. Twice.
https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10
https://github.com/msgpack/msgpack-python#security
