### ISSUE TITLE
package maintainers using broken versions

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#139]
debian jessie was just released with msgpack-python 0.4.2.
ubuntu has a even much older version.

package maintainers need to be made aware of the severe issues in these versions and that they urgently need to upgrade these packages.

this issue is to track progress with that, please add links here to the distribution-specific issues about fixing / upgrading msgpack-python in the distribution.

some issues from the past:
https://github.com/msgpack/msgpack-python/issues/124 (data corruption, affects pure py impl, fix in 0.4.6)
https://github.com/msgpack/msgpack-python/issues/101 (data corruption, affects 32bit, fix in 0.4.3)
https://github.com/msgpack/msgpack-python/issues/97 (DoS,  fix in 0.4.6?)
https://github.com/msgpack/msgpack-python/issues/67 (segfault, fix in 0.4.1)

also notable is that only a recent version enables other developers to limit the unpacker to avoid DoS via memory allocation, the api for that was not present in old msgpack-python versions.

**Comment by ThomasWaldmann** [comment]
ubuntu:
https://bugs.launchpad.net/ubuntu/+source/msgpack-python/+bug/1443213

**Comment by ThomasWaldmann** [comment]
@methane could you please add some compatibility infos for package maintainers upgrading from older versions?

**Comment by methane** [comment]
No backward incompatible changes except bugfix while 0.4.x.

**Comment by ThomasWaldmann** [comment]
From 0.3 to 0.4, the only incompatible changes is:
"""Raises TypeError instead of ValueError when packer receives unsupported type."""

**Comment by danmbox** [comment]
@ThomasWaldmann Ubuntu Vivid uses 0.4.2, but the LTS version (trusty) uses 0.3.0; are there issues with 0.3.0?

**Comment by ThomasWaldmann** [comment]
@danmbox yes, 0.3.0 has issue #101. I updated #101 accordingly, can we delete our comments here to keep this issue clean?

**Comment by methane** [comment]
Ubuntu 16.04 packages msgpack-python 0.4.6.

**Comment by methane** [comment]
Sorry, but I won't do anything about this.
Please report to distributions.
