### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by rggjan** [msgpack/msgpack-python#140]
Same issue as #57, but I somehow didn't find out how to reopen it.

I get the following stacktrace when trying to open one of my files:

```pytb
Traceback (most recent call last):
  File "/home/jan/lucy/scripts/msgpack/browser.py", line 179, in <module>
    win = TreeViewFilterWindow(args)
  File "/home/jan/lucy/scripts/msgpack/browser.py", line 28, in __init__
    self.read_file(args.file)
  File "/home/jan/lucy/scripts/msgpack/browser.py", line 68, in read_file
    data = msgpack.unpackb(f.read(), encoding='utf-8')
  File "msgpack/_unpacker.pyx", line 145, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:145)
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0
```

Using msgpack version 0.4.6 on linux, 64-bit.

The file in question can be found here:
![error](https://cloud.githubusercontent.com/assets/128554/7567756/0b9b6188-f7ff-11e4-9674-3b1e444b33c5.png)

(It is not actually a png but a msgpack file, but This is not allowed to upload)

**Comment by methane** [comment]
Isn't it just a broken data?

**Comment by methane** [comment]
It's not same issue to #57.

**Comment by rggjan** [comment]
Yes, it is broken data. Was #57 not broken data?

Anyway, even for broken data, I would expect to ger something like "error = Array, two more values expected". Because msgpack knows exactly that more data needs to follow, but the file endeded.

**Comment by methane** [comment]
> Yes, it is broken data. Was #57 not broken data?

#57 was exception is not raised properly.

> Anyway, even for broken data, I would expect to ger something like "error = Array, two more values expected". Because msgpack knows exactly that more data needs to follow, but the file endeded.

msgpack is very efficient format. In most cases, unpacker can't distinguish between broken data and incomplete data.
For one-shot API (unpack or unpackb), there are no difference between them. Incomplete data is just a broken data.
If you want to distinguish them, use Unpacker.

**Comment by rggjan** [comment]
Can you give me an example where you can't distinguish? I know msgpack is very efficient, but I think it is always clear if its broken or incomplete from the msgpack specifications: Broken if we get some value that is not cannot belong there, and missing if more values are expected but the file ends.

**Comment by methane** [comment]
```
In [1]: import msgpack

In [2]: data = msgpack.packb([1,2,3])

In [3]: data
Out[3]: b'\x93\x01\x02\x03'

In [4]: data = b'\x97' + data[1:]  # 1bit flip

In [5]: msgpack.unpackb(data)
---------------------------------------------------------------------------
UnpackValueError                          Traceback (most recent call last)
<ipython-input-5-953f5c9c8a36> in <module>()
----> 1 msgpack.unpackb(data)

msgpack/_unpacker.pyx in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:145)()

UnpackValueError: Unpack failed: error = 0
```

**Comment by methane** [comment]
msgpack.unpackb() is one-shot API.  Trimmed data is just a broken data in one-shot API.
You can use Unpacker to distinguish them.

```
In [6]: up = msgpack.Unpacker()
In [7]: up.feed(data)
In [8]: up.unpack()
---------------------------------------------------------------------------
OutOfData                                 Traceback (most recent call last)
<ipython-input-8-2c3a2ec0054c> in <module>()
----> 1 up.unpack()

msgpack/_unpacker.pyx in msgpack._unpacker.Unpacker.unpack (msgpack/_unpacker.cpp:427)()
msgpack/_unpacker.pyx in msgpack._unpacker.Unpacker._unpack (msgpack/_unpacker.cpp:405)()
OutOfData: No more data to unpack.
```

**Comment by rggjan** [comment]
Why couldn't it show:

UnpackValueError: Unpack failed: error = OutOfData: No more data to unpack.

...?

But good to know there is a way to get the actual error, thanks.
