### ISSUE TITLE
Serialization of namedtuples

### ISSUE THREAD

**Issue by ed-rw** [msgpack/msgpack-python#142]
So I saw this referenced in the issue "Allow custom encoding (not character encoding but default function encoding) of unicode strings #73" and was wondering of there's a work around or any plans to implement a fix in the future. 

I'm using version 0.4.6 and as far as I can tell there's no way to define custom serialization of namedtuples (or any object that inherits from native python types msgpack-python supports) with the current implementation. The problem is that any class that inherits from tuple somewhere in their class hierarchy will return True for isinstance(obj, (tuple)), which will not give the user's default callable a chance to run. On solution I see (after a brief code review) is as simple as moving the if block that calls the self._default function from the bottom to right after the `if obj is None:` block.

**Comment by methane** [comment]
ref #100
