### ISSUE TITLE
can not unpack object on python 2.6.6

### ISSUE THREAD

**Issue by liuyangc3** [msgpack/msgpack-python#147]
Hi,

I am debugging a problem when I use zerorpc(base on pyzmq) these days

and here is the issues 
https://github.com/zeromq/pyzmq/issues/719
https://github.com/0rpc/zerorpc-python/issues/125

when I try to unpack a zmq frame object
got a TypeError: 'Frame' does not have the buffer interface

and I found that feed support PyObject_GetBuffer
https://github.com/msgpack/msgpack-python/blob/master/msgpack/_unpacker.pyx#L318
```
def feed(self, object next_bytes):
    PyObject_GetBuffer(next_bytes, &pybuff, PyBUF_SIMPLE)
```
can anyone help, I am not  familiar with Cython
Thanks

**Comment by methane** [comment]
What do you want to do???

**Comment by liuyangc3** [comment]
hi@methane I am trying pass a zmq.frame object to Unpacker().feed(),and got a type error

zmq.frame dose have buffer interface,I am trying
 to find out the reason and need some help 
Thanks for your comment

**Comment by methane** [comment]
I won't fix.
Workaround was committed in zerorpc-python side.
