### ISSUE TITLE
Support json encoders

### ISSUE THREAD

**Issue by jvanasco** [msgpack/msgpack-python#149]
The `json` library (and `simplejson`) have a great feature where you can specify a custom encoding class.  The docs are pretty bad (https://docs.python.org/2/library/json.html#encoders-and-decoders) 

They basically just allow you to write a class, and then serialize using that class:

    class JsonEncoder(json.JSONEncoder):
        """Extends JSONEncoder for date and decimal types."""

        def encode_date(self, d):
            """Serialize the given datetime.date object to a JSON string."""
            # Default is ISO 8601 compatible (standard notation).
            return "%04d-%02d-%02d" % (d.year, d.month, d.day)

        def encode_timedelta(self, t):
            """Serialize the given datetime.timedelta object to a JSON string."""
            days = t.days
            if days < 0:
                minus = "-"
                days = -days - 1
                seconds = (24 * 60 * 60) - t.seconds
            else:
                minus = ""
                seconds = t.seconds
            secs = seconds % 60
            seconds /= 60
            mins = seconds % 60
            hours = seconds // 60  # floored division
            return "%s%d:%02d:%02d:%02d" % (minus, days, hours, mins, secs)

        def encode_time(self, t):
            """Serialize the given datetime.time object to a JSON string."""
            # Default is ISO 8601 compatible (standard notation).
            return "%02d:%02d:%02d" % (t.hour, t.minute, t.second)

        def encode_datetime(self, dt):
            """Serialize the given datetime.datetime object to a JSON string."""
            # Default is ISO 8601 compatible (standard notation).
            # Don't use strftime because that can't handle dates before 1900.
            return ("%04d-%02d-%02dT%02d:%02d:%02d" %
                    (dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second))

        def default(self, o):
            # We MUST check for a datetime.datetime instance before datetime.date.
            # datetime.datetime is a subclass of datetime.date, and therefore
            # instances of it are also instances of datetime.date.
            if isinstance(o, datetime.datetime):
                return self.encode_datetime(o)
            elif isinstance(o, datetime.date):
                return self.encode_date(o)
            elif isinstance(o, datetime.timedelta):
                return self.encode_timedelta(o)
            elif isinstance(o, datetime.time):
                return self.encode_time(o)
            elif isinstance(o, set):
                return list(o)
            elif isinstance(o, decimal.Decimal):
                return str(o)
            else:
                return json.JSONEncoder.default(self, o)

Then you invoke it like such:

    encoded = json.dumps(payload, cls=JsonEncoder)

It would be great if this library also supported this way of serializing data -- it would greatly simplify switching from json to msgpack.

**Comment by methane** [comment]
Using `default` keyword argument can do same thing.
Calling `self.default(o)` has significant overhead.

And Simplejson doesn't recommend using subclassing for now.
See note at http://simplejson.readthedocs.org/en/latest/#simplejson.JSONEncoder.default

**Comment by jvanasco** [comment]
Thanks for the quick reply.  It might be worth putting that on the README under something like "compatibility with json library", because a major usecase of msgpack is replacing json and some people use that other format.

FYI, I have no personal interest in this feature.  I used the default kwarg on my json encoder – I was just concerned with the ease of people switching back and forth.
