### ISSUE TITLE
github releases latest release is 0.4

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#154]
more recent releases are hidden/collapsed and require clicking, then it also shows 0.4.6.

**Comment by methane** [comment]
Uh. I forgot to `push --tags` and I lost local repository when I've released 0.4.x...

**Comment by methane** [comment]
fixed.

**Comment by ThomasWaldmann** [comment]
shameles hint: you know borgbackup? :-)
