### ISSUE TITLE
String serialization not always using smallest representation

### ISSUE THREAD

**Issue by kyleburnett** [msgpack/msgpack-python#162]
According to the [MessagePack spec](https://github.com/msgpack/msgpack/blob/master/spec.md#serialization-type-to-format-conversion):

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

Strings of length 32 to 255 should be encoded using the `str 8` format, but this library encodes them using `str 16`.

Here's the script I was running to test encodings at the various string format thresholds using Python 2.7.6:

```
import msgpack

def output_bytes(l):
    packed = msgpack.packb(l)
    print "Buffer size:", len(packed)
    arr = [p.encode('hex') for p in packed]
    if len(arr) < 10:
        print ' '.join(arr)
    else:
        arr = arr[:10]
        print ' '.join(arr), '...'

############################################################
# Testing string thresholds
############################################################

single = "x"

# Fix strings

data = single * 1
output_bytes(data)
print "Header should be 0xa1"

data = single * 31
output_bytes(data)
print "Header should be 0xbf"

# Str 8

data = single * 32
output_bytes(data)
print "Header should be 0xd9"

data = single * 255
output_bytes(data)
print "Header should be 0xd9"

# Str 16

data = single * 256
output_bytes(data)
print "Header should be 0xda"

data = single * 65535
output_bytes(data)
print "Header should be 0xda"

# Str 32

data = single * 65536
output_bytes(data)
print "Header should be 0xdb"
```

This outputs the following:

```
Buffer size: 2
a1 78
Header should be 0xa1
Buffer size: 32
bf 78 78 78 78 78 78 78 78 78 ...
Header should be 0xbf
Buffer size: 35
da 00 20 78 78 78 78 78 78 78 ...
Header should be 0xd9
Buffer size: 258
da 00 ff 78 78 78 78 78 78 78 ...
Header should be 0xd9
Buffer size: 259
da 01 00 78 78 78 78 78 78 78 ...
Header should be 0xda
Buffer size: 65538
da ff ff 78 78 78 78 78 78 78 ...
Header should be 0xda
Buffer size: 65541
db 00 01 00 00 78 78 78 78 78 ...
Header should be 0xdb
```

**Comment by methane** [comment]
Have you tried `use_bin_type=True` option?

**Comment by kyleburnett** [comment]
Yes. In that case everything is a bin type.

```
Buffer size: 3
c4 01 78
Header should be 0xa1
Buffer size: 33
c4 1f 78 78 78 78 78 78 78 78 ...
Header should be 0xbf
Buffer size: 34
c4 20 78 78 78 78 78 78 78 78 ...
Header should be 0xd9
Buffer size: 257
c4 ff 78 78 78 78 78 78 78 78 ...
Header should be 0xd9
Buffer size: 259
c5 01 00 78 78 78 78 78 78 78 ...
Header should be 0xda
Buffer size: 65538
c5 ff ff 78 78 78 78 78 78 78 ...
Header should be 0xda
Buffer size: 65541
c6 00 01 00 00 78 78 78 78 78 ...
Header should be 0xdb
```

I would like all of my python 'str' types to be encoded using the string format instead of the binary format.

**Comment by methane** [comment]
unicode string is encoded to string format?
Why do you want to use string format for bytes string?

If your intension is data compatibility, that's why I don't use str8 when `use_bin_type=False`.

**Comment by kyleburnett** [comment]
Maybe this will make things clearer.

```
import msgpack

packed = msgpack.packb("The quick brown fox jumps over the lazy dog")
arr = [p.encode('hex') for p in packed]
arr = arr[:10]
print ' '.join(arr), '...'
```

This outputs

```
da 00 2b 54 68 65 20 71 75 69 ...
```

The msgpack-python library is essentially wasting a byte (and not adhering to the specification) by encoding it as a `str 16`. Instead it could be encoded as

```
d9 2b 54 68 65 20 71 75 69 ...
```

We are using `str 8` format here because the length of the string is 43, which is able to be fit into a `str 8`.

**Comment by methane** [comment]
I know it and it's intended behavior.
At first, there are no bin types and str8 type. They were introduced later.
Using bin types and str8 type cause compatibility problem with old decoders.

str8 is used when you use `use_bin_type=True` option and encoding unicode string.

**Comment by methane** [comment]
In other words, if you don't want to distinguish binary data and unicode string, old msgpack spec is
for you and there were no str8 type in it.

If you want to distinguish binary data and unicode string, you should use new spec and you can use
str8 for encoding unicode string.

Mixiing old spec and new spec cause mess.  I won't support such option.

**Comment by kyleburnett** [comment]
I think that clears things up. For those who had the same confusion I had, making the "str" type a unicode string cleared things up.

```
packed = msgpack.packb(unicode("The quick brown fox jumps over the lazy dog"), use_bin_type=True)
arr = [p.encode('hex') for p in packed]
arr = arr[:10]
print ' '.join(arr), '...'
```

This produces `d9 2b 54 68 65 20 71 75 69 ...` as I wanted.

Thanks for your help.
