### ISSUE TITLE
Unpacker ignores a current reading position in a stream

### ISSUE THREAD

**Issue by AleksTk** [msgpack/msgpack-python#167]
msgpack.Unpacker ignores the current reading position in a data stream:
```python
f = BytesIO()
msgpack.pack('a', f)
msgpack.pack('b', f)
f.seek(0)

unpacker = msgpack.Unpacker(f)

print unpacker.unpack()
>>> 'a'

f.seek(0)
print unpacker.unpack()
>>> 'b'  # while 'a' expected
```
This functionality is vital if one needs to read serialized objects at certain locations in a file, when repetitive initialization of Unpacker is unpractical for performance reasons.

**Comment by methane** [comment]
It means Unpacker can't read-ahead.
Many data is packed in 1 byte.  In this case, Unpacker can read only one byte at once.

It kills performance.  I can't accept it.

**Comment by AleksTk** [comment]
Ok, I see. A sane workaround is to enable resetting an internal buffer, so that the next read would start at the current position.
