### ISSUE TITLE
Unknown serialization issue

### ISSUE THREAD

**Issue by lordnynex** [msgpack/msgpack-python#169]
Hello,

I am having serious problems with database connectivity since yesterday. I've traced the issue down to a piece of code that is passing a long integer that has python's 'L' notation appended to it. This appears to be similar to #114. I am struggling a bit because some chained dependency is explicitly requiring the latest msgpack.

**Comment by methane** [comment]
Do you know the msgpack spec? 
 It supports up to 64bit signed or unsigned integer. 
Long integer may be bigger than it. 
Please show me a real example, not only your situation.

**Comment by lordnynex** [comment]
@methane 

A reproduction example is a little bit difficult here. This module is used for message transport for Rexster's RexPro protocol (https://github.com/platinummonkey/rexpro-python). A long time ago, there was an issue that required explicitly casting integer parameters to long ex: `54298955264L`. It is not clear to me what the long notation here does when curried to C. 

As of yesterday's release, it is required that we do not cast integer types to long when passing them to the driver. 

The relevant code is [here](https://github.com/platinummonkey/rexpro-python/blob/master/rexpro/messages.py#L416) and [here](https://github.com/platinummonkey/rexpro-python/blob/master/rexpro/messages.py#L13).  Historically, I'm unsure on why this design decision was made. 

It could very likely be the rexpro driver needs to re-evaluate this int_to_32bit_array function considering the drivers requirements.txt pins a very old version of msgpack. 

Is my example outside of `MAX_LONG`? How does msgpack-pythons use of `MAX_LONG` relate to `sys.maxsize`?

**Comment by methane** [comment]
Since it is enough for most usecases.  And biginteger is hard to move over languages.
For example, Perl and PHP numbers is restricted in C types.

msgpack is JSON like, minimalistic format.  (JSON doesn't have biginteger too).
If you want to serialize rich types and values, you should use pickle.

**Comment by lordnynex** [comment]
I'm not sure how to read your response. The issue is there is a regression in the code that was released yesterday. I've attempted to debug this, but I have to move on to other issues. The integer I supplied fits in within MAX_LONG. 

I'm also not sure what you mean by 'big integer' 

I strongly suspect there is a regression bug in pack() revolving around your additional logic for strict type checking. https://github.com/msgpack/msgpack-python/blob/master/msgpack/_packer.pyx#L153

Here is a test to demonstrate my assertion that my example integer is within an acceptable numeric range. 

`g++ -std=c++11 -o inttest test.cpp -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -lpython2.7`

```cpp
#include <Python.h>
#include <cstdint>
#include <iostream>
#include <typeinfo>

int NumberOfSetBits(int i) {
     i = i - ((i >> 1) & 0x55555555);
     i = (i & 0x33333333) + ((i >> 2) & 0x33333333);
     return (((i + (i >> 4)) & 0x0F0F0F0F) * 0x01010101) >> 24;
}

int main() {
  auto a = 54298955264;

  std::cout << "Type: " << typeid(a).name() << std::endl;

  if(a > LONG_MAX) {
    std::cout << a << " is bigger than LONG_MAX " << LONG_MAX << std::endl;
  } else {
    std::cout << a << " is smaller than LONG_MAX " << LONG_MAX << std::endl;
  }

#if ULLONG_MAX == 0xffffUL
    std::cout << "2 bytes" << std::endl;
#elif ULLONG_MAX == 0xffffffffUL
    std::cout << "4 bytes" << std::endl;
#else
    std::cout << "8+ bytes" << std::endl;
#endif

  int HA = NumberOfSetBits(a);
  std::cout << "Hamming Weight: " << HA << std::endl;

  return 0;
}
```

Here it is in cython

```python
from cpython cimport *
from libc.stdlib cimport *
from libc.string cimport *
from libc.limits cimport *

test = 54298955264L

def test_int():
    if PyLong_Check(test):
        print "Is a long"
```

As far as I can tell, these tests indicate the value being passed to pack() is an integer within an acceptable range. It's 'signed'ness is inconsequential because it appears you are treating it as an unsigned long long if it is a positive integer.  

What the packed buffer actually looks like, I'm not sure. Frankly, the amount of time it would take me to reproduce a pcap demonstrating the output is not justifiable. 

Whether you fix the issue is up to you. For my use case, downgrading to the previous release is acceptable. I strongly suspect I will not be the only person affected by this. 

Considering msgpack is used in many database drivers, I sincerely hope this does not cause data corruption for users.

**Comment by methane** [comment]
I'm sorry.  Since I'm not good at English, I misunderstand often when issue report doesn't have 
reproducible example.
I'll read your report carefully when I have enough time.

**Comment by methane** [comment]
I can't get what is your problem.
Did exception happen when passing long integer to pack()?

**Comment by hougaardj** [comment]
We have had the same issue and i was able to come up with a minimal example that shows the issue

```python
import msgpack


TEST_DATA = [
    1,
    (1 << 4),
    (1 << 8),
    (1 << 15),
    (1 << 16) - 1,
    (1 << 16),
    (1 << 31) - 1,
    (1 << 31),
    (1 << 31) + 1,
    54298955264,
]


for value in TEST_DATA:
    try:
        i = int(value)
        l = long(value)
        packed_i = msgpack.unpackb(msgpack.packb(i))
        packed_l = msgpack.unpackb(msgpack.packb(l))
        print value.bit_length(), i == packed_i, l == packed_l, value, i, l, packed_i, packed_l
    except Exception as e:
        print e
```

With msgpack-python==0.4.6
```python
$ python check_msgpack_static.py 
1 True True 1 1 1 1 1
5 True True 16 16 16 16 16
9 True True 256 256 256 256 256
16 True True 32768 32768 32768 32768 32768
16 True True 65535 65535 65535 65535 65535
17 True True 65536 65536 65536 65536 65536
31 True True 2147483647 2147483647 2147483647 2147483647 2147483647
32 True True 2147483648 2147483648 2147483648 2147483648 2147483648
32 True True 2147483649 2147483649 2147483649 2147483649 2147483649
36 True True 54298955264 54298955264 54298955264 54298955264 54298955264
```

and with msgpack-python=0.4.7
```python
$ python check_msgpack_static.py 
1 True True 1 1 1 1 1
5 True True 16 16 16 16 16
9 True True 256 256 256 256 256
16 True True 32768 32768 32768 32768 32768
16 True True 65535 65535 65535 65535 65535
17 True False 65536 65536 65536 65536 0
31 True False 2147483647 2147483647 2147483647 2147483647 536870911
32 True False 2147483648 2147483648 2147483648 2147483648 0
32 True False 2147483649 2147483649 2147483649 2147483649 1
36 True False 54298955264 54298955264 54298955264 54298955264 305942016
```

The annoying part is this does not affect all machines, ex. on my MacBook there is not issue with 0.4.7, but i found it to be an issue on Ubuntu 12.04.5 LTS, kernel version 3.18.19-031819-generic and gcc 4.6.3.

**Comment by hougaardj** [comment]
```python
>>> import msgpack
>>> msgpack.packb(long((1 << 16) + 1))
'\x01'
>>> msgpack.packb(long((1 << 16) + -1))
'\xcd\xff\xff'
>>> msgpack.packb(long((1 << 16) ))
'\x00'
```
Even simpler

**Comment by hougaardj** [comment]
The python version was 2.7.3. I also tested it on a host running python 2.7.10 and it did not see the issues.

**Comment by methane** [comment]
@hougaardj Thanks for your clear report.
Is your Linux machine is x86 (32bit) or amd64 (64bit) ?

**Comment by hougaardj** [comment]
Boxes are amd64.

The output is a bit different when installing the packages on the hosts, ex:

Host5 with python 2.7.10:
```
$ virtualenv env
New python executable in env/bin/python
Installing distribute...........................................................................................................................................................................................................................done.
Installing pip................done.
$ . env/bin/activate
$ pip install msgpack-python
Downloading/unpacking msgpack-python
  Real name of requirement msgpack-python is msgpack_python
Creating supposed download cache at /home/<home_dir>/.pip/cache
  Downloading msgpack-python-0.4.7.tar.gz (126kB): 126kB downloaded
  Storing download in cache at ./.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fm%2Fmsgpack-python%2Fmsgpack-python-0.4.7.tar.gz
  Running setup.py egg_info for package msgpack-python
    
Installing collected packages: msgpack-python
  Running setup.py install for msgpack-python
    building 'msgpack._packer' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python2.7 -c msgpack/_packer.cpp -o build/temp.linux-x86_64-2.7/msgpack/_packer.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security build/temp.linux-x86_64-2.7/msgpack/_packer.o -o build/lib.linux-x86_64-2.7/msgpack/_packer.so
    building 'msgpack._unpacker' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python2.7 -c msgpack/_unpacker.cpp -o build/temp.linux-x86_64-2.7/msgpack/_unpacker.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
    In file included from msgpack/_unpacker.cpp:253:0:
    msgpack/unpack.h: In function ‘int unpack_callback_ext(unpack_user*, const char*, const char*, unsigned int, PyObject**)’:
    msgpack/unpack.h:268:77: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security build/temp.linux-x86_64-2.7/msgpack/_unpacker.o -o build/lib.linux-x86_64-2.7/msgpack/_unpacker.so
    
Successfully installed msgpack-python
Cleaning up...
$ python
Python 2.7.10 (default, Aug  7 2015, 18:34:52) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import msgpack
>>> msgpack.packb(long(1 << 16))
'\xce\x00\x01\x00\x00'
```

Host6 with python 2.7.3:
```
$ virtualenv env
New python executable in env/bin/python
Installing distribute...........................................................................................................................................................................................................................done.
Installing pip................done.
$ . env/bin/activate
$ pip install msgpack-python
Downloading/unpacking msgpack-python
  Real name of requirement msgpack-python is msgpack_python
  Using download cache from /home/<home_dir>/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fm%2Fmsgpack-python%2Fmsgpack-python-0.4.7.tar.gz
  Running setup.py egg_info for package msgpack-python
    
Installing collected packages: msgpack-python
  Running setup.py install for msgpack-python
    building 'msgpack._packer' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python2.7 -c msgpack/_packer.cpp -o build/temp.linux-x86_64-2.7/msgpack/_packer.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
    g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/msgpack/_packer.o -o build/lib.linux-x86_64-2.7/msgpack/_packer.so
    building 'msgpack._unpacker' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python2.7 -c msgpack/_unpacker.cpp -o build/temp.linux-x86_64-2.7/msgpack/_unpacker.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
    In file included from msgpack/_unpacker.cpp:253:0:
    msgpack/unpack.h: In function ‘int unpack_callback_ext(unpack_user*, const char*, const char*, unsigned int, PyObject**)’:
    msgpack/unpack.h:268:77: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/msgpack/_unpacker.o -o build/lib.linux-x86_64-2.7/msgpack/_unpacker.so
    
Successfully installed msgpack-python
Cleaning up...
$ python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import msgpack
>>> msgpack.packb(long(1 << 16))
'\x00'
```

**Comment by methane** [comment]
Thanks for detailed information.

BTW, I don't recommend to use Linux distribution's old Python.
Most libraries and apps only be tested newest version of Python 2.7.x.
Debian and Ubuntu tests their package (older than PyPI) with old Python (like 2.7.3).

Thouthands bugs (including security issues) are fixed between 2.7.3 and 2.7.11.
I strongly recommend you to don't use system Python to run your application.
System Python is for running applications installed by system package manager.

**Comment by methane** [comment]
I can't reproduce it with Python 2.7.3 on Ubuntu wily (gcc-5.2).
So it may be caused by gcc version.

**Comment by monitorius** [comment]
I can confirm this problem with ```long``` type. My db-related code has suddenly become broken, because ids of objects returned from db are of ```long``` type.
```
monitorius /tmp$ cat temp.py
import msgpack

d = 90000000
print(msgpack.loads(msgpack.dumps(d)))

d = 90000000L
print(msgpack.loads(msgpack.dumps(d)))

monitorius /tmp$ pip list|grep msgpack
msgpack-python (0.4.7)

monitorius /tmp$ python temp.py
90000000
19072

monitorius /tmp$ pip install -U msgpack-python==0.4.6
monitorius /tmp$ pip list|grep msgpack
msgpack-python (0.4.6)

monitorius /tmp$ python temp.py
90000000
90000000

monitorius /tmp$ python --version
Python 2.7.3

monitorius /tmp$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise

monitorius /tmp$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

monitorius /tmp$ uname -smr
Linux 3.18.19-24 x86_64
```

**Comment by methane** [comment]
I feel Ubuntu 12.04 is broken...

```
(system) inada-n@oldbench:~$ cat longbits.c 
#include <Python.h>
#include <longintrepr.h>

int main() {
        printf("digit bits = %d\n", PYLONG_BITS_IN_DIGIT);
        printf("sizeof(digit) = %lu\n", sizeof(digit));
}
(system) inada-n@oldbench:~$ gcc longbits.c -I /usr/include/python2.7/
(system) inada-n@oldbench:~$ ./a.out 
digit bits = 30
sizeof(digit) = 4
(system) inada-n@oldbench:~$ g++ longbits.c -I /usr/include/python2.7/
(system) inada-n@oldbench:~$ ./a.out 
digit bits = 15
sizeof(digit) = 2
```

**Comment by methane** [comment]
Ubuntu 12.04's Python doesn't contain this bugfix landed in 2012.
https://github.com/python/cpython/commit/050ba5ec1e941e05607ef29049bde08798387bcc

system Python is too old and buggy.  It's only for running applications installed by apt or yum.
You should use new Python when you want to install packages from PyPI.

**Comment by methane** [comment]
workaround is apply the patch to `/usr/include/python2.7/pyport.h` manually.
Could someone using system Python on Ubuntu 12.04 report this issue to Ubuntu?

**Comment by monitorius** [comment]
Thank you! I can add that on another machine with same Ubuntu release and Python 2.7.3, but with newer kernel (Linux 3.2.0-68-virtual x86_64) msgpack 0.4.7 works fine. I'm not sure if there are some other differences between machines except kernel.

**Comment by methane** [comment]
kernel version doesn't affect to it.
Combination of gcc version and old Python cause this.

**Comment by monitorius** [comment]
Well, msgpack is installed as binary from pip, right? I don't see any compilation messages during install and don't even have gcc or python-dev on the last machine. If the architecture and os versions are the same, then why on one machine there is a problem with long?

**Comment by methane** [comment]
I provide binary package only for Windows.
You should check your pip log carefully.
2016/02/17 午後3:13 "monitorius" <notifications@github.com>:

**Comment by methane** [comment]
I released manylinux1 wheel.  You can install it with pip >= 8.1.
