### ISSUE TITLE
Windows 7, Python 3.4.4, version 0.4.7 - Runtime termination unusual way

### ISSUE THREAD

**Issue by corylutton** [msgpack/msgpack-python#174]
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
shell returned 3

This message happens during shutdown or ending of a script.

It does not cause an error on 0.4.6, I can downgrade and the message goes away, not sure what I can do to give you better test info.  Let me know.

Thanks
Cory Lutton

Update: this may be due to building with MinGw, and I just noticed you recommend using VS 2015 in documentation.  If this is the likely reason then I can just stick with 0.4.6

**Comment by methane** [comment]
I don't support MinGW because I don't use it.

**Comment by corylutton** [comment]
Fair enough, I only use it when I am developing on a windows laptop as I sometimes like to build simple extensions..... perhaps I will try VS 2015 or just delete the pyd files and use the fallback when developing.  Thanks.

**Comment by methane** [comment]
While I dont know anything about mingw, I believe mingw have some community
you can consult in there.
2016/02/17 午後1:41 "Cory Lutton" <notifications@github.com>:
