### ISSUE TITLE
Ext data too large; 2**32-1

### ISSUE THREAD

**Issue by kawochen** [msgpack/msgpack-python#181]
In this [line ](https://github.com/msgpack/msgpack-python/blob/master/msgpack/_packer.pyx#L227-L228), should the max length be `(size_t) -1` instead?

**Comment by methane** [comment]
See https://github.com/msgpack/msgpack/blob/master/spec.md#formats-ext

Msgpack is suitable for small~medium data fits in memory.
When treating large data, "sequence of small message" is better than "one message has large array".

**Comment by kawochen** [comment]
Thanks!
