### ISSUE TITLE
Possible security issue / intrusion to PyPI packages

### ISSUE THREAD

**Issue by oberstet** [msgpack/msgpack-python#183]
Hi,

our CI builds have started to fail very recently: https://travis-ci.org/crossbario/crossbar/builds/126621443

The reason is that the hashes of the published wheels on PyPI for `msgpack-python` have changed. The hash of the source dist has NOT changed though.

As can be seen from the upload dates too:

```
File 	Type 	Py Version 	Uploaded on 	Size
msgpack-python-0.4.7.tar.gz (md5) 	Source 		2016-01-24 	123KB
msgpack_python-0.4.7-cp27-cp27m-manylinux1_i686.whl (md5) 	Python Wheel 	cp27 	2016-04-27 	235KB
msgpack_python-0.4.7-cp27-cp27m-manylinux1_x86_64.whl (md5) 	Python Wheel 	cp27 	2016-04-27 	239KB
msgpack_python-0.4.7-cp27-cp27mu-manylinux1_i686.whl (md5) 	Python Wheel 	cp27 	2016-04-27 	235KB
msgpack_python-0.4.7-cp27-cp27mu-manylinux1_x86_64.whl (md5) 	Python Wheel 	cp27 	2016-04-27 	240KB
msgpack_python-0.4.7-cp34-cp34m-manylinux1_i686.whl (md5) 	Python Wheel 	cp34 	2016-04-27 	255KB
msgpack_python-0.4.7-cp34-cp34m-manylinux1_x86_64.whl (md5) 	Python Wheel 	cp34 	2016-04-27 	263KB
msgpack_python-0.4.7-cp35-cp35m-manylinux1_i686.whl (md5) 	Python Wheel 	cp35 	2016-04-27 	250KB
msgpack_python-0.4.7-cp35-cp35m-manylinux1_x86_64.whl (md5) 	Python Wheel 	cp35 	2016-04-27 	260KB
```

Note that the reason that our py33 build in Travis did not fail is: you don't publish wheels for cpy33, hence it uses the source dist, and the hash for that is unchanged.

If it wasn't you that forced an upload, you might have an intrusion to your PyPI account. If you did the republish of already published packages - this would be bad also (please don't do that).

**Comment by oberstet** [comment]
Ah, could it be, that originally (in january) you did only publish the source dist, but now (04/27) you additionally published wheels?

because this is what we use: https://github.com/crossbario/crossbar/blob/master/requirements.txt#L117

**Comment by oberstet** [comment]
if so, this is less bad, but also has broken our builds ..

**Comment by methane** [comment]
Releasing binary wheels later is very common situation.  There are very vary reasons about packagers can't release wheels soon.

So it's a just cons of using hash.  If you chose to use hash, you chose false negative broken build too.
