### ISSUE TITLE
str16 (not str8) for 32 bytes?

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#200]
is it intended / known that the serialization of a bytes object with length 32 is a str16?

**Comment by ThomasWaldmann** [comment]
We found it: str8 is a relatively recent msgpack addition.

**Comment by methane** [comment]
Yes.  `use_bin_type=True` is required to use str8, too.
See #191 too.  I proposed to changing from `use_bin_type` to `compat_mode`.
