### ISSUE TITLE
Unpack partial data/object attribute

### ISSUE THREAD

**Issue by pryg-skok** [msgpack/msgpack-python#204]
Hi, my question is about additional pack/unpack control.

1) Is there any way to unpack single element of array if one of the field of this object equals to desired? Suppose we have an array of Persons which has fields: Name, Phone, Date.
```
Person = {"Name": "Peter", "Phone": "+79267845392", "Date": 1469965100.869669}
```
Can I skip unpacking of other Persons if their `Name != "Peter"`?

2) Related to previous: does msgpack unpacks whole structure if I want to unpack only single field? Also is there any way to read map keys? I see there is `read_map_header` but it returns only keys count, but it seems it's good for parallelizing unpacking task.

What can you suggest? Is there possible?

**Comment by methane** [comment]
I don't remember enough to answer correctly.
And I don't have time to check it for you.  You can take time to read APIs carefully for you.

Basically speaking, msgpack (and JSON) is not format for such a requirement.
AFAIK, Flatbuffer is for you.

**Comment by pryg-skok** [comment]
So what is your answer? You have no time to answer and you just close this issue without correct answer.... good point!

Of course, I read api, but maybe I missing something - that's why I'm asking. Also I have no idea why do you say that such formats are not for this requirement: it's not about format, it's about how data handled inside your code.
MsgPack format contains length of each field with every field, so it is possible to split packed binary string into chunks, without unpacking and provide interface to navigate through structures without unpacking them.
So my question about this: whether or not python implementation support this?

**Comment by methane** [comment]
> So what is your answer? You have no time to answer and you just close this issue without correct answer.... good point!

See here: https://news.ycombinator.com/item?id=8712333

Using issue tracker as free tech support from core developer cause burn out easily,
especially for project maintained by one person which maintains some projects.
That's why I don't want to take time to reply questions on issue tracker.

When you have question, users can help each other in ML or stackoverflow,
without applying loads to developer.

Your first issue doesn't include even very basic background: What is your point? Speed or memory?
After discussion on ML or stackoverflow, you could write more useful issue.

**Comment by methane** [comment]
> MsgPack format contains length of each field with every field,

msgpack format have "number of items", but not "number of bytes".
So msgpack format must scanned.  Skipping list or dict without parsing is impossible.

**Comment by methane** [comment]
>  so it is possible to split packed binary string into chunks, without unpacking and provide interface to navigate through structures without unpacking them.

I don't understand what "navigate through structures without unpacking them." actually means.

> So my question about this: whether or not python implementation support this?

So the answer is: It may, or may not.

Again, I don't want to use issue tracker as free tech support.
I'm bad at reading and writing English.  Reading and writing Python (or even C!) is far easier than English.
Thinking about "what is the point of the issue?" robs my energy and time.

**Comment by methane** [comment]
> Of course, I read api, but maybe I missing something

Maybe, `Unpacker.read()` is.  But I'm not sure it's enough for you or not.

**Comment by pryg-skok** [comment]
> When you have question, users can help each other in ML or stackoverflow,
without applying loads to developer.
> Again, I don't want to use issue tracker as free tech support.

Yes, I understand, but when you have no time - you can just not answer. That's it. Also many maintainers are glad to discuss their code and possible features. I'm not sure there is something to discuss on stackoverflow: it's just feature, your code can support it or not. 

> Your first issue doesn't include even very basic background: What is your point? Speed or memory? After discussion on ML or stackoverflow, you could write more useful issue.
> Thinking about "what is the point of the issue?" robs my energy and time.

This is about speed and possible memory, too. Sometimes not every array element or not every field of struct is need - you can just pick up only what you need without unpacking everything. It's gives great speed gain and also can save your memory. When it's partially unpacked it can be packed partially too. I thought it's quite clear. Also you've noticed me about flatbuffers - they implement such behavior (but not in python), so I really thought that my issue was clear.

> msgpack format have "number of items", but not "number of bytes". So msgpack format must scanned. Skipping list or dict without parsing is impossible.
> I don't understand what "navigate through structures without unpacking them." actually means

It means that you are not unpack every value of your map, just unpack names (keys) of that values, and actually unpacking values performs only when it's necessary. Suppose, you have large dict of dicts and arrays, and from that structure on some part of code you need only one single field somewhere in the deep. Here is speed up -- you're not unpacking whole big structure to return this single value. You can access it, because you have names of fields, but you do not need to unpack it before you need it -- that's what I mean when I said "navigate".

**Comment by asvetlov** [comment]
@methane I suggest to stop the discussion.
I understand your point and appreciate your solution.

Unfortunately I have very similar  problem at https://github.com/KeepSafe/aiohttp/issues/1030

So my suggestion is just STOP.

If @pryg-skok doesn't understand the difference between msgpack and flatbuffers -- just take him a troll.
Period.

**Comment by pryg-skok** [comment]
@asvetlov, my last message was only about answering questions: @methane already explain, the debate is over. And also I understand the difference between these serializers, and maybe I really can not well describe the idea. Sorry, I didn't want to be a troll.

**Comment by methane** [comment]
> Yes, I understand, but when you have no time - you can just not answer. That's it.

I checks open issues of some repository repeatedly, to avoid I forget to solve important bugs.
That's why "discuss on issue tracker" robs my energy and time.

> it's just feature, your code can support it or not.

I can't remember whole API of all projects I maintain or contribute.
To answer such question correctly, I must read code carefully.

If the question was posted on stackoverflow or msgpack ML, other users can reply.
Posting good question, and reply to it is very important contribution.
It makes good "community".


> This is about speed and possible memory, too. Sometimes not every array element or not every field of struct is need - you can just pick up only what you need without unpacking everything. It's gives great speed gain and also can save your memory.

If you think so, you can fork and benchmark it.
But I bet it slow down much, because it needs many Python function call while unpacking.

```
a = msgpack.unpackb(buf)[100]  # one Python call
```

```
unpacker.read_array_header()  # 1 call
for _ in range(99):  # 1 call
    unpacker.skip()  # 99 calls
a = unpacker.unpack() # 1 call -- 102 total
```

Even if it improve some efficiency, it should be compared with code simplicity.
json in Python's standard library doesn't have such API.  And some third party json libraries may
support it.
This project aims standard.  You can create fork or new library which has additional APIs
required by very few people.
