### ISSUE TITLE
msgpack encoding/decoding issues - always `latin1`

### ISSUE THREAD

**Issue by loisaidasam** [msgpack/msgpack-python#205]
I'm using [msgpack](http://msgpack.org/index.html) (`msgpack-python==0.4.8`) on `Python 2.7.11` and experiencing unexpected encoding/decoding issues.

It seems that msgpack always encodes to `latin1`-flavored strings:

    In [1]: import msgpack
    
    In [2]: msgpack.packb({u'foo': u'bar'}, encoding='utf-8')
    Out[2]: '\x81\xa3foo\xa3bar'
    
    In [3]: msgpack.packb({u'foo': u'bar'}, encoding='utf-8').decode('utf-8')
    ---------------------------------------------------------------------------
    UnicodeDecodeError                        Traceback (most recent call last)
    <ipython-input-3-92e0442a408e> in <module>()
    ----> 1 msgpack.packb({u'foo': u'bar'}, encoding='utf-8').decode('utf-8')
    
    /Users/sam/.virtualenvs/project/lib/python2.7/encodings/utf_8.pyc in decode(input, errors)
         14 
         15 def decode(input, errors='strict'):
    ---> 16     return codecs.utf_8_decode(input, errors, True)
         17 
         18 class IncrementalEncoder(codecs.IncrementalEncoder):
    
    UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte
    
    In [4]: msgpack.packb({u'foo': u'bar'}, encoding='utf-8').decode('ascii')
    ---------------------------------------------------------------------------
    UnicodeDecodeError                        Traceback (most recent call last)
    <ipython-input-5-175e354da2c9> in <module>()
    ----> 1 msgpack.packb({u'foo': u'bar'}, encoding='utf-8').decode('ascii')
    
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x81 in position 0: ordinal not in range(128)
    
    In [5]: msgpack.packb({u'foo': u'bar'}, encoding='utf-8').decode('latin1')
    Out[5]: u'\x81\xa3foo\xa3bar'

Any ideas why not `utf-8` like I specified in my encoding?

Even if I don't specify an encoding explicitly, it chooses the same string:

    In [7]: msgpack.packb({u'foo': u'bar'})
    Out[7]: '\x81\xa3foo\xa3bar'

What gives?

**Comment by methane** [comment]
See here
https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde
