### ISSUE TITLE
0.4.8  pack large long type  overflow on ubuntu-12.04

### ISSUE THREAD

**Issue by monsterxx03** [msgpack/msgpack-python#209]
Platform:   ubuntu-12.04 (python2.7.3),  msgpack version: 0.4.8

    >>> msgpack.packb(72057594051091511L)
    '\xce\x00d\xdc7'       # unpack to 6609975
    >>> msgpack.packb(72057594051091511)
    '\xcf\x01\x00\x00\x00\x00\xc8\xdc7'   # right one
    >>> uname -a
    Linux  testVM 3.2.0-25-virtual #40-Ubuntu SMP Wed May 23 22:20:17 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

I also tried 0.4.6 and 0.4.7 on 12.04, the result is right.

Tried 0.4.8 on ubuntu16.04 (python 2.7.12) , the pack result is right

    >>> uname -a
    Linux devVM 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by methane** [comment]
See #169
