### ISSUE TITLE
Track current stream offset?

### ISSUE THREAD

**Issue by enkore** [msgpack/msgpack-python#211]
In some applications, namely indexing of msgpack streams, it would be very useful to tell the total offset (not the buffer offset) of the last object returned by the Unpacker iterator. In code:

```py
for packet in data:
    unpacker = Unpacker(...)
    unpacker.feed(data)
    for object in unpacker:
        print(unpacker.offset)
```

Would print for example 0, 1234, 4567, and so on.

**Comment by jfolz** [comment]
This is addressed by #227.
