### ISSUE TITLE
outdated stuff

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#216]
- latest tag is 0.4.8
- pypi also has 0.4.8
- latest github release is 0.4.6
- README.rst (thus also: github homepage) says 0.4.6 (2015-03-13)
- http://pythonhosted.org/msgpack-python/ says "0.4" (and is (c) 2013)

Note: if you want to do the versioning (at least for the python-based stuff) a bit less manually, you could use setuptools-scm (we use that for borgbackup, it's nice).

**Comment by methane** [comment]
Thank you for pointing it out.

> latest github release is 0.4.6

I don't want to maintain github release.

> README.rst (thus also: github homepage) says 0.4.6 (2015-03-13)

I removed version from README

> http://pythonhosted.org/msgpack-python/ says "0.4" (and is (c) 2013)

Moved to Read the Docs.

**Comment by ThomasWaldmann** [comment]
The docs still say 0.4 and 2013.
