### ISSUE TITLE
Incremental object unpacking

### ISSUE THREAD

**Issue by dlecocq** [msgpack/msgpack-python#218]
We'd like to use this library when talking to a subprocess over a pipe, but we're having some problems with getting objects out of `Unpacker`.

We've got a python process A that launches B and talks to it over a pipe. A issues requests to B, which it fulfills and writes back. But the stream of requests handed to A depends on being able to get back results from B as they're ready. Despite having the proper `flush`es in place in the producers (for writing A->B and for writing B->A), we can't get this to work.

I plan to dig in more closely, but it seems this functionality should be independent of the `max_buffer_size`, but perhaps I've misunderstood something. It seems like we should be able to detect when a whole object has been read, and yield it.

Here's a small example that demonstrates our issue. When using the `Jsonpacker`, we get the expected behavior (we get some of the "Read" messages printed interleaved with the "Writing" messages). But when using `Msgpacker`, all the "Read" messages appear only after all the "Writing" messages do:

```python
#! /usr/bin/env python

import contextlib
import functools
import json
import os
import threading

import msgpack

class Msgpacker(object):
    @staticmethod
    def packer(stream, items):
        '''Write some items to the stream.'''
        for item in items:
            print 'Writing item %s' % item
            stream.write(msgpack.packb(item, use_bin_type=True))
            stream.flush()

    @staticmethod
    def unpacker(stream):
        '''Yield the items read from a stream.'''
        return msgpack.Unpacker(fin, encoding='utf-8')


class Jsonpacker(object):
    @staticmethod
    def packer(stream, items):
        '''Write some items to the stream.'''
        for item in items:
            print 'Writing item %s' % item
            json.dump(item, stream)
            stream.write('\n')
            stream.flush()

    @staticmethod
    def unpacker(stream):
        '''Yield the items read from a stream.'''
        line = stream.readline()
        while line:
            yield line
            line = stream.readline()


@contextlib.contextmanager
def launch(func, *args, **kwargs):
    '''Ensures a thread is always joined.'''
    thread = threading.Thread(target=functools.partial(func, *args, **kwargs))
    try:
        print 'Launching %s(*%s, **%s)' % (func, args, kwargs)
        thread.start()
        yield
    finally:
        thread.join()

def pipe():
    '''Make a pipe and yield file-like objects.'''
    read_fd, write_fd = os.pipe()
    return os.fdopen(read_fd, 'r'), os.fdopen(write_fd, 'w')


def writer(klass, stream, items):
    '''Write some items to the stream.'''
    with contextlib.closing(stream):
        klass.packer(stream, items)

def reader(klass, stream):
    '''Read some items from the stream.'''
    with contextlib.closing(stream):
        for item in klass.unpacker(stream):
            print 'Read item %s' % item


# Can set this to be Msgpacker or Jsonpacker
klass = Jsonpacker
fin, fout = pipe()
with launch(writer, klass, fout, xrange(100)):
    with launch(reader, klass, fin):
        pass
```

Just to reiterate, I hope to find a moment to dig into this, but thought I'd post it in case someone happens to know what the issue is off hand :-)

**Comment by methane** [comment]
Have you read example code in docstring?
http://msgpack-python.readthedocs.io/en/latest/api.html#msgpack.Unpacker

**Comment by jfolz** [comment]
You probably want to replace `fin` with `stream` up there and `fdopen` in binary mode. Doing that (and fixing the prints) it runs fine in Python 3.5.
In any case the proper place to ask stuff like this is stackoverflow.

**Comment by dlecocq** [comment]
Changing the interface to use the `feed` API has no effect (nor would I expect it to, really).

Binary mode in `fdopen` also has no effect. The reason for opening an issue here rather than pursuing it on SO was that I was initially concerned there might be bug. With the `print` statements adjusted, it still does not provide the desired behavior on python 3.5.1 on Mac.

Turns out the issue is not any issue in `msgpack-python`, but a detail of the buffering of the underlying PIPE.
