### ISSUE TITLE
pypi source distribution version

### ISSUE THREAD

**Issue by pohmelie** [msgpack/msgpack-python#220]
It looks like source distribution of msgpack-python on pypi (`msgpack-python-0.4.8.tar.gz`) is not in sync with last github release, since pypi version have no `strict_types` argument.

**Comment by methane** [comment]
What "github release"?
If you mean master branch, they are sync only when from right after release to first commit after that.
Out of sync is not a bug.

If you mean Github's "releases" tab, I don't use it.

**Comment by pohmelie** [comment]
I mean #158 was merged with master 25 jan 2016 and current pypi release is 2016-07-29. So why there is no `strict_types` in pypi version?

**Comment by methane** [comment]
Because master is under development, and PyPI release is from maintenance branch (release-0.4).

**Comment by pohmelie** [comment]
Oh, I see, thanks.
