### ISSUE TITLE
tag version 0.4.9?

### ISSUE THREAD

**Issue by williballenthin** [msgpack/msgpack-python#222]
Would you please consider tagging version 0.4.9 and releasing to Pypi?

I have an application that uses msgpack-python on memoryviews. Support for this setup in fallback mode has only been added since tag 0.4.8, so its a little tricker to get things installed nicely. Pushing a bugfix release that includes the 58 commits since 0.4.8 would really help me out. However, if there are changes that you feel haven't been sufficiently tested so that pushing 0.4.9 is a bad idea, then I totally understand.

**Comment by methane** [comment]
see https://github.com/msgpack/msgpack-python/commits/release-0.4

There are no new commit for 0.4.x for now.

**Comment by williballenthin** [comment]
Ah, ok, I was looking at the master branch. My fault. Will the memoryview support for fallback mode make it into the 0.4.x branch?

I had been looking at: https://github.com/msgpack/msgpack-python/releases/tag/0.4.8
While the tag date was July 29, 2016, there have been a bunch of commits (57) to master since then. Is the master branch the staging ground that's used before features are merged into the 0.4.x branch?

**Comment by methane** [comment]
master branch contains new feature and deprecations for 0.5 release.

**Comment by williballenthin** [comment]
ah, ok, that makes sense. thanks!
