### ISSUE TITLE
can't serialize bytearray

### ISSUE THREAD

**Issue by dineshbvadhia** [msgpack/msgpack-python#224]
If value = bytearray(b'\x01\x87h\x05')

then packb(value, use_bin_type=True)

returns the error: can't serialize bytearray(b'\x01\x87h\x05')

Is this a known problem?

**Comment by methane** [comment]
Yes.
You can convert it by `bytes(value)`.
If you're worrying about memory copy, `memoryview(value)` can be used too.

**Comment by dineshbvadhia** [comment]
Ok. Will the problem be fixed in the future?

Concern is performance with additional step when there are lots of value's.

**Comment by methane** [comment]
I don't know.  I'll consider about it when I feel like it.

**Comment by methane** [comment]
I always very careful when adding new feature.

**Comment by jfolz** [comment]
Out of interest I made this: https://gist.github.com/jfolz/321d250771b21112e8f36e5970e7e9e3
It compares packing plain bytes to bytearray+conversion to memoryview on-the-fly, and a static memoryview of the array.

```
1 bytes
bytes:      4.5108795166e-07
bytearray:  239.217758985 %
memoryview: 117.706131078 %
-----------------------------
10 bytes
bytes:      3.80992889404e-07
bytearray:  238.548185232 %
memoryview: 126.533166458 %
-----------------------------
100 bytes
bytes:      3.77893447876e-07
bytearray:  235.520504732 %
memoryview: 126.750788644 %
-----------------------------
1000 bytes
bytes:      4.39882278442e-07
bytearray:  219.349593496 %
memoryview: 123.902439024 %
-----------------------------
10000 bytes
bytes:      9.32931900024e-07
bytearray:  162.714030156 %
memoryview: 114.05571173 %
-----------------------------
100000 bytes
bytes:      6.7458152771e-06
bytearray:  108.927687849 %
memoryview: 100.759878419 %
-----------------------------
1000000 bytes
bytes:      0.00047575712204
bytearray:  101.169899823 %
memoryview: 101.225425589 %
-----------------------------
```

For tiny amounts of data, the additional function call and object creation do have significant impact. If you modify and packing the same `bytearray` over and over, you can just keep a `memoryview` of it and pack that instead.

**Comment by methane** [comment]
Now I changed my thought about memoryview.  I don't recommend memoryview because it has very critical pitfall.
Python is readability-first language.  I recommend to stop thinking about zero-copy (or less-copy).

In this case, bytearray is the most important and builtin "bytes-like" type.  I agree it should be supported directly.

**Comment by pitrou** [comment]
@methane, do you plan to make a new release soon? I will need bytearray support :-)
