### ISSUE TITLE
Unpacker with 'with' statement

### ISSUE THREAD

**Issue by dineshbvadhia** [msgpack/msgpack-python#225]
Unpack a file with:

```
unpacker = Unpacker(file_like)
for o in unpacker:
    process(o)
```
which works, but doesn't work with 'with' statement:

```
with Unpacker(file_like) as unpacker:
    for o in unpacker:
        process(o)
```

Error is: __exit__

**Comment by methane** [comment]
Why do you think Unpacker support `with` statement???

**Comment by dineshbvadhia** [comment]
The new practice with Python is to open files with the "with" statement primarily because it automatically closes the file after completion. Hence, the question.

**Comment by methane** [comment]
It's nonsense because:

* Unpacker doesn't open file, file_like is opened already
* Unpacker doesn't know what file_like is

You should:

```
with open(path) as f:
    unpacker = Unpacker(f)
        for o in unpacker:
            process(o)
```
