### ISSUE TITLE
When will master be repackaged?

### ISSUE THREAD

**Issue by JBKahn** [msgpack/msgpack-python#226]
I'm really looking forward to `strict_types` and am using the python fallback encoder and cpython decoder to accomplish that right now. Do you know if you'll be releasing again anytime soon?

**Comment by methane** [comment]
Thank you for testing master branch.
No schedule, but not anytime soon.

**Comment by JBKahn** [comment]
@methane I'm not actually using master right now. Do you think it's stable enough to use? I was wondering if there was a reason you aren't releasing it that would make me not want to use it.

**Comment by methane** [comment]
Yes.  I think current master is stable enough as normal 0.X.0 release.

Since next minor release is big step toward 1.0, I have to add many warnings where
APIs I want to remove in 1.0, or options I want to change default value.
