### ISSUE TITLE
pip3 install mspack-python error

### ISSUE THREAD

**Issue by Qiu-Kejian** [msgpack/msgpack-python#230]
OS: windows 10 64bit
Language: Chinese
Running setup.py install for msgpack-python ... error
![image](https://user-images.githubusercontent.com/16420190/27082841-eb91751a-5078-11e7-901b-23ae7793bf8b.png)
![image](https://user-images.githubusercontent.com/16420190/27082870-089b51bc-5079-11e7-8339-14b5c20d7511.png)

**Comment by methane** [comment]
Why do you think it's msgpack issue?
It seems pip issue.  You may use toooo old pip.
