### ISSUE TITLE
Incorrect Serialization for Python long types

### ISSUE THREAD

**Issue by ankitpatel96** [msgpack/msgpack-python#231]
Hey, I found some pretty bizarre behavior with serializing longs
Reproduction:
Python 2.7.3
Msgpack-python v0.4.8 (pure python version)
```python
q = 0xffff+1
v = long(0xffff+1)

encoded = msgpack.packb(q) 
decoded = msgpack.unpackb(encoded)
self.assertEqual(q, decoded) # works fine 

encoded = msgpack.packb(v) 
decoded = msgpack.unpackb(encoded)
self.assertEqual(v, decoded) #throws assert error
AssertionError: 65536L != 0
```
Note that this choice of 0xffff+1 is a deliberate choice - if you set both numbers to 0xffff it works fine.
You can also trigger this with pretty much any number above 0xffff casted or created as a long as far as i can tell.  One last clue that might help with debugging:
```python
v = long(0xffff+2)
encoded = msgpack.packb(v) 
decoded = msgpack.unpackb(encoded)
self.assertEqual(v, decoded) #throws assert error
AssertionError: 65537L != 1
```

**Comment by jfolz** [comment]
Probalby #169 again.
