### ISSUE TITLE
Unpacking using 'unpackb()' is slow when passing parameter "encoding='utf-8'"

### ISSUE THREAD

**Issue by Code-ReaQtor** [msgpack/msgpack-python#243]
Hi,

I was looking for JSON alternative and since I have experience working with msgpack (in C/C++) I thought I'll give this library a try.

This [feature](https://github.com/msgpack/msgpack-python#string-and-binary-type) is very handy.
However, this is very slow compared to JSON decoders (like ujson) which makes it impractical for applications that requires a "little more speed". I can tell that the speed drop is caused by byte decoding.

I believe this library requires an increase in performance.

Cheers!

**Comment by jfolz** [comment]
With encoding set [`PyUnicode_Decode`](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Decode) is called instead of [`PyBytes_FromStringAndSize`](https://docs.python.org/3/c-api/bytes.html#c.PyBytes_FromStringAndSize).
That is literally the only [difference](https://github.com/msgpack/msgpack-python/blob/master/msgpack/unpack.h#L228).

**Comment by Code-ReaQtor** [comment]
@jfolz thanks for pointing out.

I've used timeit to show the difference in speed.

```
without encoding:
 [0.30186917899845866, 0.2974697850004304, 0.33767431500018574, 0.28676681999786524, 0.2922696370005724]
with encoding:
 [0.4583792839985108, 0.4269451680011116, 0.4201795279986982, 0.4339324870015844, 0.4417613049990905]
```

PyUnicode_Decode adds ~50% overhead. Are there any alternatives? Should we be using Python C API?

**Comment by methane** [comment]
https://docs.python.org/3.6/c-api/unicode.html#utf-8-codecs

How is the speed difference if you replace `PyUnicode_Decode` with `PyUnicode_DecodeUTF8`?
That's I'm thinking in the future when I break backward compatibility.
(`encoding=` option is removed and use UTF-8 always).

**Comment by lbolla** [comment]
Using `PyUnicode_DecodeUTF8` does seem to speed things up a bit (about 20%).

I used this script: https://pastebin.com/NLanvQ5m

The timings on my machine are:

    noenc: 49.01663989999179
    enc (PyUnicode_Decode): 96.34805859998323
    enc (PyUnicode_DecodeUTF8): 81.82029770000554

**Comment by methane** [comment]
0.5.2 will use PyUnicode_DecodeUTF8() when passing `raw_as_bytes=False`.
https://github.com/msgpack/msgpack-python/pull/265/files#diff-ed60a250765123fb6a854e09466a29cbR235
