### ISSUE TITLE
Can't serialize tuples with strict_types

### ISSUE THREAD

**Issue by lbolla** [msgpack/msgpack-python#245]
When using `strict_types=True`, serializing tuples fails:

    >>> msgpack.dumps((1,2, 3), strict_types=True)
    ....
    TypeError: can't serialize (1, 2, 3)

(Using "tip" version of msgpack.)

**Comment by lbolla** [comment]
I figured a possible workaround, using `object_hook`:

    def default(o):
        if isinstance(o, tuple):
            return {
                '__type__': 'tuple',
                'value': list(o),
                }
        raise TypeError(repr(o))


    def convert(o):
        if o.get('__type__') == 'tuple':
            return tuple(o['value'])
        return o


    data = msgpack.packb(t, strict_types=True, default=default)
    expected = msgpack.unpackb(data, object_hook=convert)

    assert expected == t

**Comment by methane** [comment]
It's not "workaround", but "proper way".
Msgpack is like json.  It doesn't have "tuple" and "list". It has just "array".

See #100 and #98.  There were requests to distinguish tuple and list.

**Comment by lbolla** [comment]
Thanks! I've created a PR to document in unittests this procedure: it wasn't clear from the docs for me.
Also, the PR fixes a bug in formatting the error message.
