### ISSUE TITLE
Support serializing datetime objects

### ISSUE THREAD

**Issue by gappleto97** [msgpack/msgpack-python#252]
Since timestamps are now a part of the msgpack spec, shouldn't this library support serializing them?

**Comment by methane** [comment]
I won't do it soon, because there are no consensus about which type should be used for timestamp.
Datetime? Unix time in double? long integer ns?

**Comment by methane** [comment]
And datetime and timestamp is different.  Timestamp is stable, no timezone, no DST.
Datetime is very complicated.  It has timezone and DST.  I dislike handling datetime.

**Comment by thedrow** [comment]
What about https://github.com/temporenc/temporenc-python
We could simply provide the integration out of the box. It works.

**Comment by ChristThePhone** [comment]
For a short term circumvention it would be very helpful to at least be able to use an ext type with type code -1

**Comment by thehesiod** [comment]
link to spec I think is being discussed: https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type.  What's missing is the timezone

here's what I do to preserve everything from datetime including timezone and leverage int power of messagepack: https://gist.github.com/thehesiod/558f849bdd612593e25db3ded0d102b0

If it were a native type it would help a lot, could use timestamp + timezone delta.

**Comment by methane** [comment]
I won't anything other than spec.
Timestamp is unix time, not datetime.

**Comment by jfolz** [comment]
As to what datatype to accept for timestamps, there's really no alternative to `datetime`. `time.time()` and its pals are just numbers after all ;)

@thehesiod Timezone isn't missing. The spec states explicitly that all timestamps are UTC, and justifiably so. Timezones change (just look at the [commit log of pytz](https://git.launchpad.net/pytz/log/)), yet they're all defined as an offset to UTC, which **is** fixed.
Timeszones are a real deep rabbit hole you want to avoid going down. Sort of similar to text encoding. By now we've pretty much all agreed that UTF-8 is good. A similar consensus that timestamps are UTC would be amazing.

**Comment by thehesiod** [comment]
ya but if the discussion is about "serializing datetime objects" then timezone needs to be discussed otherwise you're losing information, and not guaranteeing what goes in is what comes out. From what I've seen things like comparing datetimes with datetime.timezone.utc != pytz.utc. Unfortunately python also supports datetimes w/o timezone, so that's another thing to think about where you don't know if the datetime is in utc.  If you don't want to support timezone then you shouldn't support automatic serialization of datetimes because you won't be able to guarantee in == out.   And yes, this is not an easy problem, but that's why this hasn't been done yet, and presumably why we're otherwise paid the big bucks :)  The underlying format is not at issue, it can be whatever, however to encode a "datetime" more information will be needed...otherwise a lot of assumptions will need to be stated, like perhaps only explicitly supporting UTC datetimes, and even then you'll need to know what "kind" of UTC datetime to return ;)

**Comment by jfolz** [comment]
Good point. Explicit is better than implicit, so timezone-less `datetime` objects should be rejected.

**Comment by methane** [comment]
In case of JSON, ISO8601 string is de-facto standard.
So we must keep usage of `default` for serializing datetime to str type.
In other words, I'm -1 to support datetime object by default.

On the other hand, in Python, timestamp is just a integer.
It may be ns or secs from EPOCH.  (FYI, Python 3.7 has new `time. time_ns ()` which returns Unix tiem in ns, https://www.python.org/dev/peps/pep-0564/ )

We can't distinguish int and timestamp by it's type.

My current idea is adding new types wrapping int.

```py
# msgpack.types

if PY2:
    int_type = long
else:
    int_type = int

class TimeStamp(int_type):
    pass
class TimeStampNano(int_type):
    pass
```

```py

from msgpack import packb, unpackb, types
import time

now = time.time_ns()
packed = msgpack.packb(types.TimeStampNano(now))
unpacked = msgpack.unpackb(packed)
assert isinstance(unpacked, TimeStampNano)
assert unpacked == now
```

User can use `default` function to convert `datetime` to `TimeStamp` or `TimeStampNano`.

**Comment by gappleto97** [comment]
To be clear, my title was a mistake. I meant for it to implement the type added to the spec, but at the time I had misread the spec.

**Comment by jfolz** [comment]
@methane The spec doesn't mention timezone specifically, but all reference points are defined in UTC. Would it be the user's responsibility to convert to local time to UTC?

**Comment by methane** [comment]
> The spec doesn't mention timezone specifically,

Timestamp doesn't have timezone.  It is always UTC.

> Would it be the user's responsibility to convert to local time to UTC?

Yes.  Converting datetime to timestamp is user's responsibility.
msgpack doesn't convert datetime to timestamp implicitly.

**Comment by danni** [comment]
For those looking to decode data from other msgpack implementations that include timestamps. Here's the code you'll need.

If you're getting a `ValueError` with "code must be 0~127" this is likely why (timestamps have type code `-1`).

```
def ext_hook(code, data):
    if code == -1:
        if len(data) == 4:
            secs = int.from_bytes(data, byteorder='big', signed=True)
            nsecs = 0;
        elif len(data) == 8:
            data = int.from_bytes(data, byteorder='big', signed=False)
            secs = data & 0x00000003ffffffff;
            nsecs = data >> 34;
        elif len(data) == 12:
            import struct

            nsecs, secs = struct.unpack('!Iq', data)
        else:
            raise AssertionError("Not reached");

        return datetime.datetime.utcfromtimestamp(secs + nsecs / 1e9)

    else:
        return msgpack.ExtType(code, data)

msgpack.unpack(data, ext_hook=ext_hook)
```

**Comment by danni** [comment]
And if you need the other side of this, here's a lazy version that only deals in 8-byte timestamps:

```
class KludgedExtType(msgpack.ExtType):
    """
    This is an ExtType that doesn't care for rules.
    """
    def __new__(cls, code, data):
        return super(msgpack.ExtType, cls).__new__(cls, code, data)

def default(obj):
    """MsgPack object hook for encoding datetimes."""
    if isinstance(obj, datetime.datetime):
        # always encode in the 8-byte form
        secs = int(obj.timestamp())
        nsecs = obj.microsecond * 1000

        data = (nsecs << 34) | secs
        data = data.to_bytes(8, byteorder='big')

        return KludgedExtType(-1, data)

    return obj

msgpack.packb(record, default=default, use_bin_type=True)
```

**Comment by brandond** [comment]
So, why isn't support for Timestamps in the core module yet? It's been in the spec since August of 2017. It's frustrating to have to monkeypatch things just to get support for standard features.

**Comment by methane** [comment]
Why don't you read the discussion above?
Datetime is not timestamp.  Python uses integer for timestamp.

**Comment by gappleto97** [comment]
Except that is not the expectation of the average developer, and umsgpack already uses datetime objects for this feature.

**Comment by methane** [comment]
It's bad idea and they broke datetime with offset.
It will create wrong timestamp, when "aware" datetime or "naive" datetime represents local time.
