### ISSUE TITLE
pip install silently installs from source without the cython modules on cpython 3.6

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [msgpack/msgpack-python#255]
while trying to install borg i noted that msgpack is installed from source and without using cython
the docs/readme have no details on how to propperly install

**Comment by methane** [comment]
You don't need Cython to install msgpack with extension module.
It's just your environment issue.  You should fix it yourself.

**Comment by RonnyPfannschmidt** [comment]
@methane well - a list of required packages for building from source would help as much as going and publishing wheels for more released python versions

**Comment by methane** [comment]
- compiler

That's all.  Nothing special.

**Comment by RonnyPfannschmidt** [comment]
well - i had a compiler ... that didn't help ...

and its always a pain experience to walk across ugly gcc errors to find out what internal command needs what subpackage - in particular its something that will cost a beginner massive amounts of time

**Comment by methane** [comment]
pip's log may help you.
I can't help you.

Anyway, you and beginners can ask question on Stackoverflow.
