### ISSUE TITLE
`long` packing errors in python 2.7.3

### ISSUE THREAD

**Issue by HoverHell** [msgpack/msgpack-python#256]
>>> d = long(1456174800000); msgpack.loads(msgpack.dumps(d)) == d
    False

Using python 2.7.3, msgpack-python 0.4.7 or 0.4.8.

This error does not happen in msgpack-python 0.4.6, nor in python 2.7.12 msgpack-python 0.4.8.

Internally:

    >>> msgpack.dumps(long(1456174800000))
    '\xce\x05d\x1c\x80'

for some reason, int32 is used.

At the same time,

    >>> msgpack.dumps(int(1456174800000))
    '\xcf\x00\x00\x01S\n\xc8\x1c\x80'

`int` with the same value works correctly.

Additionally, #71 mentions that large integers should raise an error; however, that does not happen (python 2.7.3, msgpack-python 0.4.8):

    >>> d = long(14561748000000000000000000000000000000); msgpack.loads(msgpack.dumps(d)) == d
    False

Again, works correctly in python 2.7.12

**Comment by methane** [comment]
Why 2.7.3?  It's tooo old.

**Comment by methane** [comment]
See #209 and #169.

System Python is maintained by distributors, but "maintained" doesn't mean
"backporting all bugfix of Python 2.7.x".
Your issue is fixed several years ago, and neglected by Ubuntu.

All you need is building Python by yourself for your application.
Use system Python only for running system application.

**Comment by HoverHell** [comment]
Yes, I know it is old. Mostly created this issue to document the problem.

**Comment by methane** [comment]
If you know, write it at first.
I'm very busy.  Don't annoy me.

**Comment by sakateka** [comment]
For the purposes of documentation of this issue
```
root@d7e1e3d5df68:/# cat /etc/issue.net 
Ubuntu 12.04.5 LTS
root@d7e1e3d5df68:/# dpkg -l python
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version                     Description
+++-===========================-===========================-======================================================================
ii  python                      2.7.3-0ubuntu2.2            interactive high-level object-oriented language (default version)
root@d7e1e3d5df68:/# python
Python 2.7.3 (default, Oct 26 2016, 21:01:49) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import msgpack
>>> d = long(1456174800000); msgpack.loads(msgpack.dumps(d)) == d
True
>>> msgpack.dumps(long(1456174800000))
'\xcf\x00\x00\x01S\n\xc8\x1c\x80'
>>> 
```
