### ISSUE TITLE
cannot msgpack a structure that includes a pandas Dataframe

### ISSUE THREAD

**Issue by vegabook** [msgpack/msgpack-python#257]
I am writing a python memoizer and mspack is so much faster than pickle. 

Problem is for data structures such as a simple list, that I can usually msgpack in one go, even if they include a numpy array (using msgpack-numpy), if that data structure includes a pandas I am out of luck. This is despite the fact that pandas itself does msgpack via pd.read_msgpack, and pd.to_msgpack. 

Is there any way that I can patch msgpack, just like numpy-msgpack does, to do pandas in the same way? 

Here is an illustration of the problem:

```
import msgpack
import msgpack_numpy as m
import numpy as np
import pandas as pd

m.patch()   # enable msgpack on numpy


xx = ["123", 1, 2, 3, np.random.rand(3)] # heterogenous including numpy
mm = msgpack.unpackb(msgpack.packb(xx))
print([xx[x] == mm[x] for x in range(len(xx))]) # all good. packs and unpacks beautifully

xx 

yy = ["123", pd.DataFrame([1, 2, 3])]
pp = [x.to_msgpack() if isinstance(x, pd.DataFrame) else msgpack.packb(x) for x in yy] # no problemo, but how to decode?
print("done pp")
pp = msgpack.packb(yy) # problemo
```

Now I could mess around with creating my own serializer / deserializer using flags for when things must go back to pandas, but as you can probably imagine, it would be a mess and very inefficient by comparison with msgpack's awesome native speed. Any hints? Pandas is becoming really popular.

**Comment by vegabook** [comment]
so question. Is this msgpack-python implemented in C? I am not a C programmer these days but can get back into it This funcationality is important enough for me that I will dedicate necessary time to do it myself, but want to just ensure that community is happy with that and doesn't want to take this on itself. Please let me know.

**Comment by jfolz** [comment]
What you want to achieve is already possible with msgpack-python.
These should give you some ideas:
https://github.com/msgpack/msgpack-python#extended-types
https://github.com/msgpack/msgpack-python#packingunpacking-of-custom-data-type

Please ask further usage questions elsewhere like stackoverflow, this is an issue tracker.

**Comment by thedrow** [comment]
@vegabook you should take a look at apache arrow. It's much more suitable for your use case.

**Comment by vegabook** [comment]
@thedrow. Done a few days ago and very impressed _but_, does not share across nodes. My calcs will be run by different users and I need a central hash repository.

**Comment by methane** [comment]
Doubly-packing (or msgpack in msgpack) is idiom for it which is widely used.

```python
yy = ["123", pd.DataFrame([1, 2, 3]).to_msgpack()]
serialized = msgpack.packb(yy)
xx = msgpack.unpackb(serialized)
xx[1] = pd.read_msgpack(xx[1])
```

Overhead is very small.  It's far better than customize msgpack or make msgpack-python complicated.

**Comment by vegabook** [comment]
Yes this is what I am doing. However now I have to "remember" which past of my array did not use standard msgpack and which must use pd.read_msgpack, so it means extra fields stored in my database, extra logic. This is not the case for msgpack-numpy where I can simply pack the whole list without worrying what's in it (as long as it's native python or Numpy, but not pandas). 

Basically this is preventing me from using msgpack. I have to stay with pickle unfortunately.

**Comment by methane** [comment]
Yes.  msgpack is simple format like json.
I don't want to add support for each library, framework or application.

**Comment by jfolz** [comment]
@vegabook You don't have to. Define a default function to create an `Extension` type for Pandas objects. Then use `ext_hook` to convert back to Pandas.
