### ISSUE TITLE
Unpacker.read_bytes behaves unpredictably with a size of -1 / support for reading all outstanding bytes?

### ISSUE THREAD

**Issue by RR2DO2** [msgpack/msgpack-python#259]
Some python read() methods take -1 as a parameter to return all remaining bytes in a stream/buffer. While msgpack's Unpacker read_bytes isn't explicitly documented as supporting this, it used to accept -1.

This lead to various corruptions though; the c implementation would not return all bytes. At least with 0.4.8 it now raises an error stating -1 is invalid (side-effect of calling the CPython related methods to obtain a size_t).

The fallback method however still accepts -1, but returns bad data in this case.

Our current workaround is to use read_bytes(sys.maxint) to obtain any other bytes from the reader passed into Unpacker, however this only works in the c implementation. The fallback returns OutOfData since there aren't that many bytes available.

There are a few things that likely should be done. read_bytes should behave consistently between the c and fallback implementations. Passing -1 into any implementation should not corrupt any internal state or return invalid data. Finally, having a dedicated Unpacker.read() that would return all data in the reader still outstanding would be invaluable.

Not sure if help would appreciated in writing a patch for this? Also not sure why there is no .read() method already - instead of the less standard read_bytes?

**Comment by methane** [comment]
Unpacker is not file-like object.  And I don't have plan to make Unpacker file-like.
And I dislike read_bytes() API.  It is API for only less than 1% people.
JSON libraries doesn't have it.  Other languages msgpack libraries doesn't have it.
I want to deprecate it rather than promote or enhance it.

**Comment by RR2DO2** [comment]
In that case there must be a way for unpacker to not consume more than the actual msgpack payload from the reader. If there is a single reader stream that has more data in it than just a msgpack object it should consume only that. Either through being aware of its own structure, or at a bare minimum by allowing a size to be passed into the constructor defining how many bytes may be consumed from the stream to allow for an external framing protocol?

Though you could argue that the caller should do the pre-buffering of the file like object - effectively copying out/managing the stream for Unpacker this would lead to either an inefficiency (a copy of the data before Unpacker processes it) or a slightly awkward file like object to be passed into as the reader which wraps the initial stream but has a 'max bytes that can be read' feature. The latter would be nicer if it would just be part of the Unpacker.

Aside from all of this, the c implementation and fallback case should still behave in the same way if read_bytes persists.

**Comment by methane** [comment]
> or at a bare minimum by allowing a size to be passed into the constructor defining how many bytes may be consumed from the stream to allow for an external framing protocol?

You can use feed() method in such case.

Unpacker(file_like) is convenient way which can be used when no precise control is required.

**Comment by jfolz** [comment]
In case of external framing `unpackb` is the method of choice. It simply reads from many buffer-like objects you give without copying. This is **much** faster than feeding. The overhead for creating a temporary `Unpacker` object is negligible by comparison.
