### ISSUE TITLE
package rename issues with msgpack 0.5.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#268]
https://github.com/borgbackup/borg/issues/3515

I've seen the transition package you've made, but somehow it seems to not work as expected (or at least not for everybody).

**Comment by methane** [comment]
Have you seen [this](https://github.com/msgpack/msgpack-python#upgrading-from-msgpack-04)?

**Comment by methane** [comment]
I'm considering msgpack-python 0.5.0.1 which is clone of msgpack 0.5.
Both packages have same content, and installed later will overwrite others.

**Comment by jfolz** [comment]
pypa/pip/issues/4961

**Comment by ThomasWaldmann** [comment]
@methane no, but thanks for pointing to that. the problem is just that a lot of users do not intend to upgrade msgpack, they just intend to upgrade borg (in our case). So they'll maybe read borg upgrade notes, but not msgpack's. Let's hope the clone idea works.

**Comment by methane** [comment]
I released msgpack and msgpack-python 0.5.1.
msgpack-python is clone of msgpack this time.

**Comment by ThomasWaldmann** [comment]
I can confirm that with 0.5.1 `pip install -U` now works as expected and does not cause an ImportError later due to missing files. Thanks!
