### ISSUE TITLE
use_bin_type - confusing future hint

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#270]
```
string and binary type

Early versions of msgpack didn't distinguish string and binary types (like Python 1).
```
Ehrm, did you really mean Python 1.x here or rather 2.x?

```
The type for representing both string and binary types was named raw.

For backward compatibility reasons, msgpack-python will still default all
strings to byte strings, unless you specify the use_bin_type=True option
in the packer.
```
So that means the current default is still False (or rather 0, from the code).

```
If you do so, it will use a non-standard type called bin to serialize byte arrays,
and raw becomes to mean str. If you want to distinguish bin and raw in the
unpacker, specify encoding='utf-8'.

In future version, default value of ``use_bin_type`` will be changed to ``False``.
```
Did you mean `True` here?

```
To avoid this change will break your code, you must specify it explicitly even when you want to use old format.
```

**Comment by methane** [comment]
> Ehrm, did you really mean Python 1.x here or rather 2.x?

Yes.  Python 1 didn't have unicode type.  It's like old msgpack.

Python 2 has unicode type, but unicode/bytes separation is not complete.
It's like transition time to new msgpack.

Python 3 separate unicode/bytes clearly, it's like new msgpack only world.
It's my goal.

> So that means the current default is still False (or rather 0, from the code).

Yes.

> Did you mean True here?

Yes, I was wrong.

**Comment by methane** [comment]
I noticed adding `use_bin_type=True` everywhere is tiring job.
I'll remove FutureWarning.

In most case, changing default of use_bin_type doesn't loss people's data.
It just use new format and msgpack-python 0.4 can decode it.

**Comment by ThomasWaldmann** [comment]
A while ago, I looked at that stuff for borgbackup and my conclusion back then was that we can't easily migrate to the more pretty new stuff (== use_bin_type=True) and we have to stick with =False.

**Comment by methane** [comment]
My current plan is:

* 0.5.1 -- Remove FutureWarning for use_bin_type.
* 0.5.x -- Add raw_as_bytes option to Unpacker.
* 0.6 -- Deprecate encoding option of Unpacker and change default options
  (use_bin_type=True for packer, and raw_as_bytes=False for unpacker).
* 0.7 -- Remove encoding option.

**Comment by methane** [comment]
@ThomasWaldmann Why?  If your reason is not special enough, I need to keep FutureWarning...

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/968 it was quite a while ago, but this ticket was the result.

**Comment by methane** [comment]
Thanks.  So I need to notice people about changing default option someway.
But I don't think FutureWarning is good idea.  Maybe, version 1.0 is good way to notice it.

So, my new plan is:


* 0.5.1 -- Remove FutureWarning for use_bin_type.
* 0.5.x -- Add raw_as_bytes option to Unpacker.
* 0.6 -- Deprecate encoding option of Unpacker
* 0.7 -- Remove encoding option of Unpacker
* 1.0 -- Change default options (use_bin_type=True for packer, and raw_as_bytes=False for unpacker).

Each version will have more than 3 months timespan.  (0.6 will be more than 3 months
after raw_as_bytes option.)

**Comment by ThomasWaldmann** [comment]
Looks like "removing encoding option of Unpacker" also would cause troubles.

**Comment by methane** [comment]
But it can have normal deprecation period...

**Comment by methane** [comment]
I noticed encoding/errors option should be removed from Packer too.
I don't allow people use other than UTF-8.  raw should be UTF-8 encoded.

**Comment by ThomasWaldmann** [comment]
How about just doing all breaking changes at 1.0, like semantic versioning?
Then i would just put mspack-python >=0.4.6,<1.0 in requirements and nothing bad would happen, hopefully.

**Comment by methane** [comment]
I want to use semver *after* 1.0.
Until 1.0, I want to remove many code as possible.
For it, small breaking change will happen every 0.x version.

**Comment by methane** [comment]
Until 1.0:

* 0.x.y has bug fixes and backward compatible new options.
* 0.x has new deprecation and small breaking changes like removing deprecated stuff.
* If 0.x.y introduce new deprecation, 0.x+1 should not remove it. 0.x+2 may remove it.

**Comment by ThomasWaldmann** [comment]
How shall msgpack using code deal with that? Check the msgpack version and then call the api differently? You can not assume that everybody out there will get latest msgpack from pypi, there will also be packaged older msgpack in linux distributions.

**Comment by methane** [comment]
Using venv.

But after considering several minutes, I'm OK to do breaking changes at 1.0 as possible.

* 0.5.1 -- Remove FutureWarning for use_bin_type.
* 0.5.x -- Add raw_as_bytes option to Unpacker.
* 0.6 -- Deprecate encoding option.
* (maybe) 0.7 -- Deprecate more stuff. 
* 1.0 -- Remove all deprecated options and change default options (use_bin_type=True for packer, and raw_as_bytes=False for unpacker).

**Comment by jfolz** [comment]
Distribution-provided packages should only be used by other distribution-provided packages, which will use compatible versions.
I do agree though that versions with breaking changes should be kept to major versions.
Version numbers are free after all :)

**Comment by methane** [comment]
May I close this issue?
