### ISSUE TITLE
[RFC] Prevent upgrading to msgpack 1.0 on Python 2

### ISSUE THREAD

**Issue by methane** [msgpack/msgpack-python#275]
From msgpack 1.0, I will change default behavior to use new msgpack spec.

It means `packb(["hello", "world"])` produces array of two bin data, not str on Python 2.
Who Python 2 user needs such breaking change?

My idea is adding `requires-python>=3.5` metadata to msgpack 1.0, while keep tested
with Python 2.  User want msgpack 1.0 can use `pip --ignore-requires-python`` option.
(see pypa/pip#3864)

Maybe, msgpack 1.1 will really drop Python 2 support.

**Comment by daa** [comment]
On the other hand unpacking ``packb(["hello", "world"])`` packed as bin data will return the same list of binary strings ``["hello", "world"]`` on Python 2, so this change is not really breaking when used in py2 environment.

**Comment by methane** [comment]
Msgpack is *cross* language format.


2018/01/13 0:48 "daa" <notifications@github.com>:

**Comment by jfolz** [comment]
IMO the current defaults are always worse and it's definitely worth upgrading Python 2 users. I use `use_bin_type=True` and `encoding='utf-8'` exclusively. In fact one of the more confusing aspects of using msgpack when I started was that I assumed that there was a distinction between binary and string data.

With current default `use_bin_type=False` the receiver can turn `str` (`bytes`) into `unicode` (`str`):
```
>>> packb(['hello', 'world'], use_bin_type=False)
'\x92\xa5hello\xa5world'
>>> unpackb(_, encoding='utf-8')
[u'hello', u'world']
```

Of course that means you can easily run into `UnicodeDecodeError` when binary data is sent.
With `use_bin_type=True` and `encoding='utf-8'` messages round-trip correctly.
I know there are probably a lot of Python 2 developers out there that are not aware of the fact that their "strings" are actually binary. But I hope that msgpack users are more advanced than that and at least the vast majority is aware of 'b' and 'u' prefixes and `unicode_literals`.

Regarding dropping support for 2.7 at some point in the future:
That's a really touchy subject. I know that it would simplify a lot of msgpack code (specifically some of the most complex bits), but it would also mean a lot of libraries that depend on msgpack would either have to drop support for 2.7 or use legacy versions of msgpack. Couple that with the fact that a lot of Linux distributions currently ship with IMO absolutely **awful** Python 3.4, so 2.7 is actually the better option here.
One reasonable policy is probably to stick with the "official" EOL date: 2020.

**Comment by methane** [comment]
> With current default use_bin_type=False the receiver can turn str (bytes) into unicode (str):

But since `b"foo" == u"foo"` on Python 2, it is not so huge problem.
At least, the problem exists.
On the other hand, if upgrading msgpack change default option silently,
it creates new problem.
When Python 2 send serialized (binary) string via `packb("foo")`
and Python 3 receive it, it become bytes and `b"foo" != "foo"` in Python 3.

> But I hope that msgpack users are more advanced than that and at least the vast majority is aware of 'b' and 'u' prefixes and unicode_literals.

If they know it, they can read manual and override default options.
We can't assume users just using default options knows packing string data
into bin type introduce new problem to **new** msgpack world.

When they upgrade to msgpack 1.0, we cannot assume msgpack data with new
format separates string and binary anymore!

---

> but it would also mean a lot of libraries that depend on msgpack would either have to drop support for 2.7 or use legacy versions of msgpack.

They use legacy version of Python already.  Why using legacy msgpack is so bad?

> Couple that with the fact that a lot of Linux distributions currently ship with IMO absolutely awful Python 3.4, so 2.7 is actually the better option here.

I dislike this logic.  Distros supports legacy software doesn't mean all OSS library's
(volunteer) developer support legacy software too.
If people want to use legacy software maintained by distro, they should do it.
If people want to use new software, they should install it by themselves.
But mixing them is silly idea.

I (and my company) moved Python 3 completely several years ago.
I use Python 2 only for maintain OSS projects for several years.  No one paid me
for supporting Python 2, of course.  Volunteer support is totally different from distro's support.

> One reasonable policy is probably to stick with the "official" EOL date: 2020.

Maybe, I will state msgpack 1.0 as "LTS" and do bugfix for it until 2020.

**Comment by jfolz** [comment]
> On the other hand, if upgrading msgpack change default option silently, it creates new problem.

Upgrading won't be problem-free for Python 3 users either. Where they expect binary they may receive strings instead. Python 3 is much more picky about which functions take which type. The current spec has to become the default at some point though.
And to play devil's advocate: maybe it will teach some people to always specify both minimum and maximum version of packages they depend on :)

> I dislike this logic. Distros supports legacy software doesn't mean all OSS library's
(volunteer) developer support legacy software too.

I agree. I just wanted to point out that there are lots of people out there that don't have easy access to Python 3.5+. Some packages with native components (OpenCV) don't play well with the likes of pyenv. I've had some "fun" installing newer interpreters alongside system Python with limited success.
msgpack is a relatively low level library that's used in a lot of different software. Unless there's significant effort required it would be nice to keep 2.7 support for some time longer :)
