### ISSUE TITLE
update msgpack-python package on pypi

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#280]
on pypi, there is still the broken msgpack-python 0.5.2 and it breaks our CI tests.

so, please update the package to whatever never version that works.

**Comment by methane** [comment]
Uploaded 0.5.4.
But please move to msgpack.

**Comment by ThomasWaldmann** [comment]
Thanks. We'll go to `msgpack` in master, but I guess I'ld rather not break anything in stable by changing that there, too.
