### ISSUE TITLE
Longer unicode strings dumped as str 16 instead of str 8 when using use_bin_type=False

### ISSUE THREAD

**Issue by vytas7** [msgpack/msgpack-python#293]
Using Python 3.5.2 and msgpack-0.5.6 from PyPi, longer (but not as long that they would require ``str 16``) unicode strings get erroneously dumped as ``str 16`` depending on ``use_bin_type`` value unless I misunderstood something.

Consider a following test scenario:
```python
>>> import msgpack
>>> msgpack.version
(0, 5, 6)
>>> S = 'short'
>>> type(S)
<class 'str'>
>>> msgpack.packb(S)
b'\xa5short'
>>> msgpack.packb(S, use_bin_type=True)
b'\xa5short'
>>> msgpack.packb(S, use_bin_type=False)
b'\xa5short'
>>> assert msgpack.packb(S, use_bin_type=True) == msgpack.packb(S, use_bin_type=False)
>>> S = 'this is a bit longer string'
>>> len(S)
27
>>> assert msgpack.packb(S, use_bin_type=True) == msgpack.packb(S, use_bin_type=False)
```

So far so good, everything works as expected. Our string gets dumped as a ``fixstr`` regardless of ``use_bin_type`` value.

Now let us continue the same test session by crossing the ``fixstr`` border:

```python
>>> S = 'this is a bit longer string / 01234567890ABCDEF'
>>> len(S)
47
>>> assert msgpack.packb(S, use_bin_type=True) == msgpack.packb(S, use_bin_type=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> msgpack.packb(S, use_bin_type=True)
b'\xd9/this is a bit longer string / 01234567890ABCDEF'
>>> msgpack.packb(S, use_bin_type=False)
b'\xda\x00/this is a bit longer string / 01234567890ABCDEF'
```

As I understand, ``use_bin_type=False`` leads to wrong representation as ``str 16``.

It is not a problem *per se* when serializing and deserializing, but it follow recommendation in *MessagePack* specification which states:

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

**Comment by vytas7** [comment]
Reading into source code a bit, these seems to be by design, sort of.

``pack_template.h`` reads:

```c
static inline int msgpack_pack_raw(msgpack_packer* x, size_t l)
{
    if (l < 32) {
        unsigned char d = 0xa0 | (uint8_t)l;
        msgpack_pack_append_buffer(x, &TAKE8_8(d), 1);
    } else if (x->use_bin_type && l < 256) {  // str8 is new format introduced with bin.
        unsigned char buf[2] = {0xd9, (uint8_t)l};
        msgpack_pack_append_buffer(x, buf, 2);
    } else if (l < 65536) {
        unsigned char buf[3];
        buf[0] = 0xda; _msgpack_store16(&buf[1], (uint16_t)l);
        msgpack_pack_append_buffer(x, buf, 3);
    } else {
        unsigned char buf[5];
        buf[0] = 0xdb; _msgpack_store32(&buf[1], (uint32_t)l);
        msgpack_pack_append_buffer(x, buf, 5);
    }
}
```

Maybe this implication could be clarified in the documentation, with the fact that ``use_bin_type`` implies an older specification standard, not just a different way to dump strings?

**Comment by methane** [comment]
I'm not good at English and writing document is harder than writing Python or C.
PR for improve documentation is welcome.

**Comment by methane** [comment]
Oh, I already described it:
https://github.com/msgpack/msgpack-python/blob/d4675bee6c83d42cecda9a84e6716021eb2ad679/msgpack/_packer.pyx#L81

Please send pull request if my English is wrong.  I can do nothing about it and I don't want keep such issue open, to focus real issues.

**Comment by vytas7** [comment]
Sorry, it was my fault! Somehow missed that piece of documentation.

Sorry for wasting your time on this.
