### ISSUE TITLE
Change default decoder limits

### ISSUE THREAD

**Issue by methane** [msgpack/msgpack-python#295]
Current default limits seems too large.  It can cause DoS attack.
Change default value to more safe value.

Current plan is "about 1MiB on amd64 system".

* `max_bin_len`: 1024*1024
* `max_str_len`: 1024*1024
* `max_array_len`: 1024*1024/8  (each pointer has 8 bytes)
* `max_map_len`: 1024*1024/32  (8byte key,hash,value, and some extra space)

**Comment by codypiersall** [comment]
I guess my idea about waiting for all the data doesn't work for array and map types though.

**Comment by jfolz** [comment]
A migration guide would certainly go a long way to help devs update their code for upcoming versions.

**Comment by codypiersall** [comment]
One more idea: we could have a kwarg `trusted_source` which if True ignores the limits on `max_bin_len` and the rest.  It would default to False.  This would solve the issue where you have to pass a lot of keyword arguments; currently, if you want to indicate that you trust the other side, you have to set bin/str/array/map/ext separately.

If you are interested in this, I would be willing to attempt a PR in the next couple weeks.

**Comment by methane** [comment]
>  It certainly caused surprising crashes for me, and I guess I'm not alone.

It means many people doesn't aware `max_xxx_type` options although it's very important
to avoid DoS attack.
That's why I think I must change the default value to safe.

Of course, I know there are many applications they are not relating to DoS attack.
But the library doesn't know it.  Application should specify it.

>  Maybe it would be possible to ...

It is not practical because it will kill performance, or introduce a lot of code (and bugs) I don't want maintain.

> On a related note, it would be really nice if the docs could be updated to the latest version that incorporates these changes; 

I'm really sorry.  I didn't notice the doc isn't updated automatically.
I manually start build and I configured webhook too.  The doc should be updated soon.

**Comment by methane** [comment]
> A migration guide would certainly go a long way to help devs update their code for upcoming versions.

Sorry, I can't understand this English.
Docstring and ChangeLog is explicit already.  Please don't require me to write more English.
Writing English is very hard to me, maybe than you think.  It leads me to burn-out.

**Comment by methane** [comment]
> One more idea: we could have a kwarg `trusted_source` which if True ignores the limits on `max_bin_len` and the rest.

I dislike the idea.  I don't want to add any more options unless strictly required.
And two knob for one thing seems ugly too.

**Comment by codypiersall** [comment]
Thanks for the feedback @methane.

> It is not practical because it will kill performance, or introduce a lot of code (and bugs) I don't want maintain.

That's fair.

> I don't want to add any more options unless strictly required. And two knob for one thing seems ugly too.

This is the same problem I was trying to solve.  From my perspective, the various `max_xxx_len` are 5 knobs for one thing: I wanted a way for msgpack to attempt to decode whatever it was given.  Your solution you came up with [just above](https://github.com/msgpack/msgpack-python/issues/295#issuecomment-456618294) would work just fine for me.

Ping me back if you don't have the time or desire to implement it and I will give it a try.

Side note:  Does it even make sense to have the `max_xxx_len` args to `unpackb`?  As I understand it, it's not really susceptible to the same DoS since you can *always* verify if the needed number of bytes are present.

**Comment by fake-name** [comment]
Has **anyone** ever had a DoS attack that this even helps mitigate? Is anyone exposing messagepack interfaces to untrusted inputs?

If you're going to add a interface for handling untrusted inputs, don't just overwrite the current API with one that will no longer work in a lot of cases. Adding a separate unpacker like `UnpackUntrusted` or similar would seem much more clear to me.

**Comment by methane** [comment]
> Has anyone ever had a DoS attack that this even helps mitigate? Is anyone exposing messagepack interfaces to untrusted inputs? This sounds like a solution in search of a problem.

RPC is one of the usage msgpack is designed for.  (See [this article](https://msgpack.wordpress.com/2010/05/04/introduction-to-messagepack-rpc/))
And Fluentd is most successed project which has msgpack API.


> Right now, you have _four_ knobs I have to set. 

For knobs for four thing.  It's orthological.
And, again, you don't "have to".  I added "auto limit" in #342.  You can just use **only one** option for Unpacker, and zero option for `unpackb` now.

**Comment by methane** [comment]
> If people need to worry about DoS attacks, they can just look at the size of the string they're shoving into the unpacker.

Only five bytes input (e.g. `b'\xdd\xff\xff\xff\xff'`) can consume 32GB RAM.
When CPython provides public API for preallocated dict, five bytes can consume 96GB RAM.

**Comment by fake-name** [comment]
> Only five bytes input (e.g. b'\xdd\xff\xff\xff\xff') can consume 32GB RAM.

Well, huh. Never mind, then.
