### ISSUE TITLE
only pre-releases on github-releases

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#298]
just noticed that all 0.5.x stuff on github releases is marked as pre-release and only 0.4.6 is marked as "latest release".

https://github.com/msgpack/msgpack-python/releases

is this on purpose?

**Comment by methane** [comment]
Yes.  I use github's release for uploading wheels from AppVeyor, not for releasing msgpack.
I release msgpack only on PyPI.

**Comment by zwn** [comment]
Mentioning AppVeyor you must mean Windows wheels, right? However, there are no Windows wheels on pypi for the 0.5.6 release - please see https://pypi.python.org/pypi/msgpack/0.5.6. Is that expected?

**Comment by methane** [comment]
Good catch.  I forgot to push "deploy" button afeter AppVeyor build.
I'm not AppVeyor expert and I can't automate full process yet.

**Comment by methane** [comment]
Windows wheels are uploaded.

**Comment by zwn** [comment]
Thanks!
