### ISSUE TITLE
Package rename broke saltstack on FreeBSD

### ISSUE THREAD

**Issue by tylerburns** [msgpack/msgpack-python#301]
Renaming the package to just msgpack is causing saltstack on FreeBSD to refuse to run because it thinks the package isn't there. I'm sure a lot of folks would appreciate it if this were added to the change log.

**Comment by jfolz** [comment]
The OG package isn't gone: https://pypi.org/project/msgpack-python/
Up to 0.4.8 there's all the wheels there.
Newer versions are available as source (which pip will happily install).
