### ISSUE TITLE
Optionally control packing as int or uint

### ISSUE THREAD

**Issue by itaiin** [msgpack/msgpack-python#302]
A little context:
I am writing a piece of code which supposed to send epoch timestamps to a service (Metrictank) encoded in msgpack.
The problem is this: the recieving software is written in golang and expects these timestamps strictly as an `int`, but `msgpack-python` is encoding them as `uint`, since the values are obviously positive. 

I searched documentation as well as the msgpack-python code but haven't been able to find a way to control this encoding. for example some sort of  `EnforceType` class that can wrap the value with a desired code when absolutely needed?

**Comment by methane** [comment]
Many msgpack implementation doesn't have such option.  It's very common practice of msgpack.
Please fix your decoder side.

For example,

vmihailenco/msgpack DecodeInt64() accepts both of int/uint.
https://github.com/vmihailenco/msgpack/blob/a053f3dac71df214bfe8b367f34220f0029c9c02/decode_number.go#L122-L124

ugorji/codec/go same.
https://github.com/ugorji/go/blob/f3cacc17c85ecb7f1b6a9e373ee85d1480919868/codec/msgpack.go#L538-L539

**Comment by itaiin** [comment]
Thanks for the quick reply! I was writing this since I can't control the decoder side.
But now that you mention that its a common practice I now see that the library they use, `tinylib/msgp`, included a patch 3 months ago to fix int/uint interop.
