### ISSUE TITLE
reintroduce Python 3.4 support?

### ISSUE THREAD

**Issue by FelixSchwarz** [msgpack/msgpack-python#306]
In #249 testing for Python 3.4 was removed (together with Python 2.6 and 3.3). Due to some unfortunate events msgpack 0.5.6 landed in Fedora EPEL 7 (RHEL/CentOS 7) and broke borgbackup which uses Pyton 3.4 there.

Issue #249 contains some [statistics](https://github.com/msgpack/msgpack-python/pull/249#issuecomment-341258286) which show that Python 3.4 usage was not that much lower than 3.5/3.6 (about 2.9% vs. 6.2% vs. 6.6%).

Is there any chance we could reintroduce Python 3.4 support in msgpack or did you encounter too many issues with that version of Python?

**Comment by methane** [comment]
> Due to some unfortunate events msgpack 0.5.6 landed in Fedora EPEL 7 (RHEL/CentOS 7) and broke borgbackup which uses Pyton 3.4 there.

"broke"?  Where the report of error and traceback?

**Comment by methane** [comment]
See #307.  Test passed on Python 3.4.  What I broke?

Anyway, I don't want support Python 3.4.
But I'm OK to keep running test with Python 3.4 for a while (maybe, until end of this year).

**Comment by methane** [comment]
"Support Python 3.4" includes:

* Provide binary wheel.
* When there is bug report which is happened only with Python 3.4, I'll try to fix.

I will accept bugfix for Python 3.4 if it's easy.
But I don't try to debug a bug happened only with Python 3.4.  Bug should be reported to EPEL, not to me.
I don't use EPEL, RedHat or CentOS.  I don't want install it for debugging issue only happens on there.

**Comment by FelixSchwarz** [comment]
> I will accept bugfix for Python 3.4 if it's easy.
> But I don't try to debug a bug happened only with Python 3.4. Bug should be reported to EPEL, not to
> me. I don't use EPEL, RedHat or CentOS. I don't want install it for debugging issue only happens on
> there.

Completely fine with me :-)

**Comment by methane** [comment]
BTW, in the downstream, you said:

> BUT msgpack stopped supporting Python 3.4 in October 2017 [2].

It's not true.  Official support is stopped from... I forgot, but maybe 0.5.
#249 just removed test for unsupported versions.

**Comment by FelixSchwarz** [comment]
Btw: "until the end of the year" should also be fine for EPEL because Python 3.4 will be replaced by 3.6 at some point (base package already available).
