### ISSUE TITLE
Add support for Timestamp extension

### ISSUE THREAD

**Issue by brandond** [msgpack/msgpack-python#316]
Timestamp extension was added to msgpack spec in https://github.com/msgpack/msgpack/commit/40e3d3db8985528d41a0ded1f9581cede270ec95 over a year ago.
Sample pure python code to serialize/deserialize from datetime was provided in #252, but rejected due to lack of TZ offset support in the timestamp extension.

**Comment by randallpittman** [comment]
I don't understand why it's an issue to require timezone-aware `datetime` for serialization and convert to UTC with `datetime.as_timezone`. And then deserialize to UTC `datetime`. 

If that's making too many decisions for the user then why not just create a UNIX-epoch `(seconds, nanoseconds)` interface a-la `msgpack-c`'s `msgpack_timestamp` and `msgpack_object_to_timestamp` (new as of v3.1.0).

**Comment by randallpittman** [comment]
Furthermore, with the current implementation negative EXT codes are disallowed (since they're reserved for future Msgpack use) so I can't manually pack a timestamp into an `ExtType`. That kind of stinks.

**Comment by methane** [comment]
> but rejected due to lack of TZ offset support in the timestamp extension.

> I don't understand why it's an issue to require timezone-aware datetime for serialization and convert to UTC with datetime.as_timezone. And then deserialize to UTC datetime.

Lack of TZ is not the only reason.  I use it for just an example why msgpack choose unixtime.

datetime is easy (for humans), and unixtime is simple (for machine, program).
msgpack is for simple.  When load / store / transfer time data, unix time should be used.
This is desgin philosophy of msgpack.

I love the design philosophy.  I believe unixtime should be converted only when showing it to humans. Not when deserializing from wire format (=msgpack).

So I don't support datetime *by default*.  This doesn't mean I don't add *option* for datetime in the future, after timestamp support.  But it must not happen before *default*.

**Comment by methane** [comment]
> If that's making too many decisions for the user then why not just create a UNIX-epoch `(seconds, nanoseconds)` interface a-la `msgpack-c`'s `msgpack_timestamp` and `msgpack_object_to_timestamp` (new as of v3.1.0).

"why not"?  Why msgpack-ruby not?  Why msgpack-java not?  (These two are maintained by msgpack
designer)
It's because we're all busy and have more important things.

Python doesn't have specific type for unix timestamp.  It makes difficult to support it.
I need to design API carefully.  It needs lots of time, mental energy, and motivation.
I have not have them yet.  That's "why" it is not supported yet.

**Comment by randallpittman** [comment]
I understand your points. It seems to me that there are a few paths that keep things low-level:

* Make a `TimestampType` that packs/unpacks to a `Decimal`.
* Make a `TimestampType` that packs/unpacks to `posix_s` and `ns`. The question here is whether to support `float` `posix_s` and then what to do if `ns` is also provided.
* Allow some way for negative type codes in `ExtType` and allow users to manually pack timestamps. 
  * It appears that when using `msgpack-c` you can do `Packer.pack_ext_type(-1, <bytes>)`, but the pure python version in fallback.py doesn't allow this.
