### ISSUE TITLE
No manylinux wheels for 0.6.0?

### ISSUE THREAD

**Issue by jessecarbon** [msgpack/msgpack-python#335]
Pypi has `manylinux` [wheels for `msgpack` up to `0.5.6`](https://pypi.org/project/msgpack/0.5.6/#files), however there are only [windows wheels for `0.6.0`](https://pypi.org/project/msgpack/0.6.0/#files). I realize this was released today, just wondering if there will be `manylinux` wheels, since it takes a bit longer to install without them.

Thanks!

**Comment by methane** [comment]
released.
