### ISSUE TITLE
Better buffer protocol support

### ISSUE THREAD

**Issue by jakirkham** [msgpack/msgpack-python#336]
Would be nice if `packb` and friends were able to handle more complex buffers. Namely if it could handle buffers with types other than `uint8` like `PyObject*`. Also handling a shape would be nice. This can be handy when passing in a NumPy array of `object` type to `packb`.

**Comment by jfolz** [comment]
The only requirement to pack `memoryview`s is that they be contiguous. Dtype does not play a role, though there be dragons: anything that isn't single bytes will be packed in native byte order without any hint of what that order way. Supporting non-contiguous strides would be nice, though I suspect handling every possible case correctly is going to be a bit of nightmare and probably slower than using `np.ascontiguousarray`. I'd suggest prototyping this for 2D arrays first only going from there if there is any speed benefit.
I don't know how (or why) you would pack an object array. Packing arbitrary Python objects correctly is very complex, hence the glacial speed of pickle.

**Comment by methane** [comment]
Note that msgpack is serialization format like *json*.  It is not for dataset.
