### ISSUE TITLE
PyPi package hash mismatch

### ISSUE THREAD

**Issue by ntrepid8** [msgpack/msgpack-python#337]
I'm using `pipenv` to install dependencies and my builds just started throwing hash mismatch errors:

```
[pipenv.exceptions.InstallError]: ['THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.', '    msgpack==0.6.0 from https://files.pythonhosted.org/packages/49/15/1857b4d250ca780c1ee3238ba7cd7ded5aeb1df27ed5d039a2034cd69a96/msgpack-0.6.0-cp27-cp27mu-manylinux1_x86_64.whl#sha256=8d0af8d64198e4b4f942a15ea9cb0dd9c4a0bd3e4e2ba57425e108bdbd4c3a0f (from -r /tmp/pipenv-3B8qWq-requirements/pipenv-gl3LBE-requirement.txt (line 1)):', '        Expected sha256 102802a9433dcf36f939b632cce9dea87310b2f163bb37ffc8bc343677726e88', '        Expected     or 64abc6bf3a2ac301702f5760f4e6e227d0fd4d84d9014ef9a40faa9d43365259', '        Expected     or 72259661a83f8b08ef6ee83927ce4937f841226735824af5b10a536d886eeb36', '        Expected     or 85f1342b9d7549dd3daf494100d47a3dc7daae703cdbfc2c9ee7bbdc8a492cba', '        Expected     or 8ce9f88b6cb75d74eda2a5522e5c2e5ec0f17fd78605d6502abb61f46b306865', '        Expected     or 9936ce3a530ca78db60b6631003b5f4ba383cfb1d9830a27d1b5c61857226e2f', '        Expected     or cb4e228f3d93779a1d77a1e9d72759b79dfa2975c1a5bd2a090eaa98239fa4b1', '             Got        8d0af8d64198e4b4f942a15ea9cb0dd9c4a0bd3e4e2ba57425e108bdbd4c3a0f']
```

It looks like the original release for `0.6.0` happened on 2018-11-30 but some of the files were updated on 2018-12-04. I looked around but did not see any explanation for the new packages. Since `pipenv` is throwing a warning about tampering I thought I should check:
> someone may have tampered with them

![selection_100](https://user-images.githubusercontent.com/482948/49524196-4fe5ed80-f879-11e8-8f77-477524f28a56.png)

**Comment by methane** [comment]
I didn't *update* anything.  PyPI doesn't allow overwriting same package.
I *added* manylinux1 wheels at 2018-12-04. (See #335)

Your lock file contains all hashes *before* I added manylinux1 wheels.
And you download manylinux1 wheel now.  It's hash is not in your lock file.

You need to update your lock file, or you can use PIP_NO_BINARY option.
https://github.com/pypa/pipenv/issues/1430#issuecomment-430834950

**Comment by ntrepid8** [comment]
Thanks for the response. That makes sense.
