### ISSUE TITLE
serialization of 64-bit floats broken on iOS ARM 32-bit

### ISSUE THREAD

**Issue by ivytin** [msgpack/msgpack-python#339]
The same [problem](https://github.com/msgpack/msgpack-c/pull/270/commits/2f9912a012391ecb967bfa951b82190b425cefab) has been solved  in msgpack-c, but still exists in msgpack-python.

**Comment by methane** [comment]
iOS 32bit is still alive?

**Comment by methane** [comment]
Do they use megpack-python?
How?

**Comment by ivytin** [comment]
In my case, we made a python interpreter for mathematic calculation on ios devices, and use msgpack to translate data if online calculation needed.
