### ISSUE TITLE
msgpack.fallback.Packer.pack is not thread safe

### ISSUE THREAD

**Issue by yaccz** [msgpack/msgpack-python#341]
msgpack.fallback.Packer.pack is not thread safe while the cython implementation seems to be by acquiring GIL. This may be a difference at least worth mentioning somewhere.

**Comment by jfolz** [comment]
The GIL does not make code thread-safe. It merely ensures that reference-counting is done correctly. AFAIK neither implementation is thread-safe.

**Comment by methane** [comment]
Like many classes in Python stdlib, it's is not thread safe unless it's documented as "thread safe"
explicitly.  Even if Cython implementation is thread safe (I don't confirmed it yet), it's implementation detail.
You must use Cython implementation in single thread, or use mutex too.
