### ISSUE TITLE
SignalR - Websocket + MessagePack (JSON)

### ISSUE THREAD

**Issue by thzois** [msgpack/msgpack-python#350]
Hello,

I have configured my SignalR server (in .NET core) to use MessagePack for the hub and I am using Websocket in Python for the communication. Everything works perfectly if I specify as protocol (json) in handshake and I am not using MessagePack. 
I am also able to print the message in response.

```
def encode_json(obj):
    return json.dumps(obj) + chr(0x1E)

def ws_on_message(ws, message: str):
     print(message)

def ws_on_open(ws):
    ws.send(encode_json({
        "protocol": "json",
        "version": 1
    }))

    x = encode_json({
        "type": 1,
        "target": "SendMessage",
        "arguments": ["Hello", "World"]
    }) 
    
    ws.send(x)
```
When I try to use MessagePack, I am specifying in the handshake as protocol (messagepack) and I use packb and unpackb. However, when I try to print the response `error from callback <function ws_on_message at 0x109641c80>: unpack(b) received extra data.`. The communication regardless the printing of the response, terminates unexpectedly. 

```
def encode_json(obj):
    return json.dumps(obj) + chr(0x1E)

def ws_on_message(ws, message: str):
    #print("Received from SignalR: ", msgpack.unpackb(message, raw=False))
    print(message)

def ws_on_open(ws):
    ws.send(encode_json({
        "protocol": "messagepack",
        "version": 1
    }))

    #Try 1
    x = encode_json({
        "type": 1,
        "target": "SendMessage",
        "arguments": ["Hello", "World"]
    })

   #Try 2
    x = {
        "type": 1,
        "target": "SendMessage",
        "arguments": ["Hello", "World"]
    }
    ws.send(msgpack.packb(x, use_bin_type=True))
```

**Comment by methane** [comment]
I don't want to pay my time and energy to learn SignalR.
You should show:

* dump of received binary data (hex or Python's bytes repr).
* pointer to document of format SignalR sents.

Please don't waste OSS maintainer's time.  It's limited resource.
If you can not write complete issue report, use user's community instead of issue tracker.
