### ISSUE TITLE
 s = s.encode('utf8')  UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 180: surrogates not allowed

### ISSUE THREAD

**Issue by Ibtiheel** [msgpack/msgpack-python#351]
I faced this problem while running the code,it's my first time using tensorflow and i'm not familiar with it :(  could anyone help me !

**Comment by methane** [comment]
It seems not relating to this project.  Don't use issue tracker to ask help.
There are only one maintainer here.  You're sending spam mail to the maintainer.
And I don't know about tensorflow.

Use some community [1] or Stackoverflow.  There are many experts.  Some of them may help you.
[1]: https://www.python.org/community/
