### ISSUE TITLE
Building cmsgpack for alpine

### ISSUE THREAD

**Issue by pdscopes** [msgpack/msgpack-python#354]
I'm using msgpack in a python alpine docker image and I would like to use `msgpack._cmsgpack` rather than `msgpack.fallback` for the obvious performance benefits.

I install msgpack using `pip install msgpack>=0.6.1`. If I install msgpack on a debian based linux server `msgpack._cmsgpack` is available.

How would I go about making `msgpack._cmsgpack` available in alpine?

**Comment by methane** [comment]
No special requirement.  You need C++ compiler and Python header files.
