### ISSUE TITLE
Disabling garbage collector

### ISSUE THREAD

**Issue by seanthegreat7** [msgpack/msgpack-python#355]
In the "Note about performance" part of the read me, you mention we can disable garbage collector while unpacking large items. I have three questions.

1- Should I enable it afterwards?
2- How big of a difference it makes?
3- How big of a message is considered big in your context?

**Comment by methane** [comment]
> 1- Should I enable it afterwards?

Generally yes.  But it's up to you.



> 2- How big of a difference it makes?

Vary on data.



> 3- How big of a message is considered big in your context?

Thousands or millions of dicts or lists.

If you are really care it, you should benchmark with your data.
You can see how log gc taokes by `gc.set_debug(gc.DEBUG_STATS)`.
