### ISSUE TITLE
ValueError: 22035 exceeds max_array_len(576)

### ISSUE THREAD

**Issue by playcode001** [msgpack/msgpack-python#358]
ValueError: 22035 exceeds max_array_len(576)

**Comment by methane** [comment]
It's expected error for wrong data.

**Comment by playcode001** [comment]
It seems that it is not a problem with the data format.

**Comment by playcode001** [comment]
![image](https://user-images.githubusercontent.com/5078044/58425386-445add00-80cc-11e9-8e4c-c183d5a50c95.png)
The same data structure can be parsed using other languages

**Comment by jfolz** [comment]
This is a measure against DOS attacks. The exception indicates that your serialized message is 576 bytes long, but it apparently contains an array of length 22035. You can set `max_array_len`, but you should most likely fix whatever code produced that message.
