### ISSUE TITLE
OS X wheels

### ISSUE THREAD

**Issue by Suor** [msgpack/msgpack-python#367]
Are there plans to add them?

**Comment by methane** [comment]
I uploaded wheel for Python 3.7 on macOS 10.14.  Is it enough for you?
https://pypi.org/project/msgpack/#modal-close

I don't have CI to build wheel for macOS yet.

**Comment by Suor** [comment]
We plan to use msgpack in [dvc](https://github.com/iterative/dvc/), where we support all non-dead Python versions, e.g. 2.7, 3.5, 3.6, 3.7. We might ignore 2.7 as it ends soon, but not the other ones. We need wheels because many of our users do not have build tools installed and we try to make install as easy as possible. 

Wheels for all Python/OS combination could be built and deployed using Travis, this is [what we do](https://github.com/iterative/dvc/blob/master/.travis.yml).

**Comment by methane** [comment]
I had uploaded more wheels.  I built them at https://github.com/methane/msgpack-wheels
