### ISSUE TITLE
[bug] msgpack.packb(data).decode() fails. It appears bytes are windows-1253 encoding, but method docblock says default is utf-8. decodewindows-1253") works

### ISSUE THREAD

**Issue by idchlife** [msgpack/msgpack-python#368]
I suspect this is a bug, since normal behaviour with .decode() throws error about encoding problem (cannot be decoded to "utf-8").

**Comment by methane** [comment]
msgpack is binary format.  It is not encoded text.

**Comment by idchlife** [comment]
@methane 	so there is no way to properly convert binary from msgpack to string and back to unpack? To store it as string somewhere.

**Comment by methane** [comment]
Yes.  If you need unicode string, You should use JSON.
msgpack is *binary* format.

**Comment by idchlife** [comment]
@methane 	thanks!

**Comment by jfolz** [comment]
It **is** like JSON. And like JSON, you have to use the appropriate function to decode the message. `bytes.decode` attempts to decode a binary string into unicode using a given character encoding scheme (usually UTF-8). `json.loads` decodes a JSON message given as `bytes` into a Python object. `msgpack.unpackb` does the same for msgpack.

**Comment by idchlife** [comment]
@jfolz 	but there is no way to do "json.dumps" in msgpack, is it?

**Comment by jfolz** [comment]
The equivalent is `msgpack.packb`. Just like `json.dumps` it produces a plain Python `bytes` object that contains the serialized message. `bytes` doesn't know anything about either msgpack or JSON. It can only be unpacked by `msgpack.unpackb`.
