### ISSUE TITLE
Implement restricted profiles

### ISSUE THREAD

**Issue by traverseda** [msgpack/msgpack-python#398]
As mentioned in the spec: https://github.com/msgpack/msgpack/blob/master/spec.md#profile

**Comment by methane** [comment]
Have you really read the spec?
It is just an idea and there is nothing concrete enough to implement.

**Comment by traverseda** [comment]
I've actually implemented messagepack in pure python, in an attempt to get more control over the typing. Unfortunately it's not very fast, and I know that even after optimizing it will not be as fast as this is.

While it is under the "future discussions" part of the text, are you sure there's nothing concrete enough to implement? Basic restrictions, like "don't serialize/de-serialize this type, instead pass it to a hook", are a major part of profiles as described in that spec.
