### ISSUE TITLE
Add object_kwargs_hook

### ISSUE THREAD

**Issue by randallpittman** [msgpack/msgpack-python#400]
Just an idea, no sure if you think it's worthwhile.

Add an unpacking option `object_kwargs_hook` or `object_kv_hook` to support directly unpacking a map into a callable that takes `key: value` argument, such as a dataclass.

The workaround is just using `object_hook=lambda x: MyDataclass(**x)`, which isn't too bad, so this isn't a major need, but then again perhaps it is low-hanging fruit too.

**Comment by methane** [comment]
Thanks for idea.  But I don't like add more option only for it.

**Comment by randallpittman** [comment]
Sure. Thanks for considering it.
