### ISSUE TITLE
Advanced unpacking control example broken

### ISSUE THREAD

**Issue by pryg-skok** [msgpack/msgpack-python#401]
Hi,

It seems that example of advanced unpacking control is no working with latest git (and pypi also): https://github.com/msgpack/msgpack-python#advanced-unpacking-control

For example `unpacker.skip(bytestream.write)` do not have input parameters. 

Also I wonder is it possible to unpack part of bytestream (by skipping some headers) and then unpack another part of same message in different part of code by accessing to the same unpacker object? It seems that in current implementation it's not possible and all that I can do is to unpack origin bytestream again and again with different parameters (fields of bytestream I need to access to). Probably it could be achievable if `.skip()` method return skipped part of bytestream, or unpacker class store unpacked fields with data and bytestream within itself and unpack bytestream when one need to access fields from there.

**Comment by methane** [comment]
> It seems that example of advanced unpacking control is no working with latest git (and pypi also): https://github.com/msgpack/msgpack-python#advanced-unpacking-control

Thanks for pointing it out.



> Also I wonder is it possible to unpack part of bytestream (by skipping some headers) and then unpack another part of same message in different part of code by accessing to the same unpacker object?

First of all, you are trying bad design.  Any other **popular** JSON or msgpack library provides such feature?  These formats are not designed for random access.

You can use `Unpacker.feed()`, `Unpacker.skip()`, `Unpacker.tell()`, and `Unpacker.read_bytes()`.
If you can achieve your goal with these methods, I think the msgpack is not right choice for you.
