### ISSUE TITLE
Allow int map keys with strict_map_key

### ISSUE THREAD

**Issue by HelloZeroNet** [msgpack/msgpack-python#410]
```py
import msgpack

raw = msgpack.packb({1234: "ok"})
msgpack.unpackb(raw)
> ValueError: int is not allowed for map key
```

Is there any reason not to allow int as map keys?

**Comment by methane** [comment]
It is described in README.
https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10

**Comment by HelloZeroNet** [comment]
I would assume it's the hashdos only happens with complex types, can you please give more detail on the issue?

**Comment by methane** [comment]
> I would assume it's the hashdos only happens with complex types,

No.  Only str and bytes have randomized hash.  int key is dangerous.  It's very easy to conflict lower bits of the int keys.

```
>>> for i in range(42, 10000, 1024):
...     print(hash(i) % 1024)
...
42
42
42
42
42
42
42
42
42
42
```

**Comment by methane** [comment]
> After some research for me it seems hash dos happens when you have multiple keys with the same hash in the dict.

At least, conflicting lower bits is enough to slow down dict.  I'm not surre it is safe for hashdos.
Do you have any evidence int is safe?  Any security experts said int is safe?

**Comment by HelloZeroNet** [comment]
I have not found any information about hashdos and int keys
Based on a quick test: https://gist.github.com/HelloZeroNet/394e653870d87cb862353b6108e84832

Key access speed there is some difference (~50% slower) with 97k keys with the same order bit, but it does not seems like a DoS attack vector:

```
Dict with same lower bits:
- Access: 0.642s
- Random access: 2.178s
- Msgpack unpack: 1.407s
- Msgpack unpack (fallback): 3.679s
Dict with different lower bits:
- Access: 0.466s
- Random access: 1.881s
- Msgpack unpack: 1.174s
- Msgpack unpack (fallback): 3.628s
Dict with string keys:
- Access: 0.416s
- Random access: 1.324s
- Msgpack unpack: 3.216s
- Msgpack unpack (fallback): 3.962s
```

**Comment by methane** [comment]
> I have not found any information about hashdos and int keys.

It implies hash(int) is not designed for hashdos safe.  Only str and bytes are hashdos safe.

> Based on a quick test: 

It is very bad thinking.   You should not think something is safe with such "quick test".
If you want to assert hash(int) is hashdos safe, you need to survey implementation and prove it is mathematically safe.

Hint: hashdos is caused by long chain of conflict.  Attacker knows hash(int) and dict (hash table) implementation. So what you need to prove is the upper bound of length of chain of conflict.
