### ISSUE TITLE
loose of compatibility to 0.6.2 and not data validation Dict[int, int]

### ISSUE THREAD

**Issue by ChameleonRed** [msgpack/msgpack-python#411]
I wrote encoder/decoder module some years ago using you msgpack module and I found that version 1.0.0 is broken compatibility with previous version.

My enconder/decoder is serializing Python objects - now can not do it.

I prepare some testing code which show problem:

```
import msgpack

x = {
    1: 1
}

s = msgpack.dumps(x)
y = msgpack.loads(s)
```

Before version 1.0.0 there was not problem and I could use such dict to pack/dump Python object.
I was using it to:

```
__MODULE_NAME = 1
__CLASS_NAME = 2
...

encodes {
__MODULE_NAME: 'MyClass',
__CLASS_NAME  'my_module',
...
}
```
Now it not works because decoder not works.

**Comment by ChameleonRed** [comment]
```
Traceback (most recent call last):
  File "C:/Users/Cezary Wagner/PycharmProjects/bug-msgpack/int_dict.py", line 8, in <module>
    y = msgpack.loads(s)
  File "msgpack\_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key
```

**Comment by ChameleonRed** [comment]
In version 0.6.2 there is not problem:

```
import msgpack

x = {
    1: 1
}

s = msgpack.dumps(x)
y = msgpack.loads(s)

print(x)
```

Gives:

```
{1: 1}
```

**Comment by zwn** [comment]
That is expected. Why don't you take a look at the readme file?

https://github.com/msgpack/msgpack-python/blob/master/README.md#major-breaking-changes-in-msgpack-10

**Comment by ChameleonRed** [comment]
BTW: 0.6.2 `Dict[int, Any]` was very fast and slim since `int` is shorter than `str` I think.

**Comment by ChameleonRed** [comment]
First of all fundamental question. I rather expert in programming.

Why I can pack **invalid dict** and can not unpack **invalid dict** that is wrong idea I think since I do not have exception during packing - it lead to serious problems including data lost?

It should be not allowed even there if default is `strict_map_key=False'.

I read https://github.com/msgpack/msgpack-python/blob/master/README.md#major-breaking-changes-in-msgpack-10 but not found any sentence explaining problem. Maybe I am very bad in reading or understanding - I try to read this **three times** and finnaly found:

> Default value of strict_map_key is changed to True to avoid hashdos. You need to pass strict_map_key=False if you have data which contain map keys which type is not bytes or str.

What is `hashdos`?

**Comment by ChameleonRed** [comment]
BTW: I like your library and I am using it at least 3 years I think ...

**Comment by ChameleonRed** [comment]
I tested this code and it probably works but - it is very weird (as I said **it should not pack what can not be unpacked** with same options - I think that is good idea to raise exception at pack).

I will test it tomorrow on about 1 000 000 scale object serialization.

```
import msgpack

x = {
    1: 1
}

s = msgpack.dumps(x)
y = msgpack.loads(s, strict_map_key=False)

print(x)
```

I think that **such syntax** is valid - pack/unpack has same options that is my suggestion. You should also give hint in documentation that someone should do this - it will stop reporting bugs very fast I think.

```
import msgpack

x = {
    1: 1
}

s = msgpack.dumps(x, strict_map_key=False)
y = msgpack.loads(s, strict_map_key=False)

print(x)

**Comment by ChameleonRed** [comment]
Tank you for support and this great library :)

**Comment by zwn** [comment]
The dictionary you are unpacking can come from an adversary trying _hashdos_ your computer. The unpacking function does not know it is your, safe, dictionary - you have to say so by using the parameter. See also #410 for more explanation.

**Comment by ChameleonRed** [comment]
No, idea what is **hashdos** maybe kind of attack/collision but why it is related to `int` not to `str` - no idea - something wrong is with this concept or I do not understand internals of Python?

I often optimize programs to the limits so this subject is little interesting to me but I do not see here why 1024 is **magic number** for dictionaries or hashes and why `int` is different to `str` (both can have same magic number).

BTW: I am not feel scary reading my own files - msgpack can be used for internal communication or data storage. External communication need different design of course but still not idea why `int` is wrong? 

Let me explain!

#410 - I just imagine that low bit string can slow down dict operation but really?
It now works at all in my case.

Let's think from start!

```
len({hash(x) for x in range(1000000)})
# all are unique = 1000000
```

Of course set of division rests of 1024 is 1024. It is normal.

```
len({hash(x) % 1024 for x in range(1000000)})
# must be 1024 since it is rest of whole number but what does mean?
```

I can say that set of division rests of 333 will be 333 but is it have some reason.

So:

```
len({hash(x) % 333 for x in range(1000000)})
# must be 333 since it is rest of whole number but what does mean?
```

Finally:

```
len(set(hash(x) % 1024 for x in range(42, 10000, 1024)))
# len is 1 - why because we use primes 2 * 3 * 7 in hash maybe?
# that is special data set not normal
```

Normally:

```
len(set(hash(x) % 1024 for x in range(10000)))
# it is 1024 - I will use only such range to speed up probably also
```

Do you think it is big problem problem with use 2 * 3 * 7 primes for hash (it ok - not the best but fast) and 1024 (number of buckets in dict?)?

I can be in special case but normally?

**Comment by ChameleonRed** [comment]
Still not understand why 1024 is so magic - maybe I will study python code to report some bug in implementation - I do not think that Dict[int, Any] is limited to 1024 buckets in Python 3.x but maybe.

Why is it not 2^8 or 2^16 or 2^32 since it is more natural for computers - maybe you were found how to speed up little Python.

**Comment by methane** [comment]
> No, idea what is **hashdos** maybe kind of attack/collision but why it is related to `int` not to `str` - no idea - something wrong is with this concept or I do not understand internals of Python?

hash of the str and bytes are randomized per process.  So attacker can not know hash value for these types.  On the other hand, attacker can know hash(int).
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED


> Still not understand why 1024 is so magic

1024 was just an example.  CPython's dict implementation uses hash table which size is 2^n.
