### ISSUE TITLE
Should `pip install` donwload msgpack 1 for Python 2?

### ISSUE THREAD

**Issue by pierreglaser** [msgpack/msgpack-python#413]
Hi,
Now that Python 2 is officialy unsupported by msgpack, should  `setup(...)` include `python_requires=">=3"`? Otherwise, running `pip install msgpack` on Python 2 installs an incompatible version.

Encountered this while working on `joblib's` CI:
joblib/joblib#1015

**Comment by methane** [comment]
msgpack works with Python 2.

As far as I can see, the CI is failing with`ValueError: <type 'tuple'> is not allowed for map key`

This doesn't relating to Python 2.  See changelog.
https://github.com/msgpack/msgpack-python#major-breaking-changes-in-msgpack-10

Tuples are not allowed by default.  You need to specify `strict_map_key=False`.
