### ISSUE TITLE
c++ packed data leads to unpack error in python

### ISSUE THREAD

**Issue by RGring** [msgpack/msgpack-python#415]
Hi,
Following situation.
Node1: Packing an object with msgpack in c++ and sending the data.
Node2: Receiving the data and unpacking in python (msgpack.unpackb(payload)). Problem: ValueError gets raised with message "Unpack failed: incomplete input".

I discovered that I only get the Exception e.g, when I pack data with a floating point members. But it also occurs, when I have nested objects.

When I unpack the data in C++, it works fine.

Thanks in advance!

**Comment by methane** [comment]
Any reproducible code?
Unless you give me a reproducible example, I assume just you use msgpack-python in wrong way.

**Comment by RGring** [comment]
After trying to provide reproducable code, I figured, that it was not a problem of msgpack-python. Sorry for the falsely report.
