### ISSUE TITLE
Killed by OOM killer when unpacking invalid data with use_list=False

### ISSUE THREAD

**Issue by garyvdm** [msgpack/msgpack-python#417]
This uses up all the memory, and the process gets killed by the OOM killer:

```
msgpack.unpackb(b'\x9f\xfdt\xf7\xddt\xff\xfd\xbd', use_list=False)
```
The data is invalid msgpack data. If you run `use_list=True`, it correctly raises a `UnpackValueError`, but takes a long time to run.

**Comment by methane** [comment]
Which version do you use?  Current version enables the protection of huge preallocation already.

```
>>> msgpack.unpackb(b'\x9f\xfdt\xf7\xddt\xff\xfd\xbd', use_list=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
    ret = unpack_construct(&ctx, buf, buf_len, &off)
ValueError: 15 exceeds max_array_len(9)
```

**Comment by garyvdm** [comment]
Ah. This was an old project for which I'd forgotten to do the `msgpack-python` -> `msgpack` upgrade.  Thanks.
