### ISSUE TITLE
Support little endian

### ISSUE THREAD

**Issue by stalkerg** [msgpack/msgpack-python#419]
Hello, main C library supports chooses between little endian and big endian just by define like MSGPACK_ENDIAN_LITTLE_BYTE. 
How I can do the same for msgpack-python? 

Thanks.

**Comment by methane** [comment]
See here
https://github.com/msgpack/msgpack-python/blob/692e0ee8ff66686dd423aae69b248b67c3bf9ed4/setup.py#L85-L88

**Comment by stalkerg** [comment]
@methane it affects only packing, I need decoding little-endian message pack too. 
I know, official standard works with BigEndian but in my case is not true. (
