### ISSUE TITLE
Incompatibility with Python 3.8 breaks many packages

### ISSUE THREAD

**Issue by skuzzymiglet** [msgpack/msgpack-python#424]
`msgpack` issues cause errors in serveral places:

+ pip install
+ Neovim Python host
+ YouComplete
+ many others

See https://stackoverflow.com/questions/61227373/pip-msgpack-error-while-installing-requirements and https://pastebin.com/aTTwyrML for info on pip failing.

I think this issue is critical as it causes breakage across the Python ecosystem

**Comment by jfolz** [comment]
https://pypi.org/project/msgpack ?????

**Comment by skuzzymiglet** [comment]
Oh, seems to be fixed now. Thank you so much
