### ISSUE TITLE
Cannot serialize the object of class

### ISSUE THREAD

**Issue by AtticusYang** [msgpack/msgpack-python#431]
i want to serialize the object of self defined class, but give an error tips, should i define a  serialize method?

```
class Person(object):
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __str__(self):
        return 'id: {}, name:{}'.format(self.id, self.name)

person = Person(100, 'charles')
print(person)

```

error tips,
    raise TypeError("Cannot serialize %r" % (obj, ))
TypeError: Cannot serialize <__main__.Person object at 0x7f8984b5e160>

**Comment by methane** [comment]
msgpack is JSON-like format.
Like JSON, msgpack is not support directly serializing any custom object.
If you want it, you should use pickle.

**Comment by AtticusYang** [comment]
> msgpack is JSON-like format.
> Like JSON, msgpack is not support directly serializing any custom object.
> If you want it, you should use pickle. 
thank u.

i think there is a situation that RPC call between two service need to serialize/unserialize the object of class.

**Comment by jfolz** [comment]
This use case is mentioned in the readme.
And this is an issue tracker, not stackoverflow.

**Comment by AtticusYang** [comment]
@jfolz ,thank u
