### ISSUE TITLE
Pure-Python fallback doesn't support the "strict_map_key" option

### ISSUE THREAD

**Issue by rspeer** [msgpack/msgpack-python#437]
I encountered confusing errors in msgpack that implied that it didn't support the `strict_map_key` option, though I know it was introduced (and required in some situations) in msgpack 1.0, and I could confirm that I had msgpack 1.0.

The reason turns out to be that I didn't have the `python3-dev` package installed _at the time that I installed msgpack_, so it was using the pure-Python version in `fallback.py`, which doesn't have the same API because it doesn't understand the `strict_map_key` option.

My expected behavior is that the fallback implementation should support all the same arguments as the C implementation; or, if the fallback implementation isn't intended to be used, that installation should fail instead of installing a version that uses the fallback installation.

**Comment by jfolz** [comment]
Could you be a bit more specific about what broke?
Python fallback [raises `ValueError`](https://github.com/msgpack/msgpack-python/blob/8fb709f2e0438862020d8810fa70a81fb5dac7d4/msgpack/fallback.py#L665) if `type(key) not in (unicode, bytes)`.
C [raises `ValueError`](https://github.com/msgpack/msgpack-python/blob/8fb709f2e0438862020d8810fa70a81fb5dac7d4/msgpack/unpack.h#L195) if `!PyUnicode_CheckExact(key) && !PyBytes_CheckExact(key)`.
Behavior should be identical.

**Comment by rspeer** [comment]
The difference is that the Python fallback does not accept the keyword argument `strict_map_key`, which is required to parse non-strings as dictionary keys in the C version.

**Comment by rspeer** [comment]
The code `msgpack.load(filename, raw=False, strict_map_key=False)` thus does not work on the pure Python version.
