### ISSUE TITLE
py3: TypeError: can not serialize 'range' object

### ISSUE THREAD

**Issue by clor09** [msgpack/msgpack-python#438]
As a startup, i tried the examples in the readme.
when i do

`msgpack.packb(range(5), use_bin_type = True)`

it just told that:

> TypeError: can not serialize 'range' object

both under py3.6+msgpack0.5.6  &  py3.8+msgpack1.0r.  but under py2 everything seems ok.. this may conflict with the `py2 incompitible`? or am i do something wrong?

**Comment by jfolz** [comment]
https://docs.python.org/3.0/whatsnew/3.0.html#views-and-iterators-instead-of-lists
