### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Xaroth** [msgpack/msgpack-python#445]
Hi,

I'm running into some issues with packing/unpacking DateTime objects, that has since been fixed in #435 . However, there has been no release since then (and there has been no release since Feb).
Would it be possible to release a new minor version so that these fixes can be pushed via pypi?

**Comment by methane** [comment]
> I'm running into some issues with packing/unpacking DateTime objects, that has since been fixed in #435 . However, there has been no release since then (and there has been no release since Feb).

I am not sure what are you waiting. #435 make pure Python packer strict. As far as you are using msgpack-python in right way, nothing changed after #435. You shouldn't wait new release. You can just fix your program. Don't you?

Anyway, I will release next version in this year for Python 3.9 binary wheels.

**Comment by methane** [comment]
Released.
