### ISSUE TITLE
Add the possibility to automate the datetime <-> Timestamp encoding/decoding

### ISSUE THREAD

**Issue by douardda** [msgpack/msgpack-python#446]
Unless I'm wrong, supporting the encoding and decoding of (tz-aware) datetime objects requires to handle the datetime -> Timestamp and Timestamp -> datetime conversions by hand.

During the packing, this can be quite easily done using the `default` callback. But for the unpacking step, there is no obvious way of doing this (that I am aware of at least).

Ideally, there should be a feature flag (like `use_bin_type` for example) to enable the automatic conversion of (tz-aware) datetime objects to Timestamp  (and the other way around) in the pack()/unpack() functions (and the Packer and Unpacker classes as well).

Hopefully this does make sense...

Thanks,
David

**Comment by methane** [comment]
You are wrong.

https://github.com/msgpack/msgpack-python/blob/8fb709f2e0438862020d8810fa70a81fb5dac7d4/msgpack/fallback.py#L172-L178

https://github.com/msgpack/msgpack-python/blob/8fb709f2e0438862020d8810fa70a81fb5dac7d4/msgpack/fallback.py#L778-L782

**Comment by douardda** [comment]
Ah yes. Maybe it would be nice this feature to be documented. On rtd at least, most of the arguments Packer and Unpacker accept are undocumented.

The argument is ntoe even visible for the Packer:

![image](https://user-images.githubusercontent.com/1496354/101139028-3a932d80-3611-11eb-8e61-a9289168e8db.png)


At least for the Unpacker it is listed in the signature, but not in the argument list below:

![image](https://user-images.githubusercontent.com/1496354/101139194-7b8b4200-3611-11eb-8cd7-b325a4a1931f.png)

But that's another issue, obviously.
