### ISSUE TITLE
Make the documentation consistent

### ISSUE THREAD

**Issue by douardda** [msgpack/msgpack-python#447]
Currently, the documentation available on rtd for Packer and Unpacker classes in inconsistent, not all the arguments are  documented in the **Paramaters** section, eg.: 
![image](https://user-images.githubusercontent.com/1496354/101140511-5d264600-3613-11eb-9863-a2a8b4eaeaea.png)

where we can see that the `datetime` argument is missing in the list.

For the `Unpacker` class,  `timestamp`, `list_hook` and `ext_hook` arguments are not documented int the **Parameters** list.

**Comment by methane** [comment]
fixed
