### ISSUE TITLE
Error: unpack failed due to incomplete input

### ISSUE THREAD

**Issue by GabrielaGuedes** [msgpack/msgpack-python#449]
I have a script that stores in a .msgpack file an array of dictionaries, incrementing it each time, something like this:
```python
with open("my_file.msgpack", "rb") as outfile:
  byte_data = outfile.read()
data_loaded = msgpack.unpackb(byte_data)

data_loaded += another_dict
with open("my_file.msgpack", "wb") as outfile:
  outfile.write(msgpack.packb(data_loaded))
```
This is done around 30k~40k times, so the array finishes with almost 40k dictionaries. But at some point, the execution just stops due to the following error when trying to open the file to read:
```
Traceback (most recent call last):
  File "my_file.py", line 5, in <module>
    data_loaded = msgpack.unpackb(byte_data)
  File "msgpack/_unpacker.pyx", line 206, in msgpack._cmsgpack.unpackb
ValueError: Unpack failed: incomplete input
```

What is happening? Does the file get corrupted?

**Comment by methane** [comment]
> What is happening? Does the file get corrupted?

I don't know. Maybe the file is corrupted. But I don't know why.
Reproducible example is needed to say anything.
