### ISSUE TITLE
Release 1.0.2 missing

### ISSUE THREAD

**Issue by fabaff** [msgpack/msgpack-python#454]
The tarball for the 1.0.2 release is not available. The Fedora and the Alpine Linux package are both using the source from here.

Could you please publish it in addition to the PyPI release? Thanks

**Comment by fabaff** [comment]
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1906739

**Comment by methane** [comment]
Thank you. I uploaded it to PyPI.

**Comment by fabaff** [comment]
Thank you

**Comment by fabaff** [comment]
Sorry, I was talking about the [releases on GitHub](https://github.com/msgpack/msgpack-python/releases). PyPI is fine.

**Comment by methane** [comment]
I don't use GitHub release.

**Comment by zwn** [comment]
When you create a tag, it appears as a release by itself. I guess what @fabaff is asking for is a git tag for 1.0.2.

**Comment by methane** [comment]
Oh, thank you. I pushed v1.0.2 tag.
