### ISSUE TITLE
Does msgpack use the Cython version by default?

### ISSUE THREAD

**Issue by laike9m** [msgpack/msgpack-python#455]
In the doc there's the [following section](https://github.com/msgpack/msgpack-python#pure-python-implementation):

> ## Pure Python implementation
> The extension module in msgpack (msgpack._cmsgpack) does not support Python 2 and PyPy.
> But msgpack provides a pure Python implementation (msgpack.fallback) for PyPy and Python 2.
> Since the **pip uses the pure Python implementation**, Python 2 support will not be dropped in the foreseeable future.

I'm a bit confused by this. If pip uses the pure Python implementation, how do I install and enable the Cython version?

**Comment by methane** [comment]
Oh, you are totally misunderstanding.

It doesn't mean "pip installs pure Python version when `pip install msgpack`".

pip **uses** msgpack. And pip bundles msgpack without extension module.
https://github.com/pypa/pip/tree/master/src/pip/_vendor/msgpack

So I decided that pure Python implementation supports what pip supports.

Note that pip is planning to drop Python 2 support. After that, msgpack pure Python will drop it too.

**Comment by laike9m** [comment]
Got it, thanks. Looks like a low hanging fruit to make it more clear. I'll create a pr if yt don't mind.
