### ISSUE TITLE
How can I decode data having binary string in it?

### ISSUE THREAD

**Issue by HanlinGao** [msgpack/msgpack-python#457]
I used `msgpack.loads(f.read(...))` to get the unpacked object, but when I tried to print it, lots of binary data occurred.

Then I tried to print the type of the unpacked object, it showed it was a list, and the first element was a dictionary. But, still, I cannot print the entire dictionary by `print(mydict)`.

So, I just used a `for` loop to print each key and each corresponding value. This time the key was finally readable, but the corresponding value was still not since it was another dictionary including binary strings.
I am very confused about this issue and the data is not encoded by myself. Do you have any suggestion that I can decode such msgpack file?

**Comment by methane** [comment]
msgpack can encode and decode binary data. So getting binary by `msgpack.loads()` is not an issue.
