### ISSUE TITLE
BufferFull exception followed up by a UnicodeDecodeError exception

### ISSUE THREAD

**Issue by liranbg** [msgpack/msgpack-python#462]
Hey,

I have a client/server architecture whereas the server is a Golang based, send msgpack messages over unix socket and a Python client that feed a buffer while reading messages from a socket. The server, might send non utf8 input values as `string` (go) and not as `[]byte`. that means, these values are failed to be decoded when we use `Unpacker(raw=False)`.

What happens is, an exception is being thrown during decoding (expected)

```python
Exception caught while serving "'utf-8' codec can't decode byte 0xd3 in position 4: invalid continuation byte": Traceback (most recent call last):
  File somefile.py", line 131, in listen
    incoming_message = next(unpacker)
  File "msgpack/_unpacker.pyx", line 518, in msgpack._cmsgpack.Unpacker.__next__
  File "msgpack/_unpacker.pyx", line 443, in msgpack._cmsgpack.Unpacker._unpack
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 4: invalid continuation byte
``` 

The issue, from now on, the unpacker, which is being initialized once, is now considered 💀  as it is not being able to unpack any message after it hits the UnicodeDecodeError exception.  but that is not just the case, every request, *expands* unpack message a bit more until it hits 

```python
Exception caught while serving "": Traceback (most recent call last):
  File somefile.py", line 131, in listen
    unpacker.feed(buf_memoryview[:max])
  File "msgpack/_unpacker.pyx", line 422, in msgpack._cmsgpack.Unpacker.feed
  File "msgpack/_unpacker.pyx", line 446, in msgpack._cmsgpack.Unpacker.append_buffer
msgpack.exceptions.BufferFull
``` 

Way to reproduce
1. create packer, set as server
2. create unpacker, set as client
3. create a message on the server, make sure it contains some non-utf8 (`\xdb`), send to client
4. client try to read, explodes with `UnicodeDecodeError`
5. server keep sending messages, 4 hits `msgpack.exceptions.BufferFull`

Note: Tested on both 1.0.2, 0.6.1 versions.

Suggestion how to fix: when hitting an exception - reset internal buffers to avoid ever-growing buffers

How I fixed it: reinitiated `unpacker` on each exception, e.g.:

```python
unpacker = msgpack.Unpacker(raw=False)
while True
  # ... read from socket
  socket.recv_into(buf)
  try:
    unpacker.feed(buf)
    msg = next(unpacker)
  except:
    unpacker = msgpack.Unpacker(raw=False)
```

**Comment by jfolz** [comment]
When you encounter an error while streaming like this, how do you recover from it? To skip a message you need to successfully decode it. In your example, how do you ensure the new `Unpacker` is fed the beginning of a message?

Bottom line: msgpack is not a suitable wire protocol. At the very least send a small header with the number of bytes in the next message.

**Comment by methane** [comment]
Fix user server.
If you can not fix your server, use `raw=True` option.

**Comment by liranbg** [comment]
> When you encounter an error while streaming like this, how do you recover from it? To skip a message you need to successfully decode it. In your example, how do you ensure the new `Unpacker` is fed the beginning of a message?
> 

Well, I dont, I simply reject the message on the client side, letting the server know something bad happened. the next message would be fed into a completely new buffer and hence is not effected.

> Bottom line: msgpack is not a suitable wire protocol. At the very least send a small header with the number of bytes in the next message. If you know how big your message is you can fill a buffer and use `unpackb`, which will actually be more efficient. The `Unpacker` copies data you feed it into its internal buffer. `unpackb` just accesses the memory directly without copying.

The message size is dynamic, and can vary from ~.1kb to 100mb. I indeed have an header telling the message size so that I could iterate while reading  from socket and feeding the msgpack.

AFAIK that is the recommended way reading from a socket.

e.g.:

```python
while message_read < message_size:
  toread = message_size - message_read
  bytes_read = self._processor_sock.recv(toread)
  if not bytes_read:
    exit(1)
  unpacker.feed(bytes_read)
  message_read += len(bytes_read)
```

am I missing something?


> Fix user server.
> If you can not fix your server, use `raw=True` option.

Nothing to fix on the server, it is a valid input.
going with a `raw=True` is what I did eventually. That being said, the error I mentioned still persist in case msgpack hits an exception for any reason it is.

**Comment by methane** [comment]
> Nothing to fix on the server, it is a valid input.

Non UTF-8 string is almost invalid. That's why it cause error by default.

See https://github.com/msgpack/msgpack/blob/master/spec.md#type-system

> String extending Raw type represents a UTF-8 string

**Comment by jfolz** [comment]
> Well, I dont, I simply reject the message on the client side, letting the server know something bad happened. the next message would be fed into a completely new buffer and hence is not effected.

How do you know that the next bytes you read from your socket were sent after you notified the server?
There are all kinds of send and receive buffers involved here. If the server just pushes data into the socket at its own pace that's a recipe for a race condition.

**Comment by liranbg** [comment]
> > Well, I dont, I simply reject the message on the client side, letting the server know something bad happened. the next message would be fed into a completely new buffer and hence is not effected.
> 
> How do you know that the next bytes you read from your socket were sent after you notified the server?
> There are all kinds of send and receive buffers involved here. If the server just pushes data into the socket at its own pace that's a recipe for a race condition.

Server awaits on client response. it does not send another message until receiving a response from its client

**Comment by methane** [comment]
Unpacker is already too complex to me. I won't make it more complicated.

**Comment by bamboosdu** [comment]
How to solve the problem of bufferfull?
