### ISSUE TITLE
unpacking data in python 3 which is packed in python2

### ISSUE THREAD

**Issue by mahadevTW** [msgpack/msgpack-python#471]
msgpack version :  `msgpack==0.6.1`
Reproducable : Yes
Hi,
We are migrating our code base to python3.
We have old data on our storage which packed in python2.
When we try to unpack old data into python3 , it gives all keys into byte format and not in Original string. 
but at the same time if we pack and unpack both in python3 it works as expected.

Code : 
in python2 
`root@master:/# python
Python 2.7.18 (default, Feb  1 2021, 15:44:42) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> data = {'hello':'world'}
>>> import msgpack
>>> b_data = msgpack.packb(data, use_bin_type=True)
>>> unpackedDict = msgpack.unpackb(b_data, raw=False)
>>> unpackedDict
{'hello': 'world'}
>>> b_data
'\x81\xc4\x05hello\xc4\x05world'
>>> 
`

Now I pickup this b_data and try to unpack into python3 :
`root@master:/# python3
Python 3.7.0 (default, Feb  1 2021, 15:25:38) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msgpack
>>> data_packed_in_py2 = b'\x81\xc4\x05hello\xc4\x05world'
>>> msgpack.unpackb(data_packed_in_py2, raw=False)
{b'hello': b'world'}
>>> data = {'hello':'world'}
>>> b_data = msgpack.packb(data, use_bin_type=True)
>>> msgpack.unpackb(b_data, raw=False)
{'hello': 'world'}
>>> 
`
I am wondering what caused this byte formatting issue.

because of this behaviour we are finding it difficult to migrate to python 3.

Want to understand how come  - `{'hello': 'world'}` became `{b'hello': b'world'}` in transition.

Any help/trick to make this compatible across python 2,3

**Comment by methane** [comment]
Read the README.

<img width="864" alt="スクリーンショット 2021-03-12 14 52 00" src="https://user-images.githubusercontent.com/199592/110898500-b43e6400-8342-11eb-8e8c-fa9d51567db0.png">

If you want to pack bytestring in Python 2 and unpack it as Unicode string in Python 3, you must use `use_bin_type=False`.

**Comment by mahadevTW** [comment]
@methane 
Thanks for inputs.
but the Data being stored on our internal storage is being packed with use_bin_type=True and , its not easy to migrate that data.

**Comment by methane** [comment]
`use_bin_type` means use "this is a binary, not a string" type for bytestring. So you must migrate your data.

```
>>> import msgpack
>>> data_packed_in_py2 = b'\x81\xc4\x05hello\xc4\x05world'
>>> t = msgpack.unpackb(data_packed_in_py2)
>>> msgpack.unpackb(msgpack.packb(t, use_bin_type=False))
{'hello': 'world'}
```

**Comment by mahadevTW** [comment]
@methane 
thanks you so much for this.
As its close to impossible for us to migrate historic old data to new.
I want to use trick where while reading back into python3.
 if data is packed in Old format, I will use pack , unpack logic to migrate selectively and operate on data in memory
 I don't want to do it blindly as new data packed in py3 will not have same problem. 
 just to avoid some performance impact.
 please suggest.

**Comment by vkorichkov-qb** [comment]
@mahadevTW, did the above code fragment help you? Did you use it to repack the py2 data?
