### ISSUE TITLE
Serializing a dictionary with integer keys yields malformed data

### ISSUE THREAD

**Issue by Justasic** [msgpack/msgpack-python#474]
When serializing a dictionary with integers as keys, it will produce malformed data that cannot be unserialized.
Example code:
```py
import msgpack
data = { 1: "a" }
msg = msgpack.packb(data)
print(msg)
# b'\x81\x01\xa1a'
print(msgpack.unpackb(msg))
# ValueError: int is not allowed for map key
```

It seems that the behavior of python3's json library will implicitly convert the integers to strings. You can test this with the code below:
```py
import json
data = { 1: "a" }
print(json.dumps(data))
# Out[3]: '{"1": "a"}'
```

I am not sure what the MessagePack specification specifies in this instance but I feel this should yield a ValueError when calling `packb` or implicitly convert the integers to strings as the json library does.

**Comment by methane** [comment]
msgpack allows int for map key.
But it is not safe for hashdos, because Python randomize hash only for str and bytes.

Since msgpack is used to unpack data from the internet, default behavior is safe; do not allow int keys.
You need to use `strict_map_key=False` option to unpack it.
