### ISSUE TITLE
Segmentation fault when calling getbuffer() on Packer object

### ISSUE THREAD

**Issue by thibaudmartinez** [msgpack/msgpack-python#479]
Hi there,

I'm trying to get the internal data of the Packer object in order to avoid unneeded copying, as documented [here](https://msgpack-python.readthedocs.io/en/latest/advanced.html).

The code is as follow :

````python
import msgpack

def do_the_job():
  packer = msgpack.Packer(autoreset=False)
  packer.pack(1)
  return packer.getbuffer()

bytes(do_the_job())
````

When running this snippet, I get the following error :

````bash
[1]    9018 segmentation fault (core dumped)  python script.py
````

I am using **Ubuntu 18.04.5 LTS** together with **msgpack 1.0.2**.

Thanks in advance for your help and for your work on this package !

**Comment by methane** [comment]
Thank you for report with snippets. But I can not reproduce it.

**Comment by thibaudmartinez** [comment]
Thank you for your reply.

I was able to reproduce the bug using the following Debian Docker image.

```Dockerfile
FROM python:3.9.5-slim-buster

RUN pip install --no-input msgpack==1.0.2

RUN echo "\
import msgpack\n\
\n\
def do_the_job():\n\
    packer = msgpack.Packer(autoreset=False)\n\
    packer.pack(1)\n\
    return packer.getbuffer()\n\
\n\
bytes(do_the_job())\
" > script.py
```

Can you try to reproduce the bug with the above setup ?

**Comment by methane** [comment]
Thank you, I can reproduce it now! I will investigate it in tomorrow.

**Comment by methane** [comment]
I got it. Memoryview object don't have reference to Packer.
When do_the_job() return, Packer object is released and Memoryview references "after free" memory.

**Comment by thibaudmartinez** [comment]
Great! Do you think it will be easy to fix in an upcoming release?

**Comment by methane** [comment]
It's not easy to fix. I can not release the fix anytime soon.
You shouldn't use the buffer after the Packer is released. It is unintended
usage.


2021年6月17日(木) 23:04 Thibaud Martinez ***@***.***>:

**Comment by jfolz** [comment]
I think this can be fixed relatively easily. Replace `PyMemoryView_FromMemory` ([here](https://github.com/msgpack/msgpack-python/blob/38dba9634e4efa7886a777b9e7c739dc148da457/msgpack/buff_converter.h)) with `PyMemoryView_FromBuffer(Py_buffer *view)` where [`view.obj`](https://docs.python.org/3/c-api/buffer.html#c.Py_buffer.obj) points to self and `incref` self.

**Comment by methane** [comment]
See here.
https://github.com/python/cpython/blob/7f01f77f8fabcfd7ddb5d99f12d6fc99af9af384/Objects/memoryobject.c#L775-L776

The best way is implementing the buffer protocol.
https://cython.readthedocs.io/en/latest/src/userguide/buffer.html

**Comment by jfolz** [comment]
Oh wow... that's really convoluted. So you need to implement `__getbuffer__` and `__releasebuffer__` magic methods, and `getbuffer` can then do `memoryview(self)`.
