### ISSUE TITLE
Stream processing requires knowledge of the data

### ISSUE THREAD

**Issue by mitsuhiko** [msgpack/msgpack-python#48]
I was just trying to use the recent updated msgpack library for stream processing but it still requires knowledge of the data that's incoming which I don't have in all cases.  What I want is a function that works roughly like this:

``` pycon
>>> u = msgpack.Unpacker(StringIO('\x94\x01\x02\x03\x04'))
>>> u.next_marker()
('map_start', 4)
>>> u.next_marker()
('value', 1)
>>> u.next_marker()
('value', 2)
>>> u.next_marker()
('value', 3)
>>> u.next_marker()
('value', 4)
```

Eg: next marker returns a tuple in the form `(marker, value)` where marker is one of `map_start` / `array_start` or `value`.  if it's `value` it will have the actual value as second item, if it's a container marker then it has the size in there.  This would allow trivial stream processing.  (a value marker would never contain a map or array, just scalar values).

**Comment by Atala** [comment]
+1, it would be a very nice thing to have IMHO.

Thanks,

Aloïs

**Comment by nikitinsm** [comment]
+1

**Comment by ThomasWaldmann** [comment]
note: this is only item in 0.4 milestone. but at same time labelled "0.5".

**Comment by salimm** [comment]
+1

**Comment by methane** [comment]
No.   We don't have this.  And I won't accept pull request implementation complicated.

Other major language's msgpack libraries doesn't support it too.
Until Ruby and Java implements it, this is very low priority.
Please use other format until msgpack adapts large data.

**Comment by methane** [comment]
I can not maintain more complexity. Unpacker is too complicated to me already.
So I won't add any more features.
