### ISSUE TITLE
impossible to create (pack) a "bin format" msgpack byte-array

### ISSUE THREAD

**Issue by edgimar** [msgpack/msgpack-python#480]
The [msgpack spec](https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family) defines the "bin format" as a means of differentiating string data from a 'raw binary' blob.  If I am working with an application that requires input msgpack data that uses this format (see below), then it is impossible to create valid msgpack to pass to the application.
```
+--------+--------+--------+--------+--------+========+
|  0xc6  |ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|ZZZZZZZZ|  data  |
+--------+--------+--------+--------+--------+========+
```

There should be some way (e.g. a flag that can be provided to packb) to pack a python `bytes` type as "bin format" msgpack.

**Comment by edgimar** [comment]
Ok, it looks like it is possible to pack with "bin format":  there is the `use_bin_type` flag that can be passed to `packb()`.  The problem is that there doesn't seem to be a way to have the following assertion hold true when `in_msgpack` contains data having "bin format" type:
```
py_data_struct = msgpack.loads(in_msgpack)
out_msgpack = msgpack.packb(py_data_struct)
assert(in_msgpack == out_msgpack)
```

**Comment by methane** [comment]
Your example is not runnable and doesn't make sense at all.

**Comment by edgimar** [comment]
@methane, I take offense at your remark, but will not react to it.  The example serves as a concise description of the problem -- here's a complete runnable version to help you understand:
```
in_msgpack = b'\x92\xa8a string\xc4\x03\x124V'
py_data_struct = msgpack.loads(in_msgpack)  # => [b'a string', b'\x124V']

out_msgpack = msgpack.packb(py_data_struct)  # => b'\x92\xa8a string\xa3\x124V'
print(in_msgpack == out_msgpack)  #  => False

out_msgpack = msgpack.packb(py_data_struct, use_bin_type=True)  # => b'\x92\xc4\x08a string\xc4\x03\x124V'
print(in_msgpack == out_msgpack)  #  => False
```

The point is that there is no possibility of `packb()` producing an array like `in_msgpack`.  When this kind of byte-array is needed to pass to an external application (and the application expects the byte-array to contain both strings and 'bin-type'), there is no clean way of doing this with the python msgpack module.

**Comment by edgimar** [comment]
I think I've tracked the problem down to using an older version of python-msgpack (0.6.2).  When testing my code in a newer version (1.0.2), both boolean expressions evaluate to True.

**Comment by methane** [comment]
```
in_msgpack = b'\x92\xa8a string\xc4\x03\x124V'
py_data_struct = msgpack.loads(in_msgpack)  # => [b'a string', b'\x124V']
```

If you took 3 minutes to read the README, you will find `raw=False` option too.
https://github.com/msgpack/msgpack-python#how-to-use

**Comment by edgimar** [comment]
Thanks for the tip -- I did look at it previously.  FWIW, I personally would find it easier to parse the documentation if all the args were described in one place, and clarifying examples were provided for each arg (similar to how python standard lib modules are documented).
