### ISSUE TITLE
Have build script fail on non-successful build of native (cython) extension and add explicit flag to use fallback

### ISSUE THREAD

**Issue by frittentheke** [msgpack/msgpack-python#481]
I recently debugged a tricky issue with OpenStack Neutron or rather oslo.privsep (https://github.com/openstack/oslo.privsep) which makes heavy use of your very appreciated python-msgpack. You'll find the whole story here: https://bugs.launchpad.net/cloud-archive/+bug/1937261.

The root cause for my observed issue was that the python-msgpack backport of version 0.6.2 to Ubuntu Bionic done by Ubuntu Cloud Archive was using the pure python fallback for pack/unpack. And this was simply due to Cython being too old as it lacked the support for `bytearray` which was only added in 0.29 https://github.com/cython/cython/pull/2573.

1. The version requirement stated in the warning at https://github.com/msgpack/msgpack-python/blob/38dba9634e4efa7886a777b9e7c739dc148da457/setup.py#L57 is not correct anymore, obviously `>=0.29` is true at least for python-msgpack version 0.6.2 and newer.

2. Honestly I believe your build script is just way too nice, skipping over every possible error condition when building the extension and then simply falling back to pure python: https://github.com/msgpack/msgpack-python/blob/38dba9634e4efa7886a777b9e7c739dc148da457/setup.py#L50
 I'd like to suggest to fail hard if Cython is not available or cannot build successfully and then add a flag to not build the extension and explicitly use the pure python fallback.
In this particular case only looking at the human readable build logs exposed this problem which only gets harder to debug with every additional layer.

3. Not allowing an at-runtime fallback is a whole other story - but could be sensible as well for use cases which will just not work with the performance available with fallback.

**Comment by methane** [comment]
Note that it is not relating to most users.

* binary wheels are provided for common platforms.
* Generated source file is bundled in source package (.tar.gz) so user do not need to run Cython.
