### ISSUE TITLE
Version compatibility between python and golang message pack

### ISSUE THREAD

**Issue by ifadams** [msgpack/msgpack-python#482]
Hello!

I'm trying to figure out what version of msgpack I should use to read data written using the 1.1.6 golang msgpack module.

When I try to read data using the  version 1.0.2 of the python msgpack, even though the input buffer binary identical (verified with a checksum) I keep getting extra data exceptions. I did verify that the same data is readable through the golang version.

Thanks for any tips or ideas you might have!

**Comment by methane** [comment]
Without reproducible example, I can say nothing.

**Comment by ifadams** [comment]
I can attempt provide isolated reproductions in both if desired. The initial question was to see if there was a known binary incompatibility across differing implementations of message pack.

**Comment by methane** [comment]
No. Many users including me uses msgpack during Python and Go.
