### ISSUE TITLE
Fully deprecate msgpack-python on pypi

### ISSUE THREAD

**Issue by mbway** [msgpack/msgpack-python#493]
I recently switched my requirements file from using conda to pip/pypi and accidentally missed that the package has a different name (just `msgpack`) on pypi. In conda-forge the name of the package is still [msgpack-python](https://anaconda.org/conda-forge/msgpack-python). This led to a different behaviour (unpacking into bytes rather than str by default) which was confusing.

edit: I was confused and hadn't actually checked the pypi page for msgpack-python specifically (which has no description other than to say the package is deprecated), only the msgpack one which refers to msgpack-python being deprecated. It is still confusing when moving from conda-forge to pypi though. Some warning printed during installation or at import might be useful?

**Comment by methane** [comment]
Actually, that's what I did when I renamed from msgpack-python to msgpack.

See this comment for why I stopped using dummy transition package.
https://github.com/msgpack/msgpack-python/issues/266#issuecomment-356162625

**Comment by methane** [comment]
And upstream issue is not closed yet.
https://github.com/pypa/pip/issues/4961

So pip may not support such transitional package.

**Comment by mbway** [comment]
would it break things if warnings were added in the meantime until pip is fixed? also with the recent release of pip getting a new resolver (https://github.com/pypa/pip/issues/988) it's possible that the issue is fixed?

**Comment by methane** [comment]
AFAIK, warning is not shown during pip install.
