### ISSUE TITLE
Uniqueness of serialization

### ISSUE THREAD

**Issue by cykerway** [msgpack/msgpack-python#494]
Does this tool guarantee the same object is always serialized to the same (byte-to-byte) binary representation?

To perceive this question more easily, think in `json` where we can serialize the same python object `{"a": 1}` into bytes `{"a": 1}` and `{"a":1}` (note the omitted space). They are all valid serializations of the same object but differ in their binary representations. `json` module provides options `sort_keys` and `separators` to control these nuances, which seem to be missing from this package. This package probably doesn't need these keys because its output is binary, but the idea is to keep the serialization stable and unique. Is there already such a guarantee? Else, what's the easiest way to make so on top of existing code?

Thank you

**Comment by jfolz** [comment]
I don't think any such guarantees are made and you cannot expect any specific encoding of your message between different versions of the library and especially different implementations. E.g., see the [spec for packing integers](https://github.com/msgpack/msgpack/blob/master/spec.md#int-format-family). There are 10 different integer formats with varying limits and signedness. An implementation can either spend cylces to determine the most compact format possible for each integer, or forego this for greater speed and use just one or a few of them.

**Comment by methane** [comment]
See this thread: https://github.com/msgpack/msgpack/issues/215

See also this topic: https://github.com/msgpack/msgpack/blob/8aa09e2a6a9180a49fc62ecfefe149f063cc5e4b/spec.md#profile
