### ISSUE TITLE
Support random access to objects within a serialized file stream

### ISSUE THREAD

**Issue by danpprince** [msgpack/msgpack-python#501]
First off, thanks for this project! Messagepack is an amazing technology, and this is a great implementation of it. 😁 When working with this library, there is one use case that I haven't been able to address, and I wonder if it already exists or is easy to add.

`msgpack.Unpacker` works quickly and effectively for _sequentially_ deserializing a stream of objects. However, for a use case I have in mind, I need random access to a single object in a stream of msgpack objects. 

I am able to implement this with [u-msgpack-python](https://github.com/vsergeev/u-msgpack-python) as in the following block, but it is not as optimized as this project and runs slower generally:

```python

import umsgpack


with open("test.msgpack", "wb") as f:
    for _ in range(1_000_000):
        umsgpack.dump("example unneeded data", f)
    
    first_target_position = f.tell()
    umsgpack.dump("first data to seek to", f)

    for _ in range(1_000_000):
        umsgpack.dump("more unneeded data", f)
    
    second_target_position = f.tell()
    umsgpack.dump("second data to seek to", f)


with open("test.msgpack", "rb") as f:
    f.seek(first_target_position)
    print(umsgpack.load(f))  # Outputs "first data to seek to"
    
    f.seek(second_target_position)
    print(umsgpack.load(f))  # Outputs "second data to seek to"
```
In this example, the read block runs almost instantly, without having to parse or explicitly skip the large number of unneeded objects in the beginning, and correctly finds the two objects of interest.

Assuming the same file written above is available, the following example does not work as expected:
```python

import msgpack

with open("test.msgpack", "rb") as f:
    unpacker = msgpack.Unpacker(f)

    f.seek(first_target_position)
    print(unpacker.unpack())  # Correctly outputs "first data to seek to"
       
    f.seek(second_target_position)
    print(unpacker.unpack())  # Outputs "more unneeded data"
```

Note that the functional equivalent, `msgpack.unpack()` also does not work here, as it raises an exception that there is extra data in the file.

Maybe is there a way to optionally disable the extra data exception? Or to add a `msgpack.Unpacker.seek()` method that would support this pattern? Or a way for the unpacker's file to track any seeks that happen to the file?

**Comment by jfolz** [comment]
I do random access on msgpack files in my library [datadings](https://datadings.readthedocs.io/en/latest/). Similar to your example I store the offsets of all samples in the set in another file, read however much data there is to read and use `unpackb` instead. This is good for multiple GB/s of throughput for my use case.

**Comment by danpprince** [comment]
> I do random access on msgpack files in my library [datadings](https://datadings.readthedocs.io/en/latest/). Similar to your example I store the offsets of all samples in the set in another file, read however much data there is to read and use `unpackb` instead. This is good for multiple GB/s of throughput for my use case.

Does this mean you have to save the offsets and the size of the object separately though? In my example, each object may be a variable size, so keeping the offset on its own doesn't seem to be enough to give `unpackb()` the input it needs due to the "extra data" exception behavior.

> If you want to leave reading the file to the `Unpacker`, creating a new object after seeking should do the trick.

I considered and tried this as well, but creating a new `Unpacker()` potentially hundreds of thousands of times adds a lot of run time overhead.

Thanks for the reply!

**Comment by jfolz** [comment]
> Does this mean you have to save the offsets and the size of the object separately though? In my example, each object may be a variable size, so keeping the offset on its own doesn't seem to be enough to give `unpackb()` the input it needs due to the "extra data" exception behavior.

No. I added a link to specific source. The offset file contains the start points of all messages. The length of message `i` is just `offset[i+1] - offset[i]`.

**Comment by jfolz** [comment]
Honestly though, creating a new object should be negligible compared to reading data from a file. Even when it's stored in a ramdisk.

**Comment by danpprince** [comment]
> > Does this mean you have to save the offsets and the size of the object separately though? In my example, each object may be a variable size, so keeping the offset on its own doesn't seem to be enough to give `unpackb()` the input it needs due to the "extra data" exception behavior.
> 
> No. I added a link to specific source. The offset file contains the start points of all messages. The length of message `i` is just `offset[i+1] - offset[i]`.

Oh interesting, I see what you mean now. The object size is implicitly known if you have all the offsets. I will experiment with that on my end, but am also interested to see if there are ideas to use the existing `Unpacker` pattern without this, or ideas on how to add it to this library.

> I would benchmark it. In my case using unpackb was the better choice. If your messages are very large - maybe more than a couple MB - then creating a new Unpacker may be better.

In my case, the files are in the range of hundreds of MB, and the messages are all a few KB, so the reads are quite fast and creating a new object takes a noticeable amount of time in comparison.

**Comment by jfolz** [comment]
I'd wager the issue is that the `Unpacker` will fill its buffer with at least 1 MB of data. You can try to set the `read_size` to something more reasonable for your data.

**Comment by danpprince** [comment]
> I'd wager the issue is that the `Unpacker` will fill its buffer with at least 1 MB of data. You can try to set the `read_size` to something more reasonable for your data.

Wow great thought, I set `Unpacker(f, read_size=2**12)` based on what I expected the size of my object to be approximately (around 4 KB) and that gave me a **10x speedup** from the default setting. I didn't even think about changing this buffer size but it makes sense in retrospect.

The following works well for me:
```python
with open("test.msgpack", "rb") as f:
    for offset in offsets:
        f.seek(offset)
        unpacked_object = msgpack.Unpacker(f, read_size=2**12).unpack()
```

This is slightly slower than the `unpackb()` approach with the exact object size read in from the file, but the implementation is a little simpler. Between the two, these are pretty good options. I'll close the issue now because I'm getting about the performance I need from this library.

@jfolz thanks a bunch for your help!
