### ISSUE TITLE
Improve error `ValueError: int is not allowed for map key`

### ISSUE THREAD

**Issue by adler-amorette** [msgpack/msgpack-python#502]
The error text should include that in order to allow it, you need to pass `strict_map_key` as `False`.

But I don't even understand why this error is raised only when unpacking. So I can pack `{1:2}` without setting `strict_map_key` and not get an error, but when unpacking it's somehow completely different. Doesn't make any sense to me.

**Comment by methane** [comment]
> But I don't even understand why this error is raised only when unpacking.

Because hashdos is problem only in unpacking.

**Comment by adler-amorette** [comment]
@methane from a user standpoint though it's not logical. If one can encode without any special parameters, they should be able to decode without any special parameters.

**Comment by adler-amorette** [comment]
@methane of course. But then the special cases should present in the encoding function too.

**Comment by methane** [comment]
I don't want to add such option only for mirroring with decoding option.
It doesn't make sense at all for me.
