### ISSUE TITLE
How to write to an existing buffer without copying?

### ISSUE THREAD

**Issue by lixin-wei** [msgpack/msgpack-python#512]
I do find `msgpack.pack(obj, stream)`

but it seems its implementation is calling `packer.pack(o)` first, and copying the entire bytes to the stream
```python
def pack(o, stream, **kwargs):
    """
    Pack object `o` and write it to `stream`

    See :class:`Packer` for options.
    """
    packer = Packer(**kwargs)
    stream.write(packer.pack(o))
```

This caused some performance issues in my system.

Is there any way to write to the `stream` directly instead of copying after serializing to bytes?

**Comment by methane** [comment]
Copy once is much faster than calling `stream.write()` for each objects.

**Comment by lixin-wei** [comment]
@methane Really? Consider a huge `bytes` object.

You need to copy it to your temp buffer first, and then write it to the stream. 2 times copy will happen.

While calling `stream.write()` directly only need to copy once.

Did I understand the current implementation correctly? If not please correct me, thanks!

**Comment by methane** [comment]
I don't want to make implementation complicated/fragile only for tiny use cases.

**Comment by lixin-wei** [comment]
So do you agree with the performance issue I mentioned above? I'm not sure whether I understand the current implementation correctly :)

I don't think it's a tiny use case, because every large object needs to be copied 2 times... I think everyone who wants to serialize large objects will meet this issue(like huge `bytes`, huge `str`).

**Comment by lixin-wei** [comment]
And would you please keep this issue open if it's true? So that others can get information from this issue.

**Comment by jcrist** [comment]
Just stumbled upon this issue. For anyone else running into this use case, you may be interested in using the msgpack implementation in [msgspec](https://jcristharif.com/msgspec/index.html) which supports encoding into a pre-allocated `bytearray`.

https://jcristharif.com/msgspec/perf-tips.html#reusing-an-output-buffer

```python
In [1]: import msgspec

In [2]: enc = msgspec.msgpack.Encoder()

In [3]: buffer = bytearray()  # a reusable bytearray buffer

In [4]: msg = {"x": 1, "y": 2}  # an example message

In [5]: enc.encode_into(msg, buffer)  # encode into the existing buffer

In [6]: buffer
Out[6]: bytearray(b'\x82\xa1x\x01\xa1y\x02')

In [7]: msg2 = {"x": 3, "y": 4}  # a new message

In [8]: enc.encode_into(msg2, buffer)

In [9]: buffer
Out[9]: bytearray(b'\x82\xa1x\x03\xa1y\x04')
```
