### ISSUE TITLE
Option to parse first object only and ignore extra bytes

### ISSUE THREAD

**Issue by kjsdf7wr3** [msgpack/msgpack-python#515]
Is it possible to add an option to stop parsing after first complete object and ignore extra bytes?
https://github.com/msgpack/msgpack-python/blob/edca770071fc702e0b4c33f87fb0fa3682b486b4/msgpack/_unpacker.pyx#L155

In an appliction I receive data that is padded and currently I remove bytes at the end until there is no more ExtraData exception.
For me it is impossible to know the amount of padding bytes, except that they occur after the first complete object/value.

**Comment by methane** [comment]
You can get object and remaining data from ExtraData.

https://github.com/msgpack/msgpack-python/blob/edca770071fc702e0b4c33f87fb0fa3682b486b4/msgpack/exceptions.py#L30-L39
