### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by sblondon** [msgpack/msgpack-python#518]
According to [pypi page](https://pypi.org/project/msgpack/), the python2 support has been dropped with release 1.0.
The main branch in the repository is currently v.1.0.4 release (https://github.com/msgpack/msgpack-python/blob/main/msgpack/__init__.py#L9).

However, there is python2 specific code in the repository. For example:

 - `setup.py` checks for python2
 - `msgpack/fallback.py` could be simplified
 - python2 is checked in `tox.ini`
 - `test/test_timestamp.py` skip some tests with python2 (`@pytest.mark.skipif(sys.version_info[0] == 2`) ; `test/test_extension.py` has also a conditional

Are you interested by a PR to remove them?

**Comment by methane** [comment]
> According to [pypi page](https://pypi.org/project/msgpack/), the python2 support has been dropped with release 1.0.

![image](https://user-images.githubusercontent.com/199592/189292861-90b4d0e6-ded5-4271-a50a-3a8e4a280c74.png)

Read it again.

**Comment by methane** [comment]
> Are you interested by a PR to remove them?

pip dropped Python 2 support.  So I will drop it too.
I don't have actual plan for msgpack 1.1 or 2.0. But PR to remove them is welcome.
