### ISSUE TITLE
master branch: ntohs / ntohl undeclared

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#521]
https://github.com/borgbackup/borg/pull/7181#issuecomment-1336118006

See there:

First all the changes from msgpack master were ported to our bundled msgpack in borgbackup 1.1-maint branch.

Then CI was failing. ntohs / ntohl undeclared.

Then the change that removed the include was reverted which made CI happy again.

So I guess you need to revert this change in master branch here also.

Note: the bundled msgpack in borg 1.1-maint is a slightly patched version 0.5.6, see there: https://github.com/borgbackup/borg/blob/e79986b2835291431f04683423304a02b039c0c1/src/borg/algorithms/msgpack/_version.py

**Comment by klemensn** [comment]
As explained here: https://github.com/msgpack/msgpack-python/pull/513#issuecomment-1336170867

**Comment by methane** [comment]
See #514

**Comment by ThomasWaldmann** [comment]
Oh, sorry, looks like I missed that. @_@

**Comment by ThomasWaldmann** [comment]
Guess this can be closed. Only thing left to do is to release the fixed msgpack code.
