### ISSUE TITLE
Encoding to unsupported byte for machines running Linux

### ISSUE THREAD

**Issue by shaon-chowdhury** [msgpack/msgpack-python#525]
I'm getting the following error when unpacking a packed byte string. What is strange this error doesn't occur on a laptop running on MacOS Ventura but does on Linux machines.

```'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte```

To pack the object, I use:
```
msgpack.packb(object, use_bin_type=True,)
```

To unpack, I use this:
```
msgpack.unpackb(object_to_deserialize, raw=False,)
```

**Comment by methane** [comment]
Not a valid issue report. Please use some Python community to ask support.
