### ISSUE TITLE
memoryview is too large when encoding large arrays

### ISSUE THREAD

**Issue by Gilthans** [msgpack/msgpack-python#532]
Hey there,
We're trying to use messagepack to serialize classes with very large data matrices.
When trying to save them though, we got 'memoryview is too large'.
Looking at the code, it seems there's a check if the length of data is more than 2**32 an exception is raised.

Is this hardcoded value a format limitation, or an implementation detail?

**Comment by jfolz** [comment]
It's a format limitation: https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family
