### ISSUE TITLE
`strict_map_key` is supported by which version ?

### ISSUE THREAD

**Issue by luochen1990** [msgpack/msgpack-python#537]
I can get following error in `msgpack-python==0.5.6`:

```
TypeError("__init__() got an unexpected keyward argument 'strict_map_key'")
```

some related context:

```
msgpack==1.0.5
msgpack-numpy==0.4.8
msgpack-python==0.5.6
msgpack-types==0.2.0
```

Is there any document about 'strict_map_key' is introduced/removed from which version?

**Comment by methane** [comment]
You shouldn't msgpack-python. It conflicts with msgpack and break your venv.

**Comment by luochen1990** [comment]
Thanks, that information is helpful :)
