### ISSUE TITLE
Migrate from setup.cfg to pyproject.toml

### ISSUE THREAD

**Issue by methane** [msgpack/msgpack-python#540]
* [x] flake8 section can be removed by moving to ruff. (#542)
* [x] metadata can be converted to PEP 621.

**Comment by ThomasWaldmann** [comment]
Maybe interesting: https://pypi.org/project/pyproject-flake8/

**Comment by ThomasWaldmann** [comment]
Besides the flake8 section, what else is to do for this issue?

**Comment by methane** [comment]
I updated the issue comment.

**Comment by ThomasWaldmann** [comment]
https://peps.python.org/pep-0621/ "PEP 621 – Storing project metadata in pyproject.toml"

**Comment by ThomasWaldmann** [comment]
I'll try to make a PR for pep621.

**Comment by ThomasWaldmann** [comment]
See PR #555.
