### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#544]
I tested `borgbackup` with Python 3.12 prerelease there:

https://github.com/borgbackup/borg/pull/7592

Py312 github CI run is there:

https://github.com/borgbackup/borg/actions/runs/5210974256/jobs/9402730199

Besides the ton of warnings, it was successful except that it noticed that borg uses "slow msgpack" (the pure python fallback implementation inside msgpack, not the compiled C implementation).

Python 3.12 release is expected some time later this year, maybe october, but I guess it would be nice to have a compatible msgpack package on pypi early, so it can get some pre-release testing.

The pure-python code seems to work (as expected), but I guess the C and Cython code might be more interesting. For borg, we needed to use either the latest 0.29.x or 3.0.x Cython releases to get Py312 compatible code.

**Comment by methane** [comment]
I will release 1.1 before 3.12 become RC.

**Comment by ThomasWaldmann** [comment]
https://www.python.org/downloads/release/python-3120rc1/

**Comment by ThomasWaldmann** [comment]
Maybe we could have a py312 compatible pypi package with the quick and easy part of that milestone and shift some of the optional stuff that might take longer to 1.1.1?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/actions/runs/6180101088/job/16776034673?pr=7592

So, msgpack 1.0.6rc1 got some testing there with python 3.12, looks good!

Guess we can close this ticket, once 1.0.6 is out.

**Comment by methane** [comment]
I released 1.0.6 now.
