### ISSUE TITLE
SystemError: error return without exception set

### ISSUE THREAD

**Issue by bobpoekert** [msgpack/msgpack-python#57]
I've been getting errors without exception objects where calls to msgpack.unpackb are the last line in the stacktrace. Could there be somewhere inside the C implementation of the msgpack bindings that is returning an error code but failing to set an exception (ex: with PyErr_SetString)?

To reproduce:

```
msgpack.unpackb('\xd7\xa3p=\n\xb7|@')
```

**Comment by rggjan** [comment]
I can still get this issue on some (erronous) files, how can I reopen this issue?

**Comment by derpston** [comment]
What version of msgpack-python are you using?

**Comment by rggjan** [comment]
0.4.6, as written in #140 (sorry for the duplicate, but I didn't know how to reopen)
