### ISSUE TITLE
Distribute a pure-Python build

### ISSUE THREAD

**Issue by jvolkman** [msgpack/msgpack-python#576]
I've seen a number of issues (usually newer versions of Python are different architectures) where the solution is to set `MSGPACK_PUREPYTHON=1` to build a pure-Python wheel. I'm currently working on a use-case where I can only support pure-Python wheels, and `msgpack` is the only package in my transitive set that doesn't provide one.

Given that a pure-Python version _can_ be built, it would be nice if it was also distributed via pypi. `pip` should prefer the platform-specific native versions if one is found to be compatible, and only fall back to the pure-python version if not.

**Comment by methane** [comment]
It is not msgpack specific problem. All libraries with speedup module have same issue.
Do you know any other major library do it successfully?

**Comment by jvolkman** [comment]
Hi @methane,

I agree that the issue of extension module incompatibility isn't specific to `msgpack`. All packages that ship native modules deal with this. But what is relatively special to `msgpack` is that it can optionally build a fallback, pure-python wheel.

I've found a handful of other popular libraries with a similar situation.
1. simplejson - perhaps most relevant to this project - ships a fallback wheel which you can see [here](https://pypi.org/project/simplejson/#files).  Its README says "It is pure Python code with no dependencies, but includes an optional C extension for a serious speed boost". You can see [here](https://github.com/simplejson/simplejson/blob/master/.github/workflows/build-and-deploy.yml#L76-L77) in its github workflow where it builds the pure-python wheel outside of cibuildwheel.
2. SQLAlchemy - a very popular Python ORM
3. Older versions of `pydantic` before 2.x

There are others. If you're curious, you can query [this dataset ](https://py-code.org/datasets) with something like
```
select distinct (project_name, project_version)
from pypi p1 join pypi p2 using (project_name, project_version)
where position(p1.project_release, 'py3-none-any') != 0
and splitByChar('-', p2.project_release)[4] = 'cp311'
order by project_name, project_version
```
