### ISSUE TITLE
memory leak observed in python 3.12.1

### ISSUE THREAD

**Issue by TheRealMcoy** [msgpack/msgpack-python#579]
This library appears to leak memory in Unpacker method under Python 3.12.1

reproducer script:
```
import msgpack
from io import BytesIO

while True:

   buf = BytesIO()
   for i in range(100):
      buf.write(msgpack.packb(i, use_bin_type=True))

   buf.seek(0)

   unpacker = msgpack.Unpacker(buf, raw=False)
   for unpacked in unpacker:
       print(unpacked)
```

Python 3.11.7 after 10 minute run:
![python3 11](https://github.com/msgpack/msgpack-python/assets/158620886/5d6224cd-cc78-4a79-ad81-c58c5e5f6385)

Python 3.12.1 after 10 minute run:
![python3 12](https://github.com/msgpack/msgpack-python/assets/158620886/ae5c0167-17fe-461c-b38a-952cb5d79df1)

**Comment by senyai** [comment]
I have similar situation, but my test case is a bit different:
```python
from msgpack import Unpacker, packb

unpacker = Unpacker()
network_packet = packb(None)

for i in range(2000000):
    unpacker.feed(network_packet)
    for unpacked in unpacker:
        pass
```

**Comment by methane** [comment]
@TheRealMcoy @senyai do you use macOS?

**Comment by methane** [comment]
Sorry, OS is not related.

https://github.com/cython/cython/issues/5724 caused it.
Until I make mew release, manually run Cython locally will fix it.

**Comment by senyai** [comment]
@methane recompiling with new cython fixed it for me, much appreciated.

**Comment by TheRealMcoy** [comment]
@methane the latest [1.0.8](https://github.com/msgpack/msgpack-python/releases/tag/v1.0.8) has resolved the memory leak, many thanks!
