### ISSUE TITLE
The msgpack wheel ships with .cpp, .h and .pyx files

### ISSUE THREAD

**Issue by sbidoul** [msgpack/msgpack-python#580]
Hi there,

It seems that since version 1.0.6, the msgpack wheels ship the .cpp, .h and .pyx files. Is that intended?

This showed up in the pip vendoring upgrade process and I need to decide if we wait for a new release without these files or adapt the pip vendoring process to remove them.

**Comment by methane** [comment]
Not intended, and fixed in #577. Next version will not contain them.
