### ISSUE TITLE
[Feature request] Cast integer to the lowest precision without overflow during encoding

### ISSUE THREAD

**Issue by caniko** [msgpack/msgpack-python#594]
**Issue**
Message pack integer, behavior is different across golang and Python. Consider that we have the integer `10000`, and store this in Python, it will most likely be int64 under the hood. This is not the case in go, when encoding int `10000` it may select a lower precision like int32 as there is no overflow.

This leads to different values across the languages. We need a way for Python to mimic this behavior for the bytes to be identical across different languages in the stack—in our case, golang and Python.

**Solution**
When `lowest_precision` in `packb` is True, cast integers to the lowest precision without causing overflow during encoding. I would also consider using unsigned if the integer is positive, could be a secondary kwarg.

**The "your issue, and not ours" solution**
Add this to the documentation so that others don't have the same pain as we did, figure this out. Include an example of how to force the precision using `ctypes`:
```python
import ctypes

def to_uint32(x):
    return ctypes.c_uint32(x).value

# Example usage
num = to_uint32(123456789)
print(num)  # Output: 123456789

# Example: Overflow behavior
num = to_uint32(2**32 + 123)
print(num)  # Output: 123, demonstrating overflow
```

**Comment by methane** [comment]
Doesn't make sense at all.
Wrong guess, wrong solution.

**Comment by methane** [comment]
https://github.com/msgpack/msgpack/blob/master/spec.md

**Comment by caniko** [comment]
Let's try to be civil, and try to steer away from antipatterns. I realize I had it the other way around, the issue is on the `golang` side. It is Python that picks an arbitrary precision on integers.

**Comment by methane** [comment]
> @methane, let's try to be civil, and try to steer away from antipatterns. Please don't close an issue before there is a mutual understanding of the problem.

Let's try to be civil, do not post issue until you understand the issue or you can provide minimum complete step to reproduce. OSS maintainers are receiving dozen notifications every day and tend to ignore notification and burn out.

**Comment by caniko** [comment]
OK
