### ISSUE TITLE
1.1.0 Pyodide Compatibility

### ISSUE THREAD

**Issue by riyavsinha** [msgpack/msgpack-python#627]
I have a package I'm trying to install with Pyodide that requires v1.1.0, but there is no pure Python wheel available for this version. I do see that for v1.0.8 there was one.

Would it be possible to release a pure Python wheel for v1.1.0? 

Error:
```
Can't find a pure Python 3 wheel for 'msgpack==1.1.0' See:
https://pyodide.org/en/stable/usage/faq.html#why-can-t-
micropip-find-a-pure-python-wheel-for-a-package You can use
"await micropip.install(..., keep_going=True)' to get a list of all packages with missing wheels.
```

**Comment by methane** [comment]
Reason behind not releasing pure python wheel: 
https://github.com/msgpack/msgpack-python/issues/576#issuecomment-1987168845

Try this instead:
https://pyodide.org/en/stable/development/building-and-testing-packages.html#building-and-testing-packages-out-of-tree

**Comment by riyavsinha** [comment]
Thank you for the response! I will try to build the WASM version in Pyodide

**Comment by edgarrmondragon** [comment]
> https://pyodide.org/en/stable/development/building-and-testing-packages.html#building-and-testing-packages-out-of-tree

The pyodide folks seem to have moved some of the docs pages, so that's a dead link now.

https://pyodide.org/en/0.27.1/development/building-and-testing-packages.html#building-and-testing-python-packages-out-of-tree
