### ISSUE TITLE
Error installing on x86_64

### ISSUE THREAD

**Issue by rroodll** [msgpack/msgpack-python#628]
I am building a new system that is Intel CPU based and pip install is failing for msgpack.
I have cloned locally and `pip install .` from there fails as well. Based on #625 I am assuming I am missing some Visual Studio component? Below is the error from my install, I am running VS Community edition with Visual C++ installed. Can someone comment?

      _cmsgpack.c
      c1: fatal error C1083: Cannot open source file: 'msgpack/_cmsgpack.c': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

       note: This error originates from a subprocess, and is likely not a problem with pip.
       ERROR: Failed building wheel for msgpack
       Failed to build msgpack
       ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgpack)

**Comment by methane** [comment]
I don't support `pip install` from git clone. You need to cythonize manually.

**Comment by rroodll** [comment]
ok, great. Thanks for the quick response.
