### ISSUE TITLE
segfault when using hooks with Unpacker

### ISSUE THREAD

**Issue by MurphyMc** [msgpack/msgpack-python#67]
Unlike the one-shot unpacker, when you're using the streaming Unpacker class, the reference count on callback functions (e.g., object_hook) needs to be incremented.

As it stands in 0.3.0, passing a callback with limited lifetime (e.g., an instance method) results in segfaults or SystemErrors.

**Comment by ThomasWaldmann** [comment]
Affects 0.3.0 also (version in Ubuntu 14.04 LTS).
