### ISSUE TITLE
Allow custom encoding (not character encoding but default function encoding) of unicode strings

### ISSUE THREAD

**Issue by Thyfate** [msgpack/msgpack-python#73]
As of now, I could not find a way to both support unicode and strings (or bytes) in a way which enables a transparent round trip (encode then decode).

However, this could easily be implemented if the unicode type could be custom encoded by the "default" function hook. In the latest version, if no character-encoding is proposed for the "pack" function, an exception is raised when a unicode instance is serialized.

If this exception were removed (line 38 from _packer.pyx) and the unicode case was then skipped when the character-encoding is not provided, a custom handler could be implemented in the default function...

**Comment by methane** [comment]
First of all, I'm sorry for late response.
I hate adding more option to msgpack-python.
I close this issue since new msgpack spec may support your situation.
If you doesn't satisfied with current msgpack-python, please make new issue.
