### ISSUE TITLE
AIX build problem

### ISSUE THREAD

**Issue by kriberg** [msgpack/msgpack-python#80]
I'm having a problem building the C++ extensions on AIX. It might be completely unrelated to msgpack-python itself, albeit I have built other python libraries using C++ extensions.

This is the output I get:

<pre>
# python setup.py build
running build
running build_py
running build_ext
building 'msgpack._packer' extension
gcc -pthread -DNDEBUG -O -maix32 -g -mminimal-toc -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O2 -I/opt/freeware/include -D__BIG_ENDIAN__=1 -I. -I/opt/freeware/include/python2.7 -c msgpack/_packer.cpp -o build/temp.aix-7.1-2.7/msgpack/_packer.o
g++ gcc -pthread -bI:/opt/freeware/lib/python2.7/config/python.exp -L/opt/freeware/lib -L/opt/freeware/lib -lncurses -Wl,-blibpath:/opt/freeware/lib:/usr/lib:/lib -Wl,-bmaxdata:0x80000000 -L/opt/freeware/lib -Wl,-blibpath:/opt/freeware/lib:/usr/lib:/lib -Wl,-bmaxdata:0x80000000 -maix32 -g -mminimal-toc -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O2 -I/opt/freeware/include build/temp.aix-7.1-2.7/msgpack/_packer.o -o build/lib.aix-7.1-2.7/msgpack/_packer.so
g++: error: gcc: No such file or directory
g++: error: unrecognized command line option '-bI:/opt/freeware/lib/python2.7/config/python.exp'
WARNING: Failed to compile extensiom modules.
msgpack uses fallback pure python implementation.
command 'g++' failed with exit status 1
building 'msgpack._unpacker' extension
gcc -pthread -DNDEBUG -O -maix32 -g -mminimal-toc -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O2 -I/opt/freeware/include -D__BIG_ENDIAN__=1 -I. -I/opt/freeware/include/python2.7 -c msgpack/_unpacker.cpp -o build/temp.aix-7.1-2.7/msgpack/_unpacker.o
In file included from msgpack/_unpacker.cpp:316:0:
msgpack/unpack.h: In function 'int unpack_callback_ext(unpack_user*, const char*, const char*, unsigned int, PyObject**)':
msgpack/unpack.h:250:77: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
     py = PyObject_CallFunction(u->ext_hook, "(is#)", typecode, pos, lenght-1);
                                                                             ^
g++ gcc -pthread -bI:/opt/freeware/lib/python2.7/config/python.exp -L/opt/freeware/lib -L/opt/freeware/lib -lncurses -Wl,-blibpath:/opt/freeware/lib:/usr/lib:/lib -Wl,-bmaxdata:0x80000000 -L/opt/freeware/lib -Wl,-blibpath:/opt/freeware/lib:/usr/lib:/lib -Wl,-bmaxdata:0x80000000 -maix32 -g -mminimal-toc -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O2 -I/opt/freeware/include build/temp.aix-7.1-2.7/msgpack/_unpacker.o -o build/lib.aix-7.1-2.7/msgpack/_unpacker.so
g++: error: gcc: No such file or directory
g++: error: unrecognized command line option '-bI:/opt/freeware/lib/python2.7/config/python.exp'
WARNING: Failed to compile extensiom modules.
msgpack uses fallback pure python implementation.
command 'g++' failed with exit status 1
</pre>

These are my compiler flags:
OBJECT_MODE=32
LDFLAGS="-L/opt/freeware/lib -Wl,-blibpath:/opt/freeware/lib:/usr/lib:/lib -Wl,-bmaxdata:0x80000000"
CFLAGS="-maix32 -g -mminimal-toc -DSYSV -D_AIX -D_AIX32 -D_AIX41 -D_AIX43 -D_AIX51 -D_ALL_SOURCE -DFUNCPROTO=15 -O2 -I/opt/freeware/include"
CXXFLAGS=$CFLAGS

**Comment by methane** [comment]
I have no idea.
It seems general problem when using cpp code in extension on AIX,
and msgpack is completely unrelated.
I think stackoverflow is far better than here.  There are no AIX devs here.
