### ISSUE TITLE
tuple and list are indistinguishable

### ISSUE THREAD

**Issue by faerot** [msgpack/msgpack-python#98]
I am trying to build universal serializaion system on top of msgpack, similar to standard pickle, except more secure. The system needs to be accurate at saving/restoring data.

The problem is current implementation stores list and tuple as sequence and type information is lost on loading it back. Unfortunately it is impossible to treat tuple and list differently in current version of the library and while it is trivial to fix, it requires altering msgpack.

What is needed is extra argument to Packer. Something like tuple_autoconvert=False. If this argument is set, msgpack would not serialize tuple as list, but treat it as unknown type and will pass it's serialization to default. This way it would be possible to implement custom serialization to tuple via extension type, etc.

**Comment by campagnola** [comment]
I'd love to have this option as well.

**Comment by pallas** [comment]
Why not convert tuples to fixarray and arrays to array?

**Comment by filmor** [comment]
`fixarray` and `array` are semantically the same thing in msgpack, the `fix` just means that the length (up to 15) is encoded directly in the leading byte, see https://github.com/msgpack/msgpack/blob/master/spec.md#array-format-family.
