### ISSUE TITLE
unpack should decode string types by default

### ISSUE THREAD

**Issue by minrk** [msgpack/msgpack-python#99]
msgpack has native text and binary types, but the default behavior of `msgpack.unpackb`  of the text type is to return the still-encoded bytes, rather than the decoded text (unicode on Python 2, str on Python 3). The msgpack spec [specifies](https://github.com/msgpack/msgpack/blob/master/spec.md#type-system) that strings are utf-8, so it should be a logical default.

Changing the default value for `Unpacker.encoding` from `None` to `utf-8` would introduce the desired behavior, but it would be problematic for anyone relying on the default behavior. So I thought I would ask before opening a PR. Would a pull request with this change be accepted?

**Comment by oconnor663** [comment]
This bit me today. If you don't want to change this by default, I think it's worth clearly documenting in your README: **Note that msgpack-python unpacks MessagePack strings into Python bytes.**

**Comment by ThomasWaldmann** [comment]
Bit me today also.

This is just inconsistent and it is a joke to pack to 2 different representations if the unpacker then just unpacks to same thing:

```
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from msgpack import *
>>> unpackb(packb(b'foo'))
b'foo'                                                          # OK
>>> unpackb(packb('foo'))
b'foo'                                                         # maybe OK (bad old spec)
>>> unpackb(packb(b'foo', use_bin_type=True))
b'foo'                                                         # OK
>>> unpackb(packb('foo', use_bin_type=True))
b'foo'                                                         # WTF!!!
>>> packb(b'foo', use_bin_type=True)
b'\xc4\x03foo'                                           # Note it is different from next one.
>>> packb('foo', use_bin_type=True)
b'\xa3foo'                                                 # Note it is different from previous.
>>> unpackb(packb('foo', use_bin_type=True), encoding='utf-8')
'foo'                                                          # Solved, but that should be the default behaviour.
```

**Comment by methane** [comment]
msgpack is format for not only Python.
Other language may pack non utf-8 data into 'raw' type.
So you should specify it manually for now.

The default may be changed when other major languages pack non-string into bin type.
But it's not happen in foreseeable future.

**Comment by methane** [comment]
*Bitten in the case of Python to Python* doesn't enough reason to change API for
cross language serialization format like JSON.

**Comment by minrk** [comment]
I think the proposal for change here only affects deserialization on Python, and doesn't affect any other languages. Python has a text type, it is unicode on Python 2 and str on Python 3. msgpack also has a text type (Raw String), so it seems logical for the msgpack Python API to map the Python text type to the msgpack text type and vice versa. It doesn't matter where the message came from, a msgpack Raw String should arrive as unicode/py3-str in Python.

I think the only case that is ambiguous is *encoding* `str` on Python 2, which is a common, if pathological, type in which to store text in Python 2. If it were up to me, I would treat Python 2 str as bytes, since that's the type it really is, and require unicode objects for encoding as text, but I acknowledge that text-as-str is an unfortunately common behavior on Python 2. If no change is desired for encoding, I think that's okay (I would take the Python 3 path, and treat py2 str as bytes, since that is what it really is).

I don't think there is any case where msgpack text should be deserialized to bytes on Python 3. Can anyone come up with one?

Since Python 3 has a much clearer separation of bytes and text, I think there is an opportunity for msgpack's behavior to be more sensible on Python 3, and possibly leave the current ambiguous behavior on Python 2 (i.e. Raw String always deserializes to `str`, which is the right thing to do on Python 3, and no change on Python 2). I still think the Python 3 way makes more sense even on Python 2, but this may be a less disruptive change.

**Comment by methane** [comment]
@minrk It affects deserializing data coming from other languages or old msgpack-python.
This is issue of "interoperability vs convenience".
I think default setting should take interoperability since msgpack is language insensitive format.

**Comment by methane** [comment]
When proposing changing default behavior, please consider about interoperability first.

Decoder default setting should be safe to decoding data from other language (or old msgpack-python).

Encoder default setting should be safe to pass serialized data to other language (or old msgpack-python).

**Comment by minrk** [comment]
> It affects deserializing data coming from other languages or old msgpack-python.

Exactly, which does not affect interoperability, but it does affect backward compatibility. The msgpack Raw String type should always, unambiguously deserialise to `str` on Python 3. Is there any case where that's not true? How else is Python supposed to distinguish between Raw String and Raw Bytes, which are distinct in msgpack, and should be distinct in Python, which has two different types to represent those?

> Decoder default setting should be safe to decoding data from other language (or old msgpack-python).

Decoding Raw String to unicode/str is safe. Is there any case where it is not? Raw Bytes should still be bytes.

> Encoder default setting should be safe to pass serialized data to other language (or old msgpack-python).

Is Raw String not supported in older msgpack versions? If so, I'm more sympathetic, but distinguishing Bytes from Text is a huge problem solved by the Raw String/Raw Bytes types. Users sending text and/or raw data should be strongly encouraged to adopt them.

I fully respect backward compatibility of the API. Perhaps there could be a new API that defines different, more sensible default behavior for Raw Strings? e.g. an explicit `msgpack.v2.packb`, which allows users to make the assumption of more recent msgpack support in order to make full use of the improved spec?

**Comment by methane** [comment]
> The msgpack Raw String type should always, unambiguously deserialise to str on Python 3. Is there any case where that's not true?

Old msgpack spec doesn't distinguish raw and bin.
Some languages doesn't distinguish raw and bin too. (e.g. PHP)
So msgpack spec **allows** raw type contains non UTF-8 sequence.

> * String objects may contain invalid byte sequence and the behavior of a deserializer depends on the actual implementation when it received invalid byte sequence
>     * Deserializers should provide functionality to get the original byte array so that applications can decide how to handle the object

-- [Spec > limitation](https://github.com/msgpack/msgpack/blob/master/spec.md#limitation)

**Comment by minrk** [comment]
@methane thanks, I had missed that Raw String is effectively indistinguishable from Raw Binary, since it officially allows arbitrary bytes with undefined behavior. My preference would still be to decode Strings as utf8 to unicode/str, since that's always the right type for representing Strings in Python 2 and 3, but since the spec recommends against raising errors for invalid text, the only logical result is returning bytes there. In that case, I would decode if utf8, else return the raw/invalid bytes, but I acknowledge returning different types based on contents is not a good route.

**Comment by filmor** [comment]
Would it be an option to just pass the msgpack version to the pack/unpack functions, like it's done for pickle? I'd like this to default to the newer version at least for unpacking.

The current interface (v2 = `use_bin_type=True` on `Packer` and `encoding="utf8"` on `Unpacker`) is just not very expressive.

**Comment by alex-eri** [comment]
I have same problem with duct keys

**Comment by coleifer** [comment]
I'm very confused by the behavior of this library.

Both Python 2 and 3 support separate types for representing binary data vs text.

Msgpack supports separate types for representing binary data vs text.

Why does this library go to such extraordinary lengths to complicate what should be a rather simple and natural translation?

I expect:

```python
In [2]: unpackb(packb(u'text'))
Out[2]: u'text'

In [3]: unpackb(packb(b'bytes'))
Out[3]: b'bytes'
```

Unless I use some arbitrary and crazy combination of keyword arguments, the behavior is completely different.

What if I wanted to support a dictionary keyed by unicode strings whose values are arbitrary bytes? Is that even possible with this driver?
